### ISSUE TITLE
CI on travis.org stopped working.

### ISSUE THREAD

**Issue by thomasdziedzic** [lobsters/lobsters#1011]
The latest travis run on master is https://travis-ci.org/github/lobsters/lobsters/builds/772510293 which has a banner stating:

> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

Travis.com has a free plan at https://www.travis-ci.com/plans but I'm not sure what 10,000 credits means.

We should probably switch to travis.com or find another vendor so that CI will continue to work in the future.

**Comment by soatok** [comment]
Github Actions has been the main thing I've moved my projects to.

Just replace `.travis.yml` with a `.github/workflows/ci.yml` file configured for the exact Rails environments you want to test on. You can even verify the correctness of this workflow in the Checks tab of the pull request that makes this change without having to commit a broken CI to the main branch.

**Comment by pushcx** [comment]
I didn't realize this was here when I opened #1022. Thanks for pointing it out. As soatok suggested, we're moving over to GitHub Actions in #1042.
