### ISSUE TITLE
Reply notification is shown once when visiting the page with the reply

### ISSUE THREAD

**Issue by strugee** [lobsters/lobsters#1013]
STR: 

1. Get a reply, so that the "1 reply" red text is shown
2. Visit the page with the reply some other way. For example: use the Your Threads page to get to it
3. Notice how the loaded page says "1 reply" still, even though you're now reading the reply
4. Refresh the page and notice the reply text is changed back to "Replies" and is no longer red

**Comment by pushcx** [comment]
I'm OK with it working this way, it's clear enough what state the user is looking at.
