### ISSUE TITLE
/about needs updating for DigitalOcean

### ISSUE THREAD

**Issue by strugee** [lobsters/lobsters#1014]
> Lobsters is hosted at DigitalOcean. We recently migrated and our setup is still in flux. **Please hassle pushcx if he hasn't filled in details by March 2021.**

Emphasis mine; cc @pushcx :P

**Comment by pushcx** [comment]
https://github.com/lobsters/lobsters/commit/6e730e97ff1d0a5ee4d71b76f339002a441d52a8

Thanks for hassling me, this is done.
