### ISSUE TITLE
Reset Password URL links to "Example.com"

### ISSUE THREAD

**Issue by mibzman** [lobsters/lobsters#1018]
When triggering a password reset email, the reset link is `https://example.com/login/set_new_password?token=XXX&username=XXX` instead of `https://lobste.rs/login/set_new_password?token=XXX&username=XXX`.

**Comment by pushcx** [comment]
Thanks to the several people who reported or confirmed this bug.

This was a weird prod issue. I beat my head on it for a while without understanding how it crept in, but there's literally one place `example.com` appeared in our config and I confirmed that replacing it in prod fixed the issue, so I committed 293c82e. Not very satisfying to fix it without understanding it fully, but clearly understanding things is irrelevant to programming.
