### ISSUE TITLE
Flag link in comment byline does not show flagging menu on /comments page

### ISSUE THREAD

**Issue by kconner** [lobsters/lobsters#1027]
Normally when you click the "flag" link in a comment byline, this menu appears:
![working](https://user-images.githubusercontent.com/602569/133674686-64f756ec-b0b9-436f-82c1-d0d703906cde.png)

If I try that on the /comments page, I do not see the menu. The only markup added to the DOM is an empty `div`, `#flag_why_shadow`.

Observed in mobile Safari 15 and desktop Safari Technology Preview 131 (15.0 prerelease).

**Comment by pushcx** [comment]
Thanks for pointing this out, squashed.
