### ISSUE TITLE
Support for CORS headers in JSON endpoints

### ISSUE THREAD

**Issue by ekzhang** [lobsters/lobsters#1029]
Hi, thanks for this wonderful open source website! I was hoping to use the JSON endpoints at

```
https://lobste.rs/hottest.json
https://lobste.rs/newest.json
https://lobste.rs/s/<submission_id>.json
```

as a way to provide some real-world data for a teaching app to help illustrate frontend web development concepts by building a clone of the Lobsters frontend. However, these pages don't have CORS enabled, which makes this difficult to do in a live tutorial setting. Would you be open to enabling CORS on these endpoints, by setting the `Access-Control-Allow-Origin: *` and other appropriate headers?

I really appreciate your time, and I would be happy to try to write a PR for this if you think it's a good idea.

**Comment by ekzhang** [comment]
Also, this project isn't related to me, but I found this discussion after a Google search for "Lobsters CORS" - https://github.com/karakanb/devo/issues/52

**Comment by Zhomart** [comment]
Similar discussion on newsit - a chrome/firefox addon that checks if the link was submitted - https://github.com/benwinding/newsit/issues/12.

The addons are not super popular. Not sure how much pressure the CORS will add to the lobsters server.

**Comment by pushcx** [comment]
As benwinding observes in that linked ticket, Lobsters doesn't have a public REST API. The endpoints the site does exist to support our little bit of javascript (or happened to come free with Rails resources). I don't mind people using them, but I don't want to imply they're an official feature, take support requests for them, or take unknowable external users into account when editing them for the site's needs.

If you want your students to pull data from the site via in-browser scripts, it sounds like the best approach is referred to in benwinding's comment: set up a service of your own to proxy to the site (with caching, please). That not only gives you a clear tool to deal with any changes we make that would break your students, as a bonus you can freely edit the API to suit your pedagogical needs.
