### ISSUE TITLE
Visited links do not get visited link color

### ISSUE THREAD

**Issue by kconner** [lobsters/lobsters#1030]
As pointed out in [this comment](https://lobste.rs/s/eg1n75/dark_mode#c_xn3bzf), visited links are not shown in a distinct color after the merge of #1026. This appears to be the case in both light and dark modes.

**Comment by phase** [comment]
https://github.com/lobsters/lobsters/blob/17cccc47e79e8aca3bc0a357225c85f399e38be4/app/assets/stylesheets/application.css#L169

The alpha here doesn't seem to be changing the appearance of the color at all. It would probably be better to manually specify the dark blue / purple.
