### ISSUE TITLE
Write helper for username colors

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#1032]
Each place a username appears in a templates, it reimplements username coloring. This of course leads to inconsistencies - many places don't check `is_active?` for inactive users, and probably some places usernames appear are missing coloring altogether. Let's audit `app/views` and write a reusable helper to link + set classes on usernames to avoid these inconsistencies.

**Comment by pushcx** [comment]
Also, this should take an optional context timestamp (default to `Time.current`), so stories/comments can show that a user was new at the time of submission rather than the time a visitor happens to load a page.

**Comment by hernanat** [comment]
gotchu

**Comment by hernanat** [comment]
> Also, this should take an optional context timestamp (default to `Time.current`), so stories/comments can show that a user was new at the time of submission rather than the time a visitor happens to load a page.

not sure we need the timestamp -- we can check to see if the story's created date is within `NEW_USER_DAYS` of the user's created date, right?

**Comment by pushcx** [comment]
That feels like it might be a recipe for 1 + n queries, but maybe the association's already going to be preloaded or there'd already be a 1 + n on the page.

There's a `User#is_new?` with this same logic. Maybe the name of this function wants to be something like `User#was_new?(at=story_or_comment)`.

**Comment by hernanat** [comment]
> That feels like it might be a recipe for 1 + n queries, but maybe the association's already going to be preloaded or there'd already be a 1 + n on the page.

I made some assumptions based on what was already there, but I see your point. I can double check and see.
 
> There's a `User#is_new?` with this same logic. Maybe the name of this function wants to be something like `User#was_new?(at=story_or_comment)`.

I like this idea a lot, will add it in!

**Comment by pushcx** [comment]
Done in 9fff6ae and dd4dfbc
