### ISSUE TITLE
Mobile CSS displays site with horizontal scrolling in a phone-size window

### ISSUE THREAD

**Issue by kconner** [lobsters/lobsters#1058]
Observed on an iPhone 12 mini in Safari. The site is about 150% the width of my screen today, and by default it will scroll to the side. Expected/familiar behavior has been to scroll only vertically by fitting page content to device width. 

From a glance at history, I think fd571d7 may be the cause: That change removed default and mobile override width styles from a wrapper element. It added the default width style to the body element, but did not also add the mobile override style to the body element. 

![6A19F5F2-3AC9-4758-9811-48C1C9A588FA](https://user-images.githubusercontent.com/602569/151687513-bf31ff87-59e8-43a5-b804-9eb5813b5cf8.png)

**Comment by viraptor** [comment]
Confirming same on Android / mobile Firefox.
![Screenshot_20220130-230911](https://user-images.githubusercontent.com/188063/151699121-07481e31-062b-4335-a22b-c975896ef776.jpg)

**Comment by luisbelloch** [comment]
Same on iPhone 13 Pro Max with 15.2.1

![image](https://user-images.githubusercontent.com/160260/151702758-3052b03d-5e99-4869-a74f-a3a514724937.jpeg)

**Comment by pushcx** [comment]
Thanks for reporting this. Yep, I broke it last night in fd571d785375573ec164e40ff266ce38fae7f889 as I did a bit of housekeeping in front of #580. Fixed in cc0532b9b47d83d6937bfe3134d174de9b03344a.

**Comment by pushcx** [comment]
@kconner I can't sucker you into doing #580 can I? I know youuuuuu like page layout. It's a nice big project to sort out years of inconsistencies with highly visible results, right up your alley. What i

**Comment by kconner** [comment]
I do like to untie a big knot, but I'm currently in a position to discard projects, not start more. :)

**Comment by pushcx** [comment]
dang :)
