### ISSUE TITLE
Comment flag reasons appear in weird places.

### ISSUE THREAD

**Issue by AbstractBeliefs** [lobsters/lobsters#1062]
When trying to flag a comment, the flag reason drop down appears not tied to the flag link, but instead to a fixed position from the screen chrome and remains fixed in position, floating when scrolling.

![An example trying to flag Janus](https://paste.pulham.info/2022-02-20-032513_1338x682_scrot.png)

**Comment by pushcx** [comment]
Most likely I broke this in 22907172fb875187faf9ee41acec10a4ad530051 trying to be clever with the checkbox hack.
