### ISSUE TITLE
Scrolling mobile nav is too thin to scroll easily with your finger

### ISSUE THREAD

**Issue by kconner** [lobsters/lobsters#1066]
I keep trying to scroll the top nav with my finger and missing.

![image](https://user-images.githubusercontent.com/602569/156887062-2023b2b3-3a6e-41d8-b79a-4c7a4462b0c3.jpeg)

For guidance, the iOS HIG suggests making tap targets 44px tall and wide at a minimum. In the browser, textual links are generally not that tall, but the browser itself leaves some tappable cushion around them. Software keyboard keys are also not that wide, but depending on what you've just typed, the keys that normally come next in your language will have wider tap targets for a moment. These adjustments aren't visible, they just make it all work better for fingertips. 

Check out the scrolling repo tabs here on GitHub for example. Our fingers are used to hitting that size, and I don't have trouble scrolling these tabs.

![image](https://user-images.githubusercontent.com/602569/156887069-7c1a70ba-5200-4826-8629-90c9f4470d1e.jpeg)

I suggest we add some cushion into the scrollable element of the nav, not changing the text size but padding the top and bottom to a total height of 44px. I think we could satisfy that without sacrificing the svelte, borderless aesthetic Lobsters enjoys. 

(I would have preferred to join the bikeshed session but was traveling and completely tuned out.)

**Comment by pushcx** [comment]
Sounds like a bug worth fixing. I don't spend much time on mobile, so it's easy for me to miss these things. Thanks for the clear report.

**Comment by pushcx** [comment]
Fixed in 3455412707b92f2c61f717581883ea8f3ffbe2e8
