### ISSUE TITLE
RSS Feeds Broken

### ISSUE THREAD

**Issue by avitex** [lobsters/lobsters#1070]
Looks like RSS feeds seem to be broken.

Example: https://lobste.rs/t/rust.rss

<img width="453" alt="image" src="https://user-images.githubusercontent.com/5110816/159148970-a4e6cb4c-c8e4-4c23-be83-866c469fd728.png">

**Comment by pushcx** [comment]
Most likely the routing change in 03480e47 but I haven't been able to look at this yet.

**Comment by pushcx** [comment]
Thanks for the report. That was indeed it, the Rails router was parsing the `.rss` as part of the tag name rather than as the `:format`. The fix is deployed now.

**Comment by avitex** [comment]
Thanks mate! :)
