### ISSUE TITLE
Domain: fold tracker bans into regular bans, add UI

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#1080]
For a long time, the site has had code banning link shorteners like `t.co` and `bit.ly` to avoid duplicate submissions and inconvenience marketers who are trying to get good [metrics](https://github.com/lobsters/lobsters/commit/e2ea9decb21de6d375148168e0aa8aeb31be1cdf) on their spam. When we [broke out the `Domain` model](https://github.com/lobsters/lobsters/commit/f718da18205ae9fcabe45903677572651274b6fe) that static list of banned domains became the `is_tracker` attribute on the `Domain` model. This functionality was made redundant by domain [banning](https://github.com/lobsters/lobsters/commit/630ace42f80af5dcd1cb5b7609629cc4c8dd4291), which also has the proper hooks in place to show up in the mod log. As unobjectionable as blocking tracking domains is, I don't like that `is_tracker` isn't visible in the source or UI anywhere.

The two features here are:

1. A migration to remove the `is_tracker` attribute. All the tracker domains should get set as banned with the reason "Used for link shortening and ad tracking." I know there's the `banned_at` timestamp; it's not worth your time to spelunk git history to find a correct timestamp and author for these from the the old `Story.TRACKING_DOMAINS`, you can just call `ban_by_user_for_reason!(User.find_by!(username: 'pushcx', ...`
2. UI for the admin (not mods) to ban domains. We'll need a `DomainsController` with `edit`/`update` actions; look to `TagsController` for most of the setup. (And, yep, domain banning has been rare enough that I've been doing it in the prod rails console.)

**Comment by fatshinobi** [comment]
May I fulfill this task?

**Comment by pushcx** [comment]
Please do! Happy to talk through any of this here or [on IRC](https://lobste.rs/chat).

**Comment by pushcx** [comment]
This should've been closed with #1119, whoops.
