### ISSUE TITLE
Issue with assets after upgrading "No route matches"

### ISSUE THREAD

**Issue by consolewitch** [lobsters/lobsters#1085]
Good afternoon,

I'm a Kubernetes enthusiast and I'm trying to build some easy-to-use Kubernetes manifests that can stand up a lobsters instance. My current experiment works on Digital Ocean but I intend to expand to AWS and GCP.

Alas, I am not a rails programmer so I'm having trouble troubleshooting something that I suspect to be a fairly simple problem. I recently upgraded from a build created last November 2021 to a build from April 2022. The result is that my site no longer finds the CSS.

When I hit the front page, the following is spat out in the lobsters log:
```
I, [2022-04-30T19:13:51.636884 #36]  INFO -- : Started GET "/" for 172.58.16.202 at 2022-04-30 19:13:51 +0000
I, [2022-04-30T19:13:51.640489 #36]  INFO -- : Processing by HomeController#index as HTML
I, [2022-04-30T19:13:51.640782 #36]  INFO -- :   Parameters: {"protocol"=>"http://"}
I, [2022-04-30T19:13:51.642614 #36]  INFO -- :   Request 172.58.16.202 GET / user: 0 nobody
I, [2022-04-30T19:13:51.652360 #36]  INFO -- :   Rendered home/index.html.erb within layouts/application (Duration: 5.5ms | Allocations: 2112)
I, [2022-04-30T19:13:51.654777 #36]  INFO -- :   Rendered layout layouts/application.html.erb (Duration: 7.9ms | Allocations: 2674)
I, [2022-04-30T19:13:51.656234 #36]  INFO -- : Completed 200 OK in 14ms (Views: 9.5ms | ActiveRecord: 0.4ms | Allocations: 4122)
X-Accel-Mapping header missing
I, [2022-04-30T19:13:51.746164 #36]  INFO -- : Started GET "/stylesheets/application.css" for 172.58.16.202 at 2022-04-30 19:13:51 +0000
F, [2022-04-30T19:13:51.749831 #36] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/stylesheets/application.css"):

I, [2022-04-30T19:13:51.751568 #36]  INFO -- : Processing by AboutController#four_oh_four as CSS
I, [2022-04-30T19:13:51.752458 #36]  INFO -- :   Request 172.58.16.202 GET /404 user: 0 nobody
I, [2022-04-30T19:13:51.755404 #36]  INFO -- :   Rendered html template (Duration: 0.1ms | Allocations: 13)
I, [2022-04-30T19:13:51.756603 #36]  INFO -- : Completed 404 Not Found in 4ms (Views: 1.4ms | ActiveRecord: 0.4ms | Allocations: 551)
```

I've learned that ruby uses an asset management tool that translates the assets directory into a minimized cache. I suspect that process is the source of my problem but I've tried several things I've found in the documentation (https://edgeguides.rubyonrails.org/asset_pipeline.html#precompiling-assets) to no avail. I could really use a pair who can look over what I've built for kubernetes and help me understand what I'm missing.

FWIW, I think this PR is what broke things https://github.com/lobsters/lobsters/pull/1040 but I could easily be wrong.

Thanks and if this is the wrong place to post this please advise.

**Comment by pushcx** [comment]
Run `rails assets:precompile` to create the file, then `ls -lt public/assets/` to see the file exists. It should be named `application-[hash].css`. You'll need to re-run that command after you pull code changes.

The way your log says the browser is looking for `application.css` rather than `application-[hash].css` makes me think you've started the server in development mode, see here for starting in production mode: https://guides.rubyonrails.org/v6.0/configuring.html#rails-environment-settings

Finally, I'd check that you can `curl http://localhost/stylesheets/application-[hash].css`. You may not have your webserver configured to serve them. Here's our nginx conf for it: https://github.com/lobsters/lobsters-ansible/blob/master/roles/nginx/files/production/nginx/sites-available/lobste.rs#L76-L81

**Comment by consolewitch** [comment]
I have tried running `rails assets:precompile` to no avail. I did just discover a way to reproduce the problem though. If you pull down the docker-lobsters repo and run `docker-compose up` you will get a working copy of lobsters. If you then shut down docker-compose and change a single environment variable in the lobsters container from `RAILS_ENV=development` to `RAILS_ENV=production` you will get the exact same error I'm seeing. 

I discovered that there is an environment variable `RAILS_SERVE_STATIC_FILES` which tells puma to serve static files. This feels very close to the solution to my problem. Kubernetes runs everything in containers so there is no way for the ingress object (which is the web server) to  serve static pages in the same way as the nginx config linked to above.

Setting the `RAILS_ENV` to production and the `RAILS_SERVE_STATIC_FILES` to true feels right since that should allow puma to serve the static files but i'm still getting the same error.  I'm continuing to investigate.

Any further thoughts would be very welcome. I will update this thread as I learn more.

**Comment by consolewitch** [comment]
Solved! What was happening was a problem with the production.rb file that is deployed as part of the docker-lobsters repo. `config.assets.js_compressor = :uglifier` needed to be replaced with `config.assets.js_compressor = Uglifier.new(harmony: true)` 

this bug can be closed. I'll open a PR against that repo.

**Comment by pushcx** [comment]
I'm glad you're set. I don't know what your end goal is, but I'm always curious to see what people do with the codebase, so please drop me a line when you reach a good point with your project.
