### ISSUE TITLE
Fix endpoint inconsistently using json

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#1106]
#1100 highlighted that `StoriesController#check_url_dupe` uses json when none of our other endpoints do. Let's unify this to work off POST body like all the others. Maybe this should be part of #554 if you're interested, @ymeynot45?

**Comment by saksham-jain** [comment]
If this issue is not picked up, can I pick it up and fix?

**Comment by saksham-jain** [comment]
@pushcx what should be the format of the response. Should it be plain or JSON?

**Comment by pushcx** [comment]
It looks like we don't even use the json? `application.js.erb` has the only reference and it only uses the html version. I'm puzzled why this even exists.

Searching history, looks like it was [my bright idea](https://github.com/lobsters/lobsters/pull/555#issuecomment-430623801). I'll add a comment for when I've forgotten about this in another few years. Sorry to waste your time.
