### ISSUE TITLE
Comments Not Rendering on Mobile Safari

### ISSUE THREAD

**Issue by landongrindheim** [lobsters/lobsters#1109]
I've noticed recently that comments will not render when I visit a comment thread on Lobsters.

OS: iOS 15.5
Browser: Safari
Other details: viewed in dark mode

![image](https://user-images.githubusercontent.com/5278382/178853047-d1e6964e-9b6f-4ad2-8d72-41240119a1db.png)

I've used the inverted colors setting to check if it was a dark font on a dark background. Comments still did not render.

**Comment by pushcx** [comment]
I can't reproduce this. Do you maybe have an ad blocker of some kind? Or a plugin to filter out youtube comments that might be overbroad?

**Comment by landongrindheim** [comment]
> I can't reproduce this. Do you maybe have an ad blocker of some kind? Or a plugin to filter out youtube comments that might be overbroad?

🤦‍♂️ I do. Just disabled a couple settings and comments now render. It's an error on my end. Sorry about that!

---

When using the same ad-blocking configuration that prevented Lobsters' comments from rendering, I'm still able to see comments on HN. Do you know what the difference is? No need to spend more energy on this, but if you know I'm curious 🙂

**Comment by jcf** [comment]
I’ve encountered this and can trace it back to the optional "Block comments" rules in 1Blocker.

![IMG_1352](https://github.com/lobsters/lobsters/assets/18374/b140db7c-93b0-4ad2-9c14-f3af02a726c4)

Given that comments are the primary focus of this page, I think the description is misleading.
