### ISSUE TITLE
Message on hat approvals

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#1110]
There's a moderator page for approving hat requests at https://lobste.rs/hats/requests

It has a text box for sending a message on rejecting hat requests, but it would also be really convenient to send a message on approval, too. (Lately, that's me apologizing for the delay in approvals.)

For UI, just have one text box and an approve or reject button. Please style the "reject" button red, like the "Ban" button admins see on user profiles.

As long as you're on the form, please also display the hat request `created_at` using `time_ago_in_words`. It doesn't need its own line, just put it to the right of the username.

**Comment by ymeynot45** [comment]
Ok, I'll start that monday after untangling the vote function.

**Comment by saksham-jain** [comment]
Can I take it and work on this if this is not picked up yet?

**Comment by pushcx** [comment]
Yes - I talked with @ymeynot45 offline and he's going to pass on this issue as it's all Ruby and he's doing javascript.

**Comment by ymeynot45** [comment]
Cool, thanks!
It is always nice to distribute the work. Sorry, I didn't get back to you
sooner.

**Comment by saksham-jain** [comment]
@pushcx Is this fine?
<img width="1440" alt="Screenshot 2022-07-19 at 11 56 04 AM" src="https://user-images.githubusercontent.com/27828987/179680691-442675dd-347e-4868-bd34-16d81cee2e08.png">

**Comment by saksham-jain** [comment]
@pushcx created PR #1111 for this issue. Kindly check once and let me know if any changes are required.

**Comment by pushcx** [comment]
Closing, @saksham-jain completed this in #1111
