### ISSUE TITLE
Status 500 on /recent.json

### ISSUE THREAD

**Issue by ranfdev** [lobsters/lobsters#1114]
Url: https://lobste.rs/recent.json.

A 500 status is unexpected, because
`/hottest.json` correctly returns json data, status 200.
`/recent.jsoaasjh` (a non existent route) correctly returns status 404

**Comment by pushcx** [comment]
However, `/recent.yaml` also fails with a 500. I can't guess why Rails does this, but it seems to assume that actions should respond to all its known mime types. They don't, and don't have a `respond_to` block claiming they do, but Rails is so sure they must that it throws `ActionView::MissingTemplate` with message `Missing template home/index, application/index with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby]}.`.

I wonder if this is a bug in Rails. Nothing in our config, routes, controller, or action says the format is supported.

**Comment by 6ixdog** [comment]
> This is the root cause of #746

Add real profit in crypto wallet for all crypto app

**Comment by pushcx** [comment]
Fixed in 98a5901.
