### ISSUE TITLE
Hidden stories still appear in the "active" tab

### ISSUE THREAD

**Issue by hwayne** [lobsters/lobsters#1133]
![image](https://user-images.githubusercontent.com/2660212/197880295-1c133a90-1392-4704-8c98-b4dbee75ea75.png)

**Comment by pushcx** [comment]
Must be calling the wrong scope - whoever picks this up, compare against the `newest` and `hottest` actions in `HomeController` to figure out what's missing. If it's not missing from the controller action, it's missing from `StoryRepository`.

**Comment by MiguelArgentina** [comment]
I think a filter is missing in `app/models/story_repository.rb#active`.
Adding `.where.not(id: Story.hidden_by(@user).pluck(:id))`  filters hidden stories.
The method would look like:
```
  def active
    Story.base(@user)
      .where.not(id: Story.hidden_by(@user).pluck(:id))
      .filter_tags(@params[:exclude_tags] || [])
      .select('stories.*, (
        select max(comments.id)
        from comments
        where comments.story_id = stories.id
      ) as latest_comment_id')
      .where('created_at >= ?', 3.days.ago)
      .order('latest_comment_id desc')
  end
```
