### ISSUE TITLE
Tag autocomplete dropdown menu missing on Suggest Story Changes

### ISSUE THREAD

**Issue by talklittle** [lobsters/lobsters#1135]
Tag autocomplete still works on Submit page, but missing the dropdown menu on Suggest.

Desktop Firefox and Chromium

**Comment by pushcx** [comment]
ping @ymeynot45 

There's also some layout issues with the story submit form + story suggestion form. I fixed some of them in 7242071b409683353b1f82d0d5804e6e77ff5562 and 3d38acd99e1aafe15b217d5220df72cd7c939fdf.

**Comment by RaymiiOrg** [comment]
This affects mobile Firefox on Android as well. I can type a suggestion, which is light grey on a white field but it seems it's not applied when submitting.
