### ISSUE TITLE
Log out button broken?

### ISSUE THREAD

**Issue by alilleybrinker** [lobsters/lobsters#1136]
The logout link from the profile page appears to be (at least for me) broken, returning a 404 and leaving me logged in. Clearing the cookie manually obviously works, but I’d prefer to be able to use the link.

**Comment by pushcx** [comment]
What's happening here: we removed jQuery, which removed the rails-ujs tooling that would decorate certain links with POST forms.

This is the top of my to-do list.

**Comment by Vaelatern** [comment]
htmx! Been using it at work and it has been a joy

https://htmx.org/attributes/hx-post/

Probably need a https://htmx.org/attributes/hx-target set depending on what the logout link returns

**Comment by pushcx** [comment]
Fixed in 2c68883. This one got real fiddly, fingers crossed.
