### ISSUE TITLE
Gravatar `Expire cache` button is broken

### ISSUE THREAD

**Issue by nikitavoloboev** [lobsters/lobsters#1137]
In [settings](https://lobste.rs/settings):

<img width="970" alt="image" src="https://user-images.githubusercontent.com/6391776/199752687-d889548c-058f-4de6-86f5-d33b7927f8b7.png">

Expire cache button is broken. If you click it, it goes to https://lobste.rs/avatars/expire page and says:

<img width="658" alt="image" src="https://user-images.githubusercontent.com/6391776/199752783-e97672a3-8a0a-4324-8c31-e288f31599de.png">

I updated my Gravatar icon and want to force a change but can't do it now.

**Comment by pushcx** [comment]
Thanks for reporting this. It has the same cause as #1136, so I'm going to close in favor of that one.
