### ISSUE TITLE
Light/dark theme settings don't work

### ISSUE THREAD

**Issue by slater** [lobsters/lobsters#1142]
I tried setting my theme setting to dark, but even after clicking "save settings" the setting doesn't stick.

macOS 12.5, Firefox 106.0.5

**Comment by pushcx** [comment]
When you set it to dark, what classes do you see on the `<html>` tag? Is there one starting `color-scheme-`?

**Comment by slater** [comment]
I think it's more because the settings page has a form tag within a form tag?

**Comment by vito** [comment]
Yeah, seems like the HTML for the form itself is busted. If I inspect element and drag the inputs and submit button into the previous `<form>` and submit everything is OK.

**Comment by pushcx** [comment]
Thanks for reporting this bug, I've deployed a fix for it.
