### ISSUE TITLE
suggesting tags on existing stories seems broken

### ISSUE THREAD

**Issue by fs111** [lobsters/lobsters#1146]
When trying to suggest tags on an existing story one would typically get the suggestions presented and then one could add the tags. That no longer works. I tried on mobile chrome and desktop firefox. No suggestion box appears so the feature is effectively broken for me.

**Comment by talklittle** [comment]
#1135 - was fixed but apparently not yet deployed to production.

**Comment by talklittle** [comment]
The fix in #1145 was deployed to production, so this issue is resolved. (Duplicate of #1135)

**Comment by pushcx** [comment]
Thanks for helping connect the related issues and catch that this was ready to close.
