### ISSUE TITLE
Save All Settings button does nothing

### ISSUE THREAD

**Issue by lorthirk** [lobsters/lobsters#1152]
I'm trying to change of my settings profile (specifically, I want to change `Receive List E-mails:` from `No e-mails` to `Only stories`). When I click the `Save All Settings` button, simply nothing happens: no page refresh, nothing in the console, and if I manually refresh the page the change is not saved. Also other settings (`Show Story Previews`, `Show User Avatars`, `Color Scheme`) are not saved. I tried with Chrome Mobile on Android, Chrome Desktop on macOS and Firefox on macOS.

**Comment by lorthirk** [comment]
This seems to be related to #1142

**Comment by pushcx** [comment]
Thanks for reporting this bug, I've deployed a fix for it in 9ec9610a
