### ISSUE TITLE
could the dark colour scheme be made readable?

### ISSUE THREAD

**Issue by SS64** [lobsters/lobsters#1154]
Related to log: Light/dark theme settings don't work #1142 

While we are stuck with a dark scheme, could it be made something more readable than black on black
The way it is right now the site is unusable

**Comment by pushcx** [comment]
It's defaulting to the color scheme your browser requests.

Closing as this is not an actionable issue - without a screenshot or PR you just seem to be griping about not getting to paint the bikeshed, which is not helpful.
