### ISSUE TITLE
Enable mailing lists feature seems to be broken

### ISSUE THREAD

**Issue by niko2342** [lobsters/lobsters#1158]
I'm trying to enable the mailing list feature by setting "Receive List E-mails" to "Only stories", but it's not possible to submit the form ("Save all Settings"). Tested on Chrome and Firefox.

**Comment by jmiven** [comment]
Yes, #1142 and the other referenced issues are caused by the same bug.

**Comment by pushcx** [comment]
I'm deploying the fix for this now in 9ec9610a

**Comment by niko2342** [comment]
Now, it works as expected. Thank you!
