### ISSUE TITLE
Replace Twitter bot with Fediverse bot

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#1159]
https://twitter.com/twitterdev/status/1621026986784337922

Related to #1141, on Feb 9, Twitter will close the API our bot uses to post stories there. (See `extras/twitter.rb`.) The short notice window makes this unusually urgent.

In #499 we've talked about integrating ActivityPub fairly deeply into the site, but rather than let perfect be the enemy of good, this issue is narrowly scoped to having an official bot posting links that people can follow. (IIRC there's one or two unofficial bots - I don't know who's running them or what feed they're using.)

**Comment by ngoldbaum** [comment]
Someone already set up a lobste.rs bot on mastodon: https://botsin.space/@lobsters

**Comment by pushcx** [comment]
Done, more detail in #1175.
