### ISSUE TITLE
Text of Fetch Title button on Submit Story page reads "Fetch&nbsp;Title"

### ISSUE THREAD

**Issue by nortti0** [lobsters/lobsters#1163]
In the source it is `<button name="button" type="button" id="story_fetch_title">Fetch&amp;nbsp;Title</button>` so this seems to be a case where an HTML entity is being used in a non-HTML input to the template.

**Comment by jmillikin** [comment]
I believe PR https://github.com/lobsters/lobsters/pull/1162 is related (cc @ymeynot45)

**Comment by fs111** [comment]
I see the same on Firefox Nightly - Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/112.0
