### ISSUE TITLE
API rate limiting is too aggressive

### ISSUE THREAD

**Issue by 4cq2** [lobsters/lobsters#1167]
Making requests like this:

https://lobste.rs/u/Dunkhan.json

even making only one per second, I hit the rate limiter in less than 10 requests:

~~~
< HTTP/2 500
< server: nginx
< date: Fri, 17 Mar 2023 23:04:03 GMT
< content-type: text/html; charset=UTF-8
< content-length: 0
< x-request-id: 125836ce-45e4-4be5-bfd7-ab05ce72288d
< x-runtime: 0.007081
< strict-transport-security: max-age=63072000; includeSubDomains
<
~~~

further, as can be seen above, the server is providing essentially no communication to the end user what has happened. No rate limit header, empty response body. plus the error should be 429:

https://developer.mozilla.org/docs/Web/HTTP/Status/429

and some feedback should be given as to what the rate limit is, example:

~~~
curl -v https://api.github.com/search/issues?q=hello
< HTTP/2 200
< x-ratelimit-limit: 10
< x-ratelimit-remaining: 6
< x-ratelimit-reset: 1679094697
< x-ratelimit-resource: search
< x-ratelimit-used: 4
~~~

**Comment by pushcx** [comment]
I'm not taking a feature request from someone I've already had to repeatedly ban for sockpuppeting.
