### ISSUE TITLE
Detect duplicate YouTube URLs

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#1171]
YouTube URLs usually look like `https://www.youtube.com/watch?v=[id]` but they have a shortener that looks like `https://youtu.be/[id]`. Probably there are more.

We do already special-case youtube links to add the `video` tag. It'd be worth adding this domain to that as well.

Similar to #1165

**Comment by Matrix89** [comment]
> We do already special-case youtube links to add the video tag. It'd be worth adding this domain to that as well.

Seems `youtu.be` and `*.youtube.com` seems to already be handled by

https://github.com/lobsters/lobsters/blob/64ba31c4d0e731d27e37098fe56e2c81edc849f3/app/assets/javascripts/application.js.erb#L559
