### ISSUE TITLE
my “notification sense” keeps getting triggered by the “T” in “Threads”

### ISSUE THREAD

**Issue by biox** [lobsters/lobsters#1176]
when i use lobste.rs while logged in via safari on ios, the “T” in “Threads” is cut off slightly, and looks almost indistinguishable from a “1” - which is normally used to indicate notifications. my “i have a notification” sense gets randomly triggered by this quirk.

i know very little about css or i'd offer a solution - i’m hoping to flag this so that someone else might help!

**Comment by biox** [comment]
here's an image - look at the top right to see what i mean

![image](https://github.com/lobsters/lobsters/assets/11777705/32783187-61ba-464d-bd12-6da70e33e89d)

**Comment by pushcx** [comment]
Does anyone else have this problem?

It doesn’t feel much like a common problem, and I’m not sure there’s a fix available in any case. The T isn’t red like when there are notifications, and it’s useful to have a word fading out to hint at the uncommon interaction of horizontally scrolling the nav bar.

**Comment by NattyNarwhal** [comment]
I think this case mainly shows up on the mini iPhones. I initially saw it as a one, then I got used to it being like that until it becomes red for unread.

**Comment by biox** [comment]
> The T isn’t red like when there are notifications

i realized that people will eventually get used to this - but for me, it took 2-3 false "oh shit i have a notif!" to understand what was happening. a number next to an envelope means "notification" to me, regardless of color.

idk, it's not a huge deal, just a little UX nicety.

**Comment by pushcx** [comment]
I also use a mini iPhone and see this, but my opinion here is pretty useless because I designed the thing. :) 

Let's leave this open a few months and see if there's more support or, ideally, a suggestion to improve the design in a way that both hints at the interaction and doesn't distract.

**Comment by MatheusRich** [comment]
It's been a year. Should we close this?

**Comment by pushcx** [comment]
Yeah, a year without activity means there isn't much interest or options. Thanks for highlighting it.
