### ISSUE TITLE
TOTP QR Code fails to scan when the site is in dark theme

### ISSUE THREAD

**Issue by sharunkumar** [lobsters/lobsters#1178]
I tried scanning it with:
- 1Password Desktop App
- Authy Mobile App (Android)
- Local QRScanner Tool which I got from npm

In all 3 cases, the TOTP failed to get scanned when the site was in dark theme.

After I switched to light theme, it worked on 1Password

**Comment by reinerh** [comment]
Same here. It's because the QR code is missing the white border around it. Without it, it's not actually a valid QR code.

**Comment by pushcx** [comment]
@sharunkumar Thanks for reporting this with clear details for repro.

@reinerh Thanks for solving thins. I added a border in ea0c542 and confirmed my phone can scan the QR code in dark mode.

If anyone still can't scan the QR code, please send a screenshot. The code is only good in your browser session (and only for 15 minutes) so it's OK to share a code **that you don't complete enrollment with**.
