### ISSUE TITLE
warn about capslock on password input

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#1180]
https://defensivecss.dev/articles/intro-defensive-css/

**Comment by mahadmughal** [comment]
Hey @pushcx , are you working on it. If not then can I help in this ?

**Comment by pushcx** [comment]
I posted this because it seemed like a nice idea, I don't have any concrete plans to do it myself. I put the `good first issue` tag on anything that would be easy for someone else to pick up.

**Comment by Br0k3nh4nd012** [comment]
@pushcx Based on the title I can understand that we need to add a text denoting the caps lock status in the password input field on the login page.
I am ready with the code changes. I am creating a [PR](https://github.com/lobsters/lobsters/pull/1183) for the same.
Can you please take a look at it?

**Comment by Br0k3nh4nd012** [comment]
@pushcx Any updates on this?

**Comment by Br0k3nh4nd012** [comment]
@pushcx Anything?

**Comment by pushcx** [comment]
I don't know why I thought this was possible with CSS, but it doesn't seem to be. I definitely didn't paste a relevant link.
