### ISSUE TITLE
Number of items-per-page preference

### ISSUE THREAD

**Issue by gingerbeardman** [lobsters/lobsters#1188]
I'd love to have the option to specify the number of items-per-page, which would allow me to fit a single page of items in my chosen window size, so I don't have to scroll.

Alternatively, I'd also be happy with infinite scroll. 

I don't mind scrolling, or paging, but I'd rather not have to do both - simply to save time/effort.

> ps: I cannot post to `meta` and had no response on IRC, so I'm filing requests here. Thanks!

**Comment by pushcx** [comment]
`Please discuss feature requests in the chat room or a meta thread before posting.`

**Comment by gingerbeardman** [comment]
One more question: at what point does a user stop being considered "new"? A certain amount of days/weeks/posts/rating?

Thanks

**Comment by pushcx** [comment]
https://lobste.rs/about#new-user-tags

It's linked from the error message you saw when you tried to post meta stories.
