### ISSUE TITLE
More complete PWA support

### ISSUE THREAD

**Issue by gingerbeardman** [lobsters/lobsters#1189]
Currently there is partial PWA (portable web app) support in that Lobsters can be added as an icon to the home screen and the icon and title are picked up during this process.

I'd love it if this could be expanded to provide a manifest with extra details which would let the web shortcut act like an app with its own window (rather than opening in the default browser as it does now).

- https://app-manifest.firebaseapp.com
- https://web.dev/learn/pwa/windows/

I'd be happy help implement this if help was needed.

> ps: I cannot post to `meta` and had no response on IRC, so I'm filing requests here. Thanks!

**Comment by pushcx** [comment]
`Please discuss feature requests in the chat room or a meta thread before posting.`

**Comment by gingerbeardman** [comment]
@pushcx as mentioned I am unable to post to meta and received no response in IRC. If you could explain those two things, I would appreciate it so I can do things by the book in future.

**Comment by pushcx** [comment]
Correct, there are two routes for feature requests and one of them isn't open to new users.
