### ISSUE TITLE
Upvote Numbers are missing and replaced by `~`

### ISSUE THREAD

**Issue by norpol** [lobsters/lobsters#1201]
Just noticed all upvote numbers are gone and it instead shows `~`.
![Screenshot of lobste.rs showing today's postings with a `~` instead of numbers.](https://github.com/lobsters/lobsters/assets/2230917/7090a723-7b67-44be-82ea-38f4774e24d7)

**Comment by pushcx** [comment]
Fixed in a04e70a0.

Thanks for the prompt report!

**Comment by norpol** [comment]
Thanks for your work! It's indeed resolved now
