### ISSUE TITLE
Add profile toggle value to optionally show your e-mail address to authenticated users

### ISSUE THREAD

**Issue by epilys** [lobsters/lobsters#1207]
Since publicly showing addresses is bad because spam, anyone who wants to share it safely can do so by only showing it to authenticated users. Who I assume are (mostly) humans.

**Comment by chahmedejaz** [comment]
Hey @pushcx - I'd love to work on this feature, can you please assign it to me? Thanks. :)

**Comment by joancodes** [comment]
Hello @epilys , could you please point out any location within the interface where email addresses are visible or displayed?

**Comment by epilys** [comment]
@joancodes they are not currently visible. This issue is about making it visible in the public user profile but only if the user has enabled it. I have never read this codebase before nor have I written Ruby. My guess is you'd have to change the public user profile and the user options data and interface.

**Comment by pushcx** [comment]
They are visible on the user profile (`app/views/users/show.html.erb`) but only to admins. I think to implement this ticket, that display should move higher on the page, into the table of profile information right before Homepage.

**Comment by pushcx** [comment]
Merged in #1218
