### ISSUE TITLE
comment search pagination buttons all point to current page

### ISSUE THREAD

**Issue by NattyNarwhal** [lobsters/lobsters#1208]
If I hover over any of the page buttons on a comment search when I do a search:

![Screenshot 2023-09-22 at 11 24 35 PM](https://github.com/lobsters/lobsters/assets/3161292/f266fd3c-e302-4b24-96ca-9553e5764f2f)

Manually changing the query string works, and changes all the page buttons to point to that current page instead.

**Comment by chahmedejaz** [comment]
Hey @pushcx - I'd love to fix this, can you please assign it to me? Thanks. :)

**Comment by pushcx** [comment]
You can just take it on, I only use assigning when I want to take something because I can’t get all my notes into an issue.

**Comment by chahmedejaz** [comment]
Sure, @pushcx, no problem. I'll submit the fix soon. Thanks :)

**Comment by pushcx** [comment]
@sin-ack I admit I only took a quick read of your PR before I deployed it, but it looked good. Could you take another look now that the bug is re-reported in #1211?

**Comment by JuanVqz** [comment]
Is this fixed by https://github.com/lobsters/lobsters/pull/1210? can we close it?

**Comment by cac04** [comment]
> Is this fixed by #1210? can we close it?

Is #1210 deployed? If so, then it didn't fix it.

Right now, you can see the broken behavior here: https://lobste.rs/search?q=pagination&what=stories&order=newest

**Comment by JuanVqz** [comment]
I'll have a look @cac04

**Comment by pushcx** [comment]
Yes, 1210 was deployed before this issue was opened.

**Comment by JuanVqz** [comment]
@pushcx and @cac04 just to let you know I fixed the issue, I wish to have more context to add tests on it.

**Comment by pushcx** [comment]
I was really puzzled reading #1217 because I thought we’d already done that. Yes, it’s semantically the same as #1210. I reintroduced the bug in 9104efa99997b226295868260d81e984cf14e3b1 by accidentally reverting #1210.
