### ISSUE TITLE
Long lines in moderation action description cause table to extend beyond container

### ISSUE THREAD

**Issue by NattyNarwhal** [lobsters/lobsters#1231]
Latest Orion and Safari (so, WebKit) for on macOS 14.
 
![Screenshot 2023-12-16 at 1 14 15 PM](https://github.com/lobsters/lobsters/assets/3161292/956acbae-b69f-4bf8-9457-01443cbf007b)

The line is causing it is almost certainly the long Google cache URL. It should be either breaking or capping the overflow here.

**Comment by epilys** [comment]
Adding a `word-break: break-word;` to the table `tr` elements seems to be sufficient.
