### ISSUE TITLE
User comments shows threads for deleted posts

### ISSUE THREAD

**Issue by NattyNarwhal** [lobsters/lobsters#1243]
An example is [here](https://lobste.rs/~shivaraj-bh/threads), where the story `jgezbz` was deleted, but a user's comments on the article make all the threads that they were in visible. Deleted articles should have their comments hidden from this.

**Comment by pushcx** [comment]
Did this in 159fc2e80335ea414e0cfc8ba296e4cfdeb79c8b but missed the `#` in the commit message for GitHub to pick it up.

There was a hassle during implementation where I wanted to use `.joins(:story).merge(Story.not_deleted(user))` but that caused errors that `Column 'is_deleted' in where clause is ambiguous`, even if I rewrote the `Story.not_deleted` scope to remove its [use of a string]() with `scope :not_deleted, ->(user) { user.try(:is_moderator?) ? all : where(is_deleted: false).or(Story.where(user_id: user&.id)) }` I feel like I missed a step and was adding the Story scope slightly wrong.
