### ISSUE TITLE
Add NBlog support

### ISSUE THREAD

**Issue by lime360** [lobsters/lobsters#1249]
[NBlog](https://github.com/fazlabz-dev/nblog) is an open standard for exchanging messages that I've developed.

There is an [official server in PHP](https://github.com/fazlabz-dev/nblog-server) along with [Hairbrush Social](https://github.com/fazlabz-dev/hairbrush-soc), which is a full-featured social network.

**Comment by pushcx** [comment]
It doesn't look like there are any servers up or that we have any users who use it to justify the dev and maintenance time.

**Comment by lime360** [comment]
there is a server at lime360.serv00.net
