### ISSUE TITLE
Replies via mailing list mode are  bouncing

### ISSUE THREAD

**Issue by CMB** [lobsters/lobsters#1253]
https://the-brannons.com/crud/borked.mbox

**Comment by pushcx** [comment]
I'm sorry I missed this bug somehow. Thank you for this detailed report, I'm investigating.

**Comment by pushcx** [comment]
This was a tricky one, the mail script was running in a unique shell environment that didn't recognize the lobsters-specific ruby environment, and then there are several levels of quoting needed to set up correctly.

There's a larger fix available, I'll file an issue so it's not lost.
