### ISSUE TITLE
Possible double karma bug with merged stories

### ISSUE THREAD

**Issue by mewsian** [lobsters/lobsters#1262]
I received 14 karma 5 days ago from a comment I made on the story about Yuzu emulator being sued. Today the story was merged into a new story "the emulator Yuzu is dead" and I think I received another 14 karma. This is the merged story I'm referring to:

https://lobste.rs/s/cnh6uz/nintendo_switch_emulator_yuzu_is_dead

I'm sorry I haven't looked into the code to identify if/where the bug occurs, and I'm not 100% sure it happened, but I think I was at 98 karma before the story merge, and now I'm at 112.

**Comment by matthieu2311** [comment]
I ran a few tests on my own version of the server and I don't see this problem. Was it fixed or is it still happening ?

**Comment by pushcx** [comment]
I don't remember any code deliberately addressing this, but it sounds like it's probably not a continuing issue, and it'll be handled anyways if merged stories get redesigned as part of #1298.

Thanks for testing this, @matthieu2311.
