### ISSUE TITLE
mastodon bot chokes on & (ampersand) in story titles

### ISSUE THREAD

**Issue by fs111** [lobsters/lobsters#1263]
Whenever the story title contains an ampersand the bot swallows the rest.

Examples:

- https://botsin.space/@lobsters/112134430872404198
- https://botsin.space/@lobsters/112117954699031513
- https://botsin.space/@lobsters/112100555723714370

**Comment by kornelski** [comment]
And converts `+` to space, so the content is passed through query string somewhere, without escaping.

**Comment by pushcx** [comment]
another one today https://botsin.space/@lobsters/112778715410734429

https://lobste.rs/s/muz4xy/at_t_unlawful_access_customer_data
