### ISSUE TITLE
Unable to delete an account

### ISSUE THREAD

**Issue by kivikakk** [lobsters/lobsters#1267]
I'm getting a 422 Unprocessable Content upon submitting an account deletion request.

At first I thought it was because the `user[i_am_sure]` field is submitted twice (once with `0` for the hidden field, once with `1` for the checked box), but upon removing the hidden field it still produces that output. (And indeed, on not checking that box, the [error flash](https://github.com/lobsters/lobsters/blob/c7ef797a764c8dcc02fa4f27b5b69b701b1eac3b/app/controllers/settings_controller.rb#L16) is correctly displayed.)

Then I thought perhaps the authenticate call was failing, but using an incorrect password produces the correct error flash too, so I'm guessing it's just being raised by `@user.delete!` for some reason. I imagine the error log will contain more useful information; maybe there's some delete that's not cascading.

**Comment by pushcx** [comment]
I’m sorry, this must be an especially annoying time for a bug like this. I found the backtrace, it seems to have something to do with the doffed hat, a validation is complaining that it can’t be used. Which is narrowly true, but not relevant. I’m investigating the bug.


> We are programmed to receive / You can check out any time you like / But you can [never leave](https://en.wikipedia.org/wiki/Hotel_California)!

**Comment by kivikakk** [comment]
Makes total sense!

Perhaps it was just as well (for me at least!); in more recent times I've come to enjoy participating more again. :)
