### ISSUE TITLE
When searching for a story by URL, the parse tree displayed for the search query omits that URL

### ISSUE THREAD

**Issue by roryokane** [lobsters/lobsters#1270]
## Bug description

When searching for a story by URL, such as <https://lobste.rs/search?q=https%3A%2F%2Fghuntley.com%2Ffracture%2F&what=stories&order=newest>, after expanding the “_n_ results for” section, the parse tree that should be below “Search query parsed to:” is empty:

> <img width="638" alt="empty parse tree when searching for an existing story by URL" src="https://github.com/lobsters/lobsters/assets/79168/8671be9f-d42c-4ecf-abfc-a529608dd403">

This empty parse tree is visible by default [when there are no results](https://lobste.rs/search?q=https%3A%2F%2Fexample.com%2Fno_such_story&what=stories&order=newest):

> <img width="445" alt="empty parse tree shown by default when searching by URL with no results" src="https://github.com/lobsters/lobsters/assets/79168/b2691a43-746d-455f-b208-bae6b7010671">

For comparison, search terms that aren’t URLs (as in [this search](https://lobste.rs/search?q=https%3A%2F%2Fghuntley.com%2Ffracture%2F+Microsoft&what=stories&order=newest)) are described in that section:

> <img width="659" alt="parse tree shows descriptions of terms other than the URL" src="https://github.com/lobsters/lobsters/assets/79168/10b5c731-77cb-4cb8-98cc-09f170cb8e1f">

The “Search query parsed to:” section should describe how the URL was parsed from the search, too.

## Implementation suggestions

The search parse tree is displayed in this view:

https://github.com/lobsters/lobsters/blob/c7ef797a764c8dcc02fa4f27b5b69b701b1eac3b/app/views/search/index.html.erb#L53-L62

That `case` statement needs a `when :url` branch.

<details>
<summary>The chain of code that shows the parse tree should contain a <code>:url</code> key with the URL as its value</summary>

https://github.com/lobsters/lobsters/blob/c7ef797a764c8dcc02fa4f27b5b69b701b1eac3b/app/controllers/search_controller.rb#L10

https://github.com/lobsters/lobsters/blob/c7ef797a764c8dcc02fa4f27b5b69b701b1eac3b/app/models/search.rb#L18-L19

https://github.com/lobsters/lobsters/blob/c7ef797a764c8dcc02fa4f27b5b69b701b1eac3b/app/models/search_parser.rb#L52

https://github.com/lobsters/lobsters/blob/c7ef797a764c8dcc02fa4f27b5b69b701b1eac3b/app/models/search_parser.rb#L42

https://github.com/lobsters/lobsters/blob/c7ef797a764c8dcc02fa4f27b5b69b701b1eac3b/app/models/search_parser.rb#L22-L27

`.as(:url)` ensures the resulting parse tree `Hash` will contain a `:url` key. See `as` described in [Parslet’s parsing docs](https://kschiess.github.io/parslet/parser.html).

</details>

The ERB inside the new `when :url` branch should represent a `dt` element followed by a `dd` element, the same as all the other branches.

**Comment by pushcx** [comment]
Thank you for this bug report and diagnosis. The fix is deploying now, with a little extra code to hopefully recognize these quicker.
