### ISSUE TITLE
Sorting for /messages should be newest message on top, not oldest

### ISSUE THREAD

**Issue by freddyb** [lobsters/lobsters#1272]
Having received a fair share of message on lobste.rs over the past few years, it's a bit annoying to scroll all the way down for newest messages. It would be nice if they were in reverse chronological order.

**Comment by pushcx** [comment]
/messages is sort of deliberately a bit clunky to encourage people to delete old messages and move to email. I'm going to say wontfix at least until there's a stronger case for it.
