### ISSUE TITLE
Bug count wrong on merged stories

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#1275]
Unconfirmed, pasting from IRC so it doesn't get lost:

> aibou Hi, I think that there is a bug causing the website to display a wrong number of comments on "merged" stories. One example is https://lobste.rs/s/0qvtim/,  which says there are 138
>                    comments, even though there appear to be 148 comments. Another is https://lobste.rs/s/uihyvs/, indicating 306 rather than 311. I estimated the correct number of comments
>                     by Ctrl-F searching for the number of occurrences of "comment_text" in the HTML source.

**Comment by rog404** [comment]
Hi @pushcx 

I have verified that this is not an issue.

When using the comment_text tag, comments removed by the author are also being captured. This explains why there are more comments than those visible on the page.

To confirm this, you can filter by:
div.comment div.comment_text => resulting in 148 comments in the [first example](https://lobste.rs/s/0qvtim/) (all comments)

However, when you filter by:
div.bad div.comment_text => resulting in 10 comments (deleted comments)

Therefore, the 138 comments counter is correct.

**Comment by pushcx** [comment]
Thanks for investigating this report, glad to have this puzzle solved.
