### ISSUE TITLE
Print media query

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#1282]
We don’t have any print-specific CSS now and look pretty good. There’s opportunity for a few tweaks like hiding `comment_folder` and comment forms. I don’t know anything else off the top of my head and would like to keep this pretty light.

**Comment by shubhamsugara22** [comment]
would like to try this one @pushcx

**Comment by pushcx** [comment]
@shubhamsugara22 did everything asked in this issue, so I'm going to close it. That doesn't mean our print media query is 'done' so much as 'done for now' because it's a feature request. If you are reading this in the future and have improvements, please reopen or open a PR.
