### ISSUE TITLE
web UI for hat editing

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#1283]
Related to #1247, mods (not users) need a web UI to edit hats. Single-field form to edit the text, with two buttons:

 * Edit in place (help text: replaces hat on old comments)
 * Doff + create new (help text: doesn't change old comments)

Both options need to create clear modlog entries.

This came up in the context of [andyc](https://lobste.rs/~andyc) (@andychu here) renaming Oil Shell -> Oils, which I badly procrastinated on because of the hassle of thinking this through and then doing it in the console.

**Comment by kernal053** [comment]
I am working on this issue. Below are few screenshots for references. 

Edit Hat form
<img width="879" alt="Screenshot 2024-08-06 at 3 57 49 PM" src="https://github.com/user-attachments/assets/491d3add-7214-4082-a8c2-8afcb8af2d8c">

Modlog for edit in place option
<img width="886" alt="Screenshot 2024-08-05 at 7 53 14 PM" src="https://github.com/user-attachments/assets/471ffaf8-fd35-4ca5-8fd3-57a5f935e9a6">

Modlog for doff and replace option
<img width="879" alt="Screenshot 2024-08-05 at 7 55 02 PM" src="https://github.com/user-attachments/assets/4b8973a9-41b0-46b5-a24a-e21b8b839081">

Are any more changes needed in form ? Also, does modlog entries conveys message properly ? Let me know if anything can be conveyed in better way.

**Comment by pushcx** [comment]
For editing a hat, please make the message `Renamed Hat "A" to "B"`. And replacing, `Doffed hat "A" to replace with "B"`
