### ISSUE TITLE
Replace parse_inbound_email with Action Mailbox

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#1285]
The mailing list most receives incoming email to the [parse_inbound_email](https://github.com/lobsters/lobsters/blob/master/script/parse_inbound_mail) script, which has unfortunately been kind of janky. Most recently we had #1253, but there have been others. I remember it's been significant debugging every time there have been major hosting changes.

Years after the script was developed, Rails 6 (I think?) added [Action Mailbox](https://guides.rubyonrails.org/action_mailbox_basics.html) to better address this area. Let's update to be more Railsy and use Action Mailbox.

**Comment by glokta1** [comment]
One of the steps required to migrate to ActionMailbox involves configuring Postfix to pipe inbound emails to `bin/rails action_mailbox:ingress:postfix`. Reference: https://guides.rubyonrails.org/v7.1/action_mailbox_basics.html#postfix.

This might be something you have to do on your end on the mail server @pushcx

**Comment by pushcx** [comment]
I'll have to deploy it, but the config for it is [available here](https://github.com/lobsters/lobsters-ansible/blob/1ddd062b2c1f9580c0b28ed125a0a407b892cdec/roles/lobsters/files/forward) with the rest of our system setup.
