### ISSUE TITLE
Chrome has wrong text selection color

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#1289]
Firefox, correct:

![2024-06-10_12-18](https://github.com/lobsters/lobsters/assets/6262/a101c9f5-4b0d-4111-9d33-95c9afe1aad7)

Chrome, incorrect:

![2024-06-10_12-18_1](https://github.com/lobsters/lobsters/assets/6262/4a45ca54-e05e-4dae-84b2-ad06aa6d519f)

Presumably it's wrong in dark mode, too, but I didn't check that.

**Comment by shurj0** [comment]
https://github.com/lobsters/lobsters/pull/1294

System colors are deprecated in CSS3

**Comment by pushcx** [comment]
Following @shurj0's investigation we'll just let the user agent use its default.
