### ISSUE TITLE
Quote marks (exact search) operator doesn't work on https://lobste.rs/search

### ISSUE THREAD

**Issue by karlicoss** [lobsters/lobsters#1296]
According to https://lobste.rs/search, it should be possible to use quotes operator to search exact query, e.g. `"lobsters search"`
However any query with quotes gives empty results, e.g. https://lobste.rs/search?q=%22lobsters+search%22&what=comments&order=newest

Even single words give no matches when quoted: https://lobste.rs/search?q=%22test%22&what=stories&order=newest

**Comment by pushcx** [comment]
Thanks for reporting this.

The `@10` at the end of the strings is from the Parslet library. The matches should have been turned intro strings, so that's at least part of the bug.

Whoever picks this up, please remember to add a test case or two. I'm surprised this didn't fail one.

**Comment by pushcx** [comment]
Thanks for the clear examples, I got this fixed.
