### ISSUE TITLE
flagged submissions lack flag reason

### ISSUE THREAD

**Issue by gustafe** [lobsters/lobsters#1300]
Today's newest page contains an unusual number of submissions with 0 or less net scores, but for a number of them there's no legible flag reason

<img width="1160" alt="Screenshot 2024-08-13 at 16 54 22" src="https://github.com/user-attachments/assets/d57f2180-367a-4fed-93e8-7b2b58ee5ab2">

* https://lobste.rs/s/1uihg8/type_confusion_attacks_prosemirror has 0 score but no flag reason
* https://lobste.rs/s/exrfes/developing_clis has -1 but only one flag (1 spam)
* https://lobste.rs/s/t5exgw/whenfs_fuse_filesystem_for_your_google has 0 score but no flag reason
* https://lobste.rs/s/v3ouvk/approach_optimizing_typescript_type has 0 score but no flag reason

There are a number of other examples with the same symptoms.

**Comment by jmiven** [comment]
Flags do not not affect the score anymore, but hiding a story do in some cases: https://github.com/lobsters/lobsters/commit/1414e96c3ce59bc96806684889997fe37fc0ef5a

**Comment by pushcx** [comment]
I've [changed this behavior](https://lobste.rs/s/lyvlhn/should_we_have_low_content_low_effort_flag#c_vz7frw) so hiding alone no longer reduces score and refreshed the scores of all stories submitted in the last couple days.
