### ISSUE TITLE
Comments missing from the /threads page

### ISSUE THREAD

**Issue by jmiven** [lobsters/lobsters#1301]
[This comment and the ones below it](https://lobste.rs/s/lyvlhn/should_we_have_low_content_low_effort_flag#c_mrczlx) are missing from the `/threads` page of their respective authors :

[/~pushcx/threads](https://web.archive.org/web/20240814170632/https://lobste.rs/~pushcx/threads)
[/~eatonphil/threads](https://web.archive.org/web/20240814170453/https://lobste.rs/~eatonphil/threads)
[/~jmiven/threads](https://web.archive.org/web/20240814170352/https://lobste.rs/~jmiven/threads)

**Comment by jmiven** [comment]
Thank you!

**Comment by pushcx** [comment]
Thanks for the report! It was a fun one to reproduce, it only appeared to users who are logged in and not a moderator. I added some tests for the behavior so hopefully it won't sneak back in.
