### ISSUE TITLE
JSON endpoint for finding Lobsters URLs by stories

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#1304]
Add endpoint to return JSON with an array of story urls. There's a few potential uses oriented around making it easier to find Lobsters discussions. It has come up enough times over the years that I've gotten over my reluctance to add API endpoints that the site js isn't using.

`/stories` (as befits our god object) is very busy. Maybe this should have its own little controller like `/stories/url`? Then there could be routes `/stories/url/all?url=....` to do what's describe above. Then also `/stories/url/latest?url=...` to 302 to the latest version (nice for a bookmarklet, or for bloggers to add a link from their posts). If the story hasn't been submitted before... I'm not sure what to serve, maybe a custom 404 page? Maybe 302 to `/stories/new` with that prefilled? But that's not great for visitors without accounts.

Note: Use `Utils.normalize_url` or `Story.find_similar_by_url` 

This also needs to be documented on `/about` so that folks can find it in the future.

[Nogweii](https://www.twitch.tv/Nogweii) has volunteered to take this on. I see @nogweii has the same avatar so I'm going to roll the dice and ping them.

**Comment by danlamanna** [comment]
For reference, one motivating use case would be a web extension similar to [What Hacker News Says](https://github.com/pinoceniccola/what-hn-says-webext) which shows a popup similar to this when clicked:
![image](https://github.com/user-attachments/assets/cff8f899-6566-49b9-ae71-6fcd38faf1aa)

**Comment by nogweii** [comment]
Still to be finished, but here's what the JSON will likely look like:

```json
[
  {
    "short_id": "xv6ea4",
    "short_id_url": "https://lobste.rs/s/xv6ea4",
    "created_at": "2024-08-15T20:34:22.000-05:00",
    "title": "Temporibus non optio",
    "url": "http://cole.test/rona",
    "score": 1,
    "flags": 0,
    "comment_count": 18,
    "description": "",
    "description_plain": "",
    "comments_url": "https://lobste.rs/s/xv6ea4/temporibus_non_optio",
    "submitter_user": "ret_frances_bernier",
    "user_is_author": false,
    "tags": [
      "temporibus"
    ]
  }
]
```

**Comment by pushcx** [comment]
Completed by @nogweii in #1303
