### ISSUE TITLE
Upgrade to Rails 7.2

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#1311]
https://rubyonrails.org/2024/8/22/Rails-7-2-1-has-been-released

**Comment by petrenkorf** [comment]
@pushcx Is this issue already taken by someone? Otherwise, I'm willing to take this as it is a "good first issue"

**Comment by pushcx** [comment]
This was implemented in #1314, which I just caught up with and merged. But I hope to see your name on another 'good first issue'. :D
