### ISSUE TITLE
trilogy_connect - unable to connect to 

### ISSUE THREAD

**Issue by voodoo** [lobsters/lobsters#1323]
ActiveRecord::ConnectionNotEstablished: Connection refused - trilogy_connect - unable to connect to 127.0.0.1:3306 (ActiveRecord::ConnectionNotEstablished)

I'm on macOS. I've installed mysql with brew.  Is there anything I'm missing? (where is the chat - I don't have a Facebook) I'm a pretty ok developer but it has been awhile since I've done any rails. Any guidance appreciated.

**Comment by pushcx** [comment]
You'll want to install mariadb, not mysql. They use the same port, though, so if you're getting this message then there's more setup to make sure mariadb starts. I don't use brew myself, but I found some [official docs](https://mariadb.com/kb/en/installing-mariadb-on-macos-using-homebrew/) that look straightforward.

The [Lobsters chat is on IRC](https://lobste.rs/chat), not Facebook.

**Comment by pushcx** [comment]
I've added some documentation for this dependency. Please reopen if you see an opportunity to improve it.
