### ISSUE TITLE
Simplified Chinese support

### ISSUE THREAD

**Issue by zhangysh1995** [lobsters/lobsters#1324]
I deployed lobsters myself, and found several problems with using simplified Chinese. 
For example, when I try to add a category:

<img width="405" alt="image" src="https://github.com/user-attachments/assets/fbda8da5-8d3a-430a-b860-fc78fb53d6b6">

It throws such an error:

<img width="840" alt="image" src="https://github.com/user-attachments/assets/c0ddd76d-ab63-40fa-bd98-60bc15a4865f">

I try adding a tag, it says it is invalid:

<img width="404" alt="image" src="https://github.com/user-attachments/assets/403600c2-4d73-42b0-9add-c22c046ed992">

<img width="406" alt="image" src="https://github.com/user-attachments/assets/fc1f0f6c-76b9-4a9b-9fdc-02fbf8ff7c2a">

I want to use lobsters to build my own website in Chinese so I will first try improving it myself.
I use source code at commit: 7dfc493725ffa36401bd51bfb31fa15c48077701.

**Comment by pushcx** [comment]
The problem is in `app/models/tag.rb` line 21.

There are many places the codebase assumes a western alphabet, or assumes that an attribute is safe to use in a URL. You will need to check all model validations.
