### ISSUE TITLE
Spurious request throttling

### ISSUE THREAD

**Issue by viraptor** [lobsters/lobsters#1325]
Recently (this week?) I'm running into an issue where the first visit is intercepted and a throttling message is shown. Something about rack attack, throttling and sleep(1). I keep forgetting to save it unfortunately and it needs a long time to reproduce.

It seems that the throttling is misconfigured and affects my initial request, but not any later ones. This happens pretty reliably for user `viraptor` on lobsters.

**Comment by viraptor** [comment]
Got lucky this time: 
```
Throttled, sleep(1) between hits; more in config/initializers/rack_attack.rb
```

**Comment by pushcx** [comment]
The fact that this popped up after 48880af9286d3c2944676bf38e2b8e1830c9bb18 makes me think it's probably the same bug as #1412.

@viraptor (or anyone!) please reopen if you still have this problem.

**Comment by viraptor** [comment]
Just checked the `/touch-icon-144.png` file and other icons like `/favicon.ico` and although they have an `etag`, there doesn't seem to be any explicit caching instructions. Adding a `Cache-Control` header could help a bit as well.

**Comment by pushcx** [comment]
Good catch! I've filed it as a bug over in the ansible repo with our nginx config.
