### ISSUE TITLE
Story disowning

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#1331]
Users can [disown comments](https://github.com/lobsters/lobsters/blob/f512ae4187be05098978c28055a076db3604df31/app/controllers/comments_controller.rb#L175) individually or entirely as they delete their account, but only disown all stories by deleting their account.

For this feature, add a 'disown' link that functions similarly to comment disowning. It should only appear on the individual story page (not every place the story is listed) and not while the edit window is open, similar to comments.

**Comment by SharvariTatachar** [comment]
Hi! I'm looking to work on this issue, but I'm having trouble setting up. I'm getting this error when I run bin/setup: 
`bin/setup:8:` syntax error, unexpected ':', expecting ')'
  system(* exception: true)
bin/setup:38: syntax error, unexpected end-of-input, expecting end`

Any ideas on what I'm missing?

**Comment by nogweii** [comment]
>  I'm getting this error when I run bin/setup

I think you're running into an issue with new ruby syntax. Are you running Ruby 3.2+?
