### ISSUE TITLE
`Utils.normalize(url)` mishandles `www10.org`

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#1339]
Part of normalizing URLs tries to remove `www` from hostnames, including with digits. It's too aggressive and stripping a real hostname off the TLD. So we have a Domain named `org` instead of `www10.org`: https://lobste.rs/domains/org/

**Comment by nogweii** [comment]
Per the conversation in today's stream, this is probably not because of `Utils.normalize` but instead `Story.set_domain` (or `set_domain_and_origin` if/when the `origin` branch gets merged).
