### ISSUE TITLE
New "origins" feature exposes link that requires elevated permissions to normal users

### ISSUE THREAD

**Issue by gustafe** [lobsters/lobsters#1341]
While browsing the modlog I could see that a new feature called "Origins" allowed for more fine-grained filtering of domains. 

The first domain to be unbanned is dataswamp.org, and the "domains" page <https://lobste.rs/domains/dataswamp.org> has a line at the top:

> dataswamp.org: 11 stories from 8 submitters with [2 origins](https://lobste.rs/domains/dataswamp.org/origins)

However, attempting to access the link <https://lobste.rs/domains/dataswamp.org/origins> leads to an error page for my user:

> You are not authorized to access that resource.

**Comment by pushcx** [comment]
Whoops! Thanks for point it out, I'm deploying the fix now.
