### ISSUE TITLE
Removed moderated comments remain in unread counter

### ISSUE THREAD

**Issue by technomancy** [lobsters/lobsters#1353]
My red "unread replies" counter next to "Inbox" at the top right has been stuck at a minimum of 1; I believe this is because I had an unread reply that got removed here: https://lobste.rs/s/1roeql/stallman_report#c_pjhutv

Clicking on the 1 leads me to `/inbox` which redirects to `/messages` when no unread replies can be found.

New unread replies can increase this number above 1, (in which case `/inbox` works for the new replies) but as far as I can tell I'm unable to get it below 1.

**Comment by Eduardo-Lpz** [comment]
This one was a weird one to reproduce it, and from my (lacking of all context) testing seems to be more related to `messages` instead.

**Comment by pushcx** [comment]
@technomancy can you confirm that you see the correct number/behavior now? Please reopen if anything seems odd.

**Comment by technomancy** [comment]
@pushcx looks like that did the trick; thanks!

**Comment by pushcx** [comment]
Great, always nice to confirm when the repro steps don't quite work. Thanks again, @Eduardo-Lpz!
