### ISSUE TITLE
Adding Elestio as deployment option

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [lobsters/lobsters#1357]
Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing Lobsters application as shown [here](https://elest.io/open-source/lobsters). I think it would be a great idea if we can add it to official readme/documentation here.
🔔 In addition to this, if you are interested we provide partnership opportunities with tools we support by **revenue share** upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

Example Button:

[![Deploy on Elestio](https://elest.io/images/logos/deploy-to-elestio-btn.png)](https://elest.io/open-source/lobsters)

**Comment by pushcx** [comment]
I can't stop you from using the open source codebase, but I need you to immediately cease and desist using screenshots of https://losbte.rs, our logo, or our site description "a computing-focused community centered around link aggregation and discussion" to advertise your service. It's grossly misleading to imply you're affiliated with the site or host it. For clarity, you also need to explicitly state that you're unaffiliated with the site.

Please ask if any of this is unclear and comment here confirm here when you've removed.

**Comment by pushcx** [comment]
ping @jbenguira - This needs your immediate attention.

**Comment by pushcx** [comment]
I received an email from @jbenguira confirming that he's aware of this request that Elestio immediately cease and desist its misleading statements and appropriation of the site logo and screenshots. He has not yet committed to a timeline for correcting Elestio's marketing.

```
   Hey Peter, I saw your message here:
   [1]https://github.com/lobsters/lobsters/issues/1357
   It seems based on your message you are threatened by our service or
   thinking we are parasites or something like that. 
   1) FYI we are trying to contact all open source authors we have in our OSS
   catalog on Elest.io, the goal is to offer a partnership where we pay the
   authors 30% profit sharing. 
   Here is our partnership
   contract: [2]https://sign.elest.io/d/16NpSgdG9QsYM7
   2) Even if legally you can't prevent us from offering lobster as a service
   we are not a bad actor, we try to contribute to open source, and if you
   are not happy with what we do WE AGREE to remove lobster from our
   platform.
   3) We believe we can contribute to Lobster as a partner, sponsor, and also
   creating articles & videos about lobster
   Please just let me know what you think, I'll be happy to do a call
   with you to talk about it more in details if you are interested
   Kind regards,

   Joseph BENGUIRA

   Chief Technology Officer

   [3]https://elest.io 

     

   Confidentiality and Virus Warning
   This e-mail is confidential and is intended exclusively for the person(s)
   named above. If it has been delivered to you by mistake, please notify the
   sender and then delete this e-mail. If you are not the intended recipient
   be aware that any disclosure, copying, distribution or use of the contents
   of this information and or files is prohibited. You are requested to carry
   out your own virus check before opening any attachment. Appdrag Limited
   accepts no liability for any loss or damage which may be caused by
   software viruses.

References

   Visible links
   1. https://github.com/lobsters/lobsters/issues/1357
   2. https://sign.elest.io/d/16NpSgdG9QsYM7
   3. https://elest.io/
```

**Comment by jbenguira** [comment]
> He has not yet committed to a timeline for correcting Elestio's marketing.

Hey Peter, we have updated the marketing page to address your requests, you can check here: https://elest.io/open-source/lobsters

Can you please let me know about 2 other points?

1) Are you interested in a rev sharing partnership concerning all instances of lobsters deployed on elestio? You can check the contract I sent by email 
or
2) Do you prefer us to remove lobster from our platform? 

Kind regards
Joseph

**Comment by jbenguira** [comment]
> Thank you, I appreciate you promptly revising this. There's one more use of our site intro on your [resources page](https://elest.io/open-source/lobsters/resources), the first sentence "Lobsters is a community-driven..." is taken from our About page.
I'll make sure this is also fixed by tomorrow, also I've noted your answers about the other points.
Finally I wanted to THANK YOU for your great OSS project :)
