### ISSUE TITLE
replies on flagged posts do not show up in inbox

### ISSUE THREAD

**Issue by lolbinarycat** [lobsters/lobsters#1362]
If a post gets enough flags to be "auto-hidden", any further replies will not get sent to the author's inbox.

**Comment by pushcx** [comment]
This is intentional, to avoid the 'replies' feature reminding people to keep fighting in flamewars or pushing threads further off-topic. There's a [few more conditionals](https://github.com/lobsters/lobsters/blob/master/db/views/replying_comments_v10.sql) too.
