### ISSUE TITLE
Migrate Fediverse mirror to a different instance

### ISSUE THREAD

**Issue by chamlis** [lobsters/lobsters#1363]
The [Lobsters Fediverse mirror](https://botsin.space/@lobsters) is currently on the instance https://botsin.space, which [is shutting down](https://muffinlabs.com/posts/2024/10/29/10-29-rip-botsin-space/). Relevant to Lobsters, it'll become read-only shortly after December 15th, and shut down altogether some time after March 2025.

**Comment by pushcx** [comment]
Thanks for filing this to track the work. We also [discussed the shutdown on Lobsters](https://lobste.rs/s/7tyhmz) so it's not off my radar, but it's good to put it with the rest of the to-dos.
