### ISSUE TITLE
Hat request is rejected when it’s approved

### ISSUE THREAD

**Issue by dpk** [lobsters/lobsters#1371]
I requested a hat and @pushcx said it was approved. I got a message saying it was rejected, and I can’t don the hat. We tried again at his request, and the same thing happened – he’s definitely sure he clicked ‘approve’.

The rejection message includes no content, only a subject ‘Your request for hat "R7RS WG2 chair" has been rejected’.

**Comment by pushcx** [comment]
Perhaps because I didn't add anything in the textarea?

**Comment by pushcx** [comment]
We tried a third time, and no, it fails even with text.

Irritatingly, I got a green success flash message reading "Successfully rejected hat request."

Whoever fixes this, please add a `feature` spec for both approving and rejecting hat requests. This has probably been broken since I split out the `HatRequestsController` three months ago, which I suppose is also an admission of how far behind I was on requests.

**Comment by pushcx** [comment]
I'm digging through the log to find all the wrongly-rejected hat requests and message the affected users. Here's a sample; the `_method` param is the culprit.


```
{
  "method": "DELETE",
  "path": "/hat_requests/74",
  "format": "html",
  "controller": "HatRequestsController",
  "action": "destroy",
  "status": 302,
  "allocations": 13166,
  "duration": 58.75,
  "view": 0.0,
  "db": 20.95,
  "location": "https://lobste.rs/hat_requests",
  "timestamp": "2024-11-09T19:59:16.757Z",
  "params": {
    "_method": "delete",
    "authenticity_token": "[FILTERED]",
    "hat_request": {
      "reason": ""
    },
    "commit": "Approve Hat Request"
  },
  "exception": null,
  "exception_message": null,
  "remote_ip": "[redacted]",
  "perf": {
    "allocations": null,
    "duration": null,
    "view": null,
    "db": 20.954580999386963
  },
  "user_id": 78,
  "username": "pushcx"
}
```

**Comment by pushcx** [comment]
I have messaged all the affected users to apologize and created all the wrongly-rejected hats. So there's no remaining tasks requiring prod access, just the bugfix + tests.
