### ISSUE TITLE
json logging perf wrong

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#1372]
Example - the `allocations` and `duration` values are outside of the `perf` hash (and shouldn't exist) and are `null` inside of `perf`. The duplicated `view` and `db` keys outside of `perf` should be removed. The time values in `perf` should be rounded to the nearest whole ms.

```
{
  "method": "GET",
  "path": "/t/practices.rss",
  "format": "rss",
  "controller": "HomeController",
  "action": "single_tag",
  "status": 200,
  "allocations": 38379,
  "duration": 214.9,
  "view": 14.78,
  "db": 111.76,
  "timestamp": "2024-11-09T19:51:27.310Z",
  "params": {},
  "exception": null,
  "exception_message": null,
  "remote_ip": "[REMOVED]",
  "perf": {
    "allocations": null,
    "duration": null,
    "view": 14.776980999158695,
    "db": 111.75560299670906
  },
  "user_id": 0,
  "username": "nobody"
}
```

**Comment by kernal053** [comment]
After, going through Lograge gem I have few observations.  `allocations` , `durations`, `view` and `db` are core options of  process_options event of ActionController LogSubscriber. And custom_options provided in config are added to this main event. So, it won’t be possible to removed those values from our resulting json log. 

https://github.com/roidrage/lograge/blob/27066cd75d449cb91ed79b18c4271d62a76c9839/lib/lograge/log_subscribers/base.rb#L29-L37

Also, `allocation` and `durations` are part of `event` not `event.payload`. To obtain those values one need to change `event.payload[:allocations] -> event.allocations ` and `event.payload[:duration] -> event.duration.to_f.round(2)`.

**Comment by pushcx** [comment]
Thanks for investigating. With the info you found, I don't think it's worth the added complexity to try to put the performance info into a sub-hash. I can just delete the `perf` hash to leave all the data with the correct values and formatting at the top level.
