### ISSUE TITLE
Add optional "random" sorting on `Ask` threads

### ISSUE THREAD

**Issue by epilys** [lobsters/lobsters#1374]
"Ask" threads are useful for getting answers to a question, but sometimes the top-voted one might not be the most appropriate for everyone; we might not be looking for the same thing after all, and top answers can turn into an echo-chamber since they are most visible when opening the page.

My proposal is adding a "random" sorting for Ask posts in particular, which can either be opt-in or opt-out. Flagged comments should still take a sorting penalty, probably.

This can also be a good first issue for new contributors.

**Comment by epilys** [comment]
Side note: "Who's hiring" and "What are you doing this weekend/week" threads are also "Ask" threads; I think this proposal would benefit them as well by making less-upvoted posts have spotlight and a chance to be upvoted.

**Comment by pushcx** [comment]
> Please discuss feature requests in the chat room or a meta thread before posting.

I missed the meta discussion, could you link it or give me a timestamp for the irc log?

**Comment by epilys** [comment]
No meta discussion was done before this, closing.
