### ISSUE TITLE
Receiving emails for comments on hidden stories

### ISSUE THREAD

**Issue by mikejsavage** [lobsters/lobsters#141]
If you hide a story and have the mailing list enabled, you still receive emails when people comment on it.

**Comment by mikejsavage** [comment]
I don't think this has been fixed. For example, I've manually hidden the "systemd sucks" story but am still receiving followup emails.

**Comment by jcs** [comment]
@mikejsavage this should be fixed again now

**Comment by mikejsavage** [comment]
It's back again! I'm receiving emails for comments on flagged stories, which don't show up on the comments page.
