### ISSUE TITLE
Firefox on Android keeps requesting apple-touch-icon.png

### ISSUE THREAD

**Issue by dzwdz** [lobsters/lobsters#1412]
For a few months (?) I've constantly been getting throttled by rack-attack when using lobste.rs on my phone.
After contacting @pushcx it turns out that I've been requesting `/apple-touch-icon.png` and `/apple-touch-icon-144.png` over and over in bursts of 5-12 hits.
Apparently I'm not the only one - pushcx is seeing a "staggering numbers of hits, all recent versions of Firefox on Android".

Those URLs aren't linked anywhere on the site, but the latter [is mentioned in some Apple documentation](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html).

I'm on Firefox for Android 133.0.3, which seems to be the latest version, and the only installed extension is uBlock Origin.

This *might* be related to #1325?

**Comment by pushcx** [comment]
There was one remaining reference to `/apple-touch-icon-144.png`. I don't know if Android FF would try to render the Twitter card but it's possible. Or they've cached the old URLs. Either way, I've fixed the remaining reference and softlinked the old URLs. That should solve this.
