### ISSUE TITLE
check for duplicate article immediately

### ISSUE THREAD

**Issue by robey** [lobsters/lobsters#149]
This is really a usability bug, not a logic bug, but it's my biggest frustration right now.

When posting a new article, it should check for a duplicate url immediately after you paste it into the url field. That would save me a lot of effort coming up with tags and typing a short summary, only to find out at the last stage that someone else has already posted the link.

**Comment by jcs** [comment]
This doesn't appear to be worked on anymore, so if someone wants to take it with as minimal a change as possible I'd probably merge it.

**Comment by barce** [comment]
Hi @jcs I'd like to work on this tonight. I'm working on an HN for photographers using lobsters.
