### ISSUE TITLE
Disable invitation-only?

### ISSUE THREAD

**Issue by jsandlund** [lobsters/lobsters#155]
Hi, 

I'm new to rails and jamming around on Lobsters. 

I see that Oauth is included out of the box. Is there a way to disable the invitation only-setting and allow anyone to register via oAuth?

**Comment by tannakartikey** [comment]
Shouldn't there be a toggle for it? I can contribute if you want that feature

**Comment by talklittle** [comment]
@tannakartikey https://github.com/lobsters/lobsters/pull/455
