### ISSUE TITLE
Feature: Reddit-style red mail icon on comment reply

### ISSUE THREAD

**Issue by taoeffect** [lobsters/lobsters#218]
I've noticed that conversations tend to die unnecessarily on Lobsters because a story goes off the front page.

Someone who notices it late might make an insightful comment, replying to some other comment, and nobody is aware of it.

That, IMO, is an unnecessary tragedy that Reddit has managed to fix brilliantly simply by displaying a highlighted red "mail" icon in the top right of the screen any time someone replies to one of your comments, or to one of the stories you submitted.

Could be a solution for the concern expressed in #78 as well.

**Comment by Fastidious** [comment]
This is a very good idea. I am loving Lobste.rs!
