### ISSUE TITLE
Add option to receive comment replies as private message

### ISSUE THREAD

**Issue by rpglover64** [lobsters/lobsters#299]
See: https://lobste.rs/s/oevsxr/feature_request_response_notifications

> Seems reasonable, just needs another 2 checkboxes in the settings for “comment reply notification settings” and “comment mention notification settings” to add “receive private message”.  You can file it here, though unless you’re going to include a PR, it will probably take a long time for someone to get to it.
> -- [jcs](https://lobste.rs/c/evlddz)

Well, I'm not including a PR, but at least it will be on the radar and I'll get a notification when it gets fixed.

**Comment by pushcx** [comment]
Rather than create a private message from a system user, #218 solves this same problem with a UI improvement. I'm closing this in favor of it.
