### ISSUE TITLE
Feature request: tag-scoped search

### ISSUE THREAD

**Issue by pushups** [lobsters/lobsters#317]
I think being able to restrict searches to specific tags would be a very helpful feature. I did find a few old threads asking for it:
https://lobste.rs/s/gg4d7o/ask_jcs_can_we_get_tag_search
https://lobste.rs/s/uprcao/feature_request_narrow_limit_searching

I'm particularly interested in being able to search ask. There have been a few posts recently asking about tools the community uses, and books that people have found helpful that would be great to go back to if I happen not to bookmark them immediately. Of course I think the utility extends way beyond that.

I'm willing to look into building this if it would be a useful feature, and I'm not duplicating work.

**Comment by pushcx** [comment]
This would be very straightforward to add to `Search#search_for_user!` `app/models/search.rb` now that the site searches via SQL. I'd like to see syntax like `tag:python django' to search for stories about "django" tagged with "python".

**Comment by pushups** [comment]
I'll take a stab at implementing this.

**Comment by pushups** [comment]
Closing because this is merged!

**Comment by pushcx** [comment]
Thanks, @pushups. I have already used this on prod to find a story. :)
