### ISSUE TITLE
Ability to sort your threads

### ISSUE THREAD

**Issue by pilkch** [lobsters/lobsters#325]
If I comment on stories A, B, C they can be mixed up in "Your Threads", B, A, C for example.  At a guess it seems to be based on the time the original story was submitted, not my comment?

The map in my head of my threads is in the order I start contributing to them.  It would be great if I could "Sort by my comment order" or "Sort by parent story order".

**Comment by pilkch** [comment]
What happens when a user adds comments 1, 2, 3 to stories A, B, A?  Should they be shown in the user's timeline order or the story then comment timeline order?

**Comment by pushcx** [comment]
There isn't a strong demand for this feature request and there's no code, so I'm going to close this issue. I think there's definitely room for an improved personal discussion page but that's best handled in a `meta` discussion on the site itself.
