### ISSUE TITLE
Feature Request: Continuing work on JSON API

### ISSUE THREAD

**Issue by lukefiji** [lobsters/lobsters#361]
Wondering if you would like to make any progress on the JSON API from #42? I'm working on a Lobste.rs React web app as a practice project and would love to move onto creating a React Native version later down the road. 

I'm wondering how difficult it would be to be able to feed more than just the first 25 hottest/newest posts; and if it is possible in a reasonable manner, I would really like to work with you and give you my input to help make this API flourish

**Comment by pushcx** [comment]
@lukefiji If you'd like this please open a PR with code. Me building out an API by guessing at someone else's needs would likely only be of marginal use (and adds a maintenance burden).

If you do embark on this, please don't make one giant PR for all possible endpoints. It would be very helpful to be able to see them one at a time and give suggestions for future improvements so you wouldn't waste your own time writing code that wouldn't be a good fit for the project.
