### ISSUE TITLE
Feature: "positive" filters

### ISSUE THREAD

**Issue by oconnore** [lobsters/lobsters#372]
For example: I'd like to filter out most Ruby posts, but I don't want to filter out an "Art" post that just happens to be done using "Ruby".

So in the big list of checkboxes, you could have an extra column "important" or something like that. And then if any of the tags included "Art", it would always get shown regardless of my other filters.

**Comment by pushcx** [comment]
I'd like this feature, as this is exactly why I've never filtered any tags.

**Comment by finnoleary** [comment]
I understand that this is an old issue, as it's open I guess it hasn't been fixed?

Do you think using background shading to indicate 'important' items would be an acceptable solution?

**Comment by pushcx** [comment]
Correct, we've never implemented anything along these lines. We already use color to indicate tag type (media, admin-only) so shading might be hard to understand.

I think most of the complexity of this is figuring out UI for [/filters](https://lobste.rs/filters) so it's clear what's happening and why.

Added complexity note: visitors who are not logged-in users can filter tags, see `TAG_FILTER_COOKIE`.

**Comment by pushcx** [comment]
It's been a couple years, closing. Looks like I was the only one who wanted this, and now as a mod I can't filter anything.
