### ISSUE TITLE
Dark Theme / Selectable Styles

### ISSUE THREAD

**Issue by MDCox** [lobsters/lobsters#404]
Hey all :)

I'm opening this issue to explore how interested people would be in having selectable themes on lobste.rs .  Personally I rather enjoy dark themes, and being effectively nocturnal, the shift to the pure white theme can feel like such an assault to my eyes that it's not too uncommon for me to use curl or lynx instead of actually accessing the site via chrome like I normally would.  While it wouldn't be too hard to change the styling for just my browser, I was wondering if other people would find use in any of the following possible features:

- The ability to switch to a dark theme
- The ability to switch among multiple themes
- The ability to define your own theme

Being able to toggle between a light and dark theme makes most sense to me. It's simple, doesn't lead to option or asset bloat, and would likely address the most common need but the other options are natural extensions.  At least code-wise it seems that the first two options would likely be implemented in the same way, just with a different interface (checkbox vs. dropdown.)  The ability to define custom themes would obviously be more involved.

Upsides to doing this: providing the ability to customize themes for people who prefer dark themes, are color blind, or just feel the need to mess with stuff.

Downsides: probably opens up a Pandora's box of bikeshedding and unnecessary choice when the current theme is nice, clean, effective, and basically accepted.  Also it increases maintenance burden since maintaining two stylesheets is more involved than one.

Implementation wise there aren't many real questions I don't think.  Save the selected theme on the user model either as a bool or reference to the theme and include the correct stylesheet in the layouts while falling back to the default.  Specifics on a dark theme or other themes to include are undefined and can get bike-sheddy, but can easily be tweaked/discussed down the line.

I'm totally up to implement it, I just didn't know if it's something other people wanted and whether it's something @jcs would accept considering the required migration and maintenance consideration.

**Comment by talklittle** [comment]
> While it wouldn't be too hard to change the styling for just my browser

I think this approach may make more sense actually. It's easy to do by installing an extension (Stylus/Stylish), and offloads the maintenance burden to the community. Also you get unlimited flexibility to adjust themes to your exact liking if you don't like every detail about the community provided ones.

https://userstyles.org/styles/browse?search_terms=lobste

**Comment by xkpb** [comment]
I'm okay with one canonical light theme, and one canonical dark theme. Other than that, if users want to define their own ad hoc styles I think using browser extensions would be best for them, like @talklittle mentioned.

**Comment by talklittle** [comment]
I'm gonna take back my original comment. There is value to a built-in dark theme, especially on mobile, where extensions may be nonexistent or a pain to deal with.

**Comment by pushcx** [comment]
The best place to poll about features is a `meta`-tagged thread on Lobsters itself.

I would have to see overwhelming demand to want to support user-defined styles. A single toggle to a dark theme seems OKish if someone can suggest a good place in the UI for it... and, again, that discussion should be in a meta thread. :)
