### ISSUE TITLE
moderations page broken

### ISSUE THREAD

**Issue by jcs** [lobsters/lobsters#418]
https://github.com/lobsters/lobsters/commit/4a0bde4312d8591d79de24c4ed67dbee41dac76b broke:

      undefined method `map' for nil:NilClass
      app/views/moderations/index.html.erb:8:in `block in _app_views_moderations_index_html_erb___250235976051282676_3138816036620'

**Comment by pushcx** [comment]
In the console, does `User.moderators` return `nil` or you, Irene, and kyle?

(And I've remembered I should've used `pluck` instead of `map`, but that'd leave the same error.)

**Comment by jcs** [comment]
No, it returns 3 users.

**Comment by jcs** [comment]
Well it's no longer throwing exceptions now, but I have no idea why it was before or why it isn't now.  Oh well.

**Comment by pushcx** [comment]
This bug is super weird. I've spent an hour trying to reproduce it and can't. If you happen to have any more debugging info like a full traceback please leave it, otherwise I'll just keep my eyes open for recurrence.
