### ISSUE TITLE
URL encoding for specialcharcters won'r work.

### ISSUE THREAD

**Issue by roottr** [lobsters/lobsters#419]
Hello,

It seems Lobster won't correctly encode URl for special characters.

For example: 

shows as > s/xociqc/tesla_11_bin_adet_model_x_arac_n_geri_r_yor

should be > s/xociqc/tesla_11_bin_adet_model_x_aracini_geri_cagriyor

Would you know how to fix this?

Thanks a lot in advance.

**Comment by pushcx** [comment]
This isn't a bug to be fixed. Not every character is [valid in a URL](https://stackoverflow.com/questions/7109143/what-characters-are-valid-in-a-url) and [Story#title_as_url](https://github.com/lobsters/lobsters/blob/f1ad8922467e6c915fbb23d48369d79ae886bcbf/app/models/story.rb#L674) reflects this with the gsub a few lines down: `gsub(/[^a-z0-9]/, "_")`. If you'd rather leave out the non-ascii characters, replace the `"_"` with `""`.

**Comment by roottr** [comment]
Hi @pushcx  thanks a lot for your response. Would you know also how I can encode turkish character such as title   "başakı" to "basaki" ?

Thank you very much in advance.

**Comment by pushcx** [comment]
It looks like [`parameterize`](http://api.rubyonrails.org/v5.1/classes/ActiveSupport/Inflector.html#method-i-parameterize) does this.

This could replace the `downcase` and maybe some of the use of `gsub` in `title_as_url`. I'm reopening this issue, it would be a nice small feature. If you use this on your site, please open a pull request so the main Lobsters code can include it.
