### ISSUE TITLE
Merged submissions disappear from a user's submission list

### ISSUE THREAD

**Issue by colindean** [lobsters/lobsters#423]
A story I submitted was merged into another story. My submission is missing from my own submission list. I would expect it to be there, maybe with some indication that it has been merged into another, but, when clicked, redirect to the merged story when visiting it.

Reproduction:

1. When I go to https://lobste.rs/newest/colindean
2. I expect to see https://lobste.rs/s/xun2wv/severe_flaw_wpa2_protocol_leaves_wi_fi at the top of the list
    * this story has been merged with https://lobste.rs/s/dwzplh/krack_attacks_breaking_wpa2
3. I do not see this story there.

**Comment by pushcx** [comment]
Thanks for the clear bug report.

**Comment by pushcx** [comment]
Fixed by jmks in #570
