### ISSUE TITLE
User's own comments from merged stories don't show own vote

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#424]
https://lobste.rs/s/dwzplh/krack_attacks_breaking_wpa2#c_varrat

Probably just need a tweak to whatever query pulls in the comments of a merged story. This doesn't allow people to vote multiple times, it's just a data fetching + display issue.

**Comment by vishalsodani** [comment]
I think I have found the solution. I tired changing this line

`@votes = Vote.comment_votes_by_user_for_story_hash(@user.id, @story.id)`

to

`@votes = Vote.comment_votes_by_user_for_story_hash(@user.id, (@story.merged_stories.ids).push(@story.id))`

**Comment by evexoio** [comment]
@vishalsodani I've tested your suggestion and it works. will create PR soon.
