### ISSUE TITLE
Email TLS went missing

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#426]
User report:

> Hey, I just noticed emails are no longer using TLS after the migration. It results in a big red lock icon in Gmail. Could TLS be re-enabled for email please?

**Comment by talklittle** [comment]
Seems like it's a matter of pointing the Sendmail config to the Let's Encrypt certificate. https://aput.net/~jheiss/sendmail/tlsandrelay.shtml

**Comment by pushcx** [comment]
We're using [postfix](http://www.postfix.org/TLS_README.html), which looks straightforward. @alynpost wants to redo our LE config, so this is blocked on that.

**Comment by pushcx** [comment]
I've enabled issues on the lobsters-ansible repo and added an issue for this bug, which is about the deployment setup rather than the rails codebase: https://github.com/lobsters/lobsters-ansible/issues/2

**Comment by alanpost** [comment]
I have re-enabled TLS and verified google received the message encrypted and with a good signature:

ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@lobste.rs header.s=prgmr-0 header.b=bypOhpX4;
       spf=pass (google.com: domain of nobody@lobste.rs designates 71.19.148.33 as permitted sender) smtp.mailfrom=nobody@lobste.rs;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=lobste.rs
Return-Path: <nobody@lobste.rs>
Received: from lobste.rs (lobste.rs. [71.19.148.33])
        by mx.google.com with ESMTPS id a1si3400595plp.90.2017.10.26.13.17.10
        for <[]@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 26 Oct 2017 13:17:10 -0700 (PDT)

Would you confirm you no longer have a red lock icon on email from lobste.rs?

**Comment by pushcx** [comment]
Tested with a GMail acocunt, no red lock, tls headers visible.
