### ISSUE TITLE
Logging of moderator hats being used spams moderators with notifications about their own moderation actions. Moderation moderation moderation.

### ISSUE THREAD

**Issue by IreneKnapp** [lobsters/lobsters#429]
https://github.com/lobsters/lobsters/commit/bfc8cc0c9d5d49597fd74d2a7c9f7127b405f389 added this new functionality, which logs the use of the SysOp hat for public accountability. Apparently the fact that it appends to the moderation log means that it generates a message (including an email, if they have that turned on) to the person whose comment it was. In this scenario, the person who commented is already aware that a moderation action occurred because they were the one who took it.

I think the appropriate fix is probably to check whether a person is being notified about their own action, and if so, suppress the message.

If this counts as a feature request, I can find time to implement it I guess...

**Comment by evexoio** [comment]
> If this counts as a feature request, I can find time to implement it I guess

@IreneKnapp are you still down to take on this issue?

**Comment by evexoio** [comment]
@IreneKnapp That's great, we're not in a hurry 🙈

**Comment by IreneKnapp** [comment]
I figured, lol. Considering it only annoys mods. Okay, please consider me to be owning the fix.

**Comment by pushcx** [comment]
I got bugged at this one and realized I knew exactly where to fix it, so I did. :smiley:
