### ISSUE TITLE
Submit comment with Ctrl+Enter or Cmd+Enter

### ISSUE THREAD

**Issue by colindean** [lobsters/lobsters#430]
I'd like to be able to type ⌘↩︎ (that's Command + Enter) to submit comments and maybe posts, too. I'd set it to use Ctrl+Enter, too.

I want to poll for some kind of consensus that people like this before I spend the time to do the work.

**Comment by jcs** [comment]
https://github.com/lobsters/lobsters/commit/22e04c0b9037e2bcc3be35e108f69e51470eb2da#diff-4214baf57cb704da1865fc11c65cfab6

**Comment by colindean** [comment]
…this worked just now. It didn't work when I filed this, I swear 😩

Must have been a PEBKAC problem. Thanks for pointing out its existence.
