### ISSUE TITLE
I can't resubmit link

### ISSUE THREAD

**Issue by unbalancedparentheses** [lobsters/lobsters#440]
I am trying to resubmit this link since they added the new 2017 videos of the conference and it is not possible:
http://bangbangcon.com/recordings.html

**Comment by azdle** [comment]
I just ran into this too. It just always go back to the submit page saying I can submit it anyway. I was able to submit something by adding a checkbox to the page calling it `story[seen_previous]` / `story_seen_previous`

I don't really understand rails, but I'm pretty sure this is an issue in the view that generates the error html, here: https://github.com/lobsters/lobsters/blob/master/app/views/stories/_form_errors.html.erb#L25-L28

AFICT `f` will never be defined there. I assume this is a copy-paste error when the error stuff was moved into its own file. I'm not sure if the proper thing would be to pass `f` in or move the hidden form element back, but I assume either would fix it.

@talklittle, looks like you moved the error stuff into it's own file. Could you look and tell me if I'm crazy? Thanks!

**Comment by talklittle** [comment]
@azdle I think you're right; maybe passing `:f` in `locals` via `stories/_form.html.erb` would fix it? I guess I'll submit a pull request
