### ISSUE TITLE
inconsistent view of layout for new comments before and after refresh

### ISSUE THREAD

**Issue by nickpsecurity** [lobsters/lobsters#443]
Right after the new comment posted, skade and I's comments weren't lined up properly with the minus signs on different sides for each of us. I reloaded the page in new tab. They were lined up correctly with minus signs on same side. Attached before and after images.

![lopsided with minuses reversed](https://user-images.githubusercontent.com/17504074/34689808-6983b6ca-f47c-11e7-8893-58891f2240ef.png)

![looks normal after refresh](https://user-images.githubusercontent.com/17504074/34689819-71a46886-f47c-11e7-8f1e-0087c7d2c2b4.png)

**Comment by talklittle** [comment]
Duplicate of #428
