### ISSUE TITLE
Bug: Uncaught ReferenceError: autosize is not defined

### ISSUE THREAD

**Issue by avinassh** [lobsters/lobsters#447]
Happens when you are not logged in and view any post. Check the console for this error.

1. Visit - https://lobste.rs/s/ouqngb/never_accept_mdm_policy_on_your_personal

2. Check console:

<img width="1392" alt="screen shot 2018-01-20 at 9 56 55 pm" src="https://user-images.githubusercontent.com/640792/35185570-de91e81a-fe2c-11e7-9740-d705849a9ca2.png">

**Comment by pushcx** [comment]
Thanks for reporting this, real easy to square away.
