### ISSUE TITLE
Hats not working?

### ISSUE THREAD

**Issue by IreneKnapp** [lobsters/lobsters#451]
As of this morning, I don't see a place to choose a hat when posting comments. Is that everyone, or just me?

**Comment by pushcx** [comment]
Not just you, it must be a bug in the doffing code. I'm running it down now.

**Comment by pushcx** [comment]
MySQL apparently ignored that I wanted the `doffed_at` timestamp to default to null and used `0000-00-00 00:00:00` on existing hats. I've corrected that and confirmed that new hats default correctly.
