### ISSUE TITLE
Replies page shows deleted replies

### ISSUE THREAD

**Issue by anadrome** [lobsters/lobsters#452]
A discrepancy between handling of deleted comments on the replies page versus elsewhere. On the replies page, all deleted replies are shown, with the "[Comment removed by author]" annotation. Elsewhere in the interface, deleted leaf comments are hidden entirely, and only deleted comments that themselves have replies are shown. As a result, the link from a deleted comment shown on the replies page to where it would exist on the story page goes to a nonexistent anchor ([example](https://lobste.rs/s/jq1lbx/are_there_viable_privacy_focused_social#c_zoep3w)).

**Comment by pushcx** [comment]
Thanks for the report, I've [fixed](https://github.com/lobsters/lobsters/commit/640f2cdca10cc737aa627dbdf0bbe398b81b497f) this.
