### ISSUE TITLE
Incorrect comment tree toggle button position on Previewed or Cancelled Edit

### ISSUE THREAD

**Issue by talklittle** [lobsters/lobsters#458]
Comments render incorrectly when pressing Edit, and then Preview or Cancel. The tree collapse button moves to the wrong place on a desktop browser.

**Comment by sean-public** [comment]
I have reproduced this as well.

The tree collapse button is removed when you press "edit" on a comment and is never added again when the textarea is dismissed. The JS should always re-insert that element when exiting the edit state.

**Example**
![image](https://user-images.githubusercontent.com/21961562/36951056-774cdc28-1fc4-11e8-930f-4d4263eb1e01.png)
The collapse button was formerly at the bottom of the dotted line and does not return when leaving the editor by any means.
