### ISSUE TITLE
Avoid IDs with obvious bad words

### ISSUE THREAD

**Issue by sean-public** [lobsters/lobsters#461]
When [generating an id](https://github.com/lobsters/lobsters/blob/108baedb39206198e442a5bb0828c644862a79e0/app/models/short_id.rb#L34) to be used for a newly created post, there are no checks for the content of the produced text. These then become canonical paths to the posts on the site, which can eventually lead to URLs that include, say, `faggot`, `fuckhn`,  or even [`assman`](https://i.imgur.com/vxfc3Up.jpg).

I suggest a quick scrub of IDs for the worst English words. I don't think other languages are necessary because the site is entirely in English. A [typical banned words list](http://www.bannedwordlist.com/lists/swearWords.txt) can be used and filtered down to words 3-6 letters in length, inclusive. If there is a match with the banned list, just re-roll to get another random string ([this retry logic is already in place](https://github.com/lobsters/lobsters/blob/108baedb39206198e442a5bb0828c644862a79e0/app/models/short_id.rb#L9)). I think this will only remove a tiny fraction of the 36⁶ space, so that's not a concern.

[Here's the current code generating the random IDs](https://github.com/lobsters/lobsters/blob/28c8217652456bf361516501559e559e6b744ec2/extras/utils.rb#L2..10).

**Comment by pushcx** [comment]
As the submitter of [`im2gay`](https://lobste.rs/s/im2gay) I get it, but this is uncommon enough that I think we can chuckle at winning the `(n bad words) in 36⁶` lottery. I don't mind editing one in a prod console if we have a prod problem.
