### ISSUE TITLE
Broken migration "20180131203555_fix_doffed_at.rb" on MySQL 5.7.21

### ISSUE THREAD

**Issue by talklittle** [lobsters/lobsters#462]
`ActiveRecord::StatementInvalid: Mysql2::Error: Incorrect datetime value: '0000-00-00 00:00:00' for column 'doffed_at' at row 1: UPDATE `hats` SET `hats`.`doffed_at` = NULL WHERE (doffed_at = '0000-00-00 00:00:00')`

**Comment by pushcx** [comment]
What are your settings for ALLOW_INVALID_DATES, NO_ZERO_DATE, and/or NO_ZERO_IN_DATE? (I'm unhappy to hear that even after all the hassle MySQL gave me about this field, it's still breaking things.)
