### ISSUE TITLE
Option to be emailed story replies

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#465]
The new replies notification system has an odd asymmetry: users get both comments posted on their stories and replies to their comments listed as 'replies' on the site, but only have the option to have the latter emailed to them. A user who's joined since the replies notification system saw the personal setting "Comment Reply Notification Settings" and expected that they'd be emailed both. They reported a bug that they weren't getting emails and it took a few minutes to puzzle out. I think it would be worth adding it as an option, defaulted off for existing users but on for new users.

**Comment by iridakos** [comment]
+1

**Comment by pushcx** [comment]
Was doing a pass through all the open issues and realized this is a dupe of #161.
