### ISSUE TITLE
Prefilled password fields for "delete my account"

### ISSUE THREAD

**Issue by chneukirchen** [lobsters/lobsters#466]
In Firefox, the `autocomplete="off"` for "Delete Account" at https://lobste.rs/settings is ignored, which lets it prefill the password, making account deletion just a single click away.

I'd propose to rename the field so this doesn't happen, or to show a popup where one needs to enter the password (ala Twitter).

**Comment by talklittle** [comment]
@pushcx Unfortunately that change didn't help, on Firefox 59.0.1. It still prefills the account deletion password. Other password fields on the page are left blank as expected.

**Comment by pushcx** [comment]
Looks like this is [by design](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion):

> For this reason, many modern browsers do not support autocomplete="off" for login fields:
> 
> *    If a site sets autocomplete="off" for a form, and the form includes username and password input fields, then the browser will still offer to remember this login, and if the user agrees, the browser will autofill those fields the next time the user visits the page.
> *    If a site sets autocomplete="off" for username and password input fields, then the browser will still offer to remember this login, and if the user agrees, the browser will autofill those fields the next time the user visits the page.
> 
> This is the behavior in Firefox (since version 38), Google Chrome (since 34), and Internet Explorer (since version 11).

There's nothing I can do about it, apparently. [This Support page](https://support.mozilla.org/en-US/kb/control-whether-firefox-automatically-fills-forms) describes how users can disable this behavior. If Firefox offers a way to disable this I'll add it.

**Comment by talklittle** [comment]
@pushcx Please see PR #476, it works by making the input disabled initially.

**Comment by pushcx** [comment]
This was resolved by the merge of @talklittle's PR #447.
