### ISSUE TITLE
rake db:schema:load doesn't generate foreign key in database

### ISSUE THREAD

**Issue by WanCC1995** [lobsters/lobsters#478]
I followed the readme to build up the applications. (build on MySQL)
I found that the foreign key only appears at app level, while db level doesn't have any foreign keys. It's kind of weird that the database don't do such validation.
I'm wondering how to make up it. One straight forward idea is to manually add such foreign keys to the database. But I guess that it may not be a wise idea.

Looking forward to your reply.

**Comment by pushcx** [comment]
The Lobsters codebase predates Rails's support for foreign keys. Confusingly, [the documentation](http://guides.rubyonrails.org/association_basics.html) uses the tern "foreign key" for the column assocating one record with the `id` column of another, though they are not database-level foreign keys.

Now that Rails supports FKs, it would be good to add a migration using [`add_foreign_key`](http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_foreign_key) for these. In the `rubocop` branch that recently landed I added a lot of the missing `:dependent => :destroy` and to associations, so this should be straightforward.

**Comment by WanCC1995** [comment]
@pushcx Thanks for your timely reply! I'll add a new migration.

**Comment by pushcx** [comment]
This was done in #548
