### ISSUE TITLE
ruby version

### ISSUE THREAD

**Issue by jakob-haider** [lobsters/lobsters#487]
can't run the server because bundler can't install the gemset with different rubies
`" gem ... not available for ruby sdk ... "`
the right ruby version to build is necessary. 
could you add this to the gemfile? like here 
[specifying ruby version in gemset](http://bundler.io/v1.12/gemfile_ruby.html)

**Comment by pushcx** [comment]
Could you paste the error you get? Do you know why the `.ruby-verison` that exists isn't working for you?

**Comment by pushcx** [comment]
Are you testing a bot? I see you've created two identical issues on two defunct projects.
