### ISSUE TITLE
Single reason field for user moderation

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#492]
At the bottom of `app/views/users/show.html` there's some moderation tools. There are two `reason` fields, one with a button for banning the user and one with a button for disabling their invites. I've been playing whack-a-mole with the spammer who likes to create accounts to upvote his spam and a couple times I've disabled invites when I've meant to ban. I'd rather have a single form like `app/views/stories/edit.html` where there's one `reason` field and two buttons. This will probably require editing the controller actions.

**Comment by jtopgi** [comment]
I'll take this issue.
