### ISSUE TITLE
Add HSTS header and preload HSTS

### ISSUE THREAD

**Issue by lgarron** [lobsters/lobsters#493]
https://hstspreload.org/?domain=lobste.rs

`production.rb` contains the following:

https://github.com/lobsters/lobsters/blob/0e55e37d5ac309adae9a6bfb0f9ca79861244685/config/environments/production.rb#L41-L42

However, there is no other reference to HSTS / `Strict-Transport-Security` in the rest of the codebase, and the live website does not send the header. Here's how I would recommend doing this:

- Get the Let's Encrypt cert to cover `www.lobste.rs` as well.
- Check that any other subdomains also work over HTTPS.
- Send the following header: `Strict-Transport-Security: max-age=63072000; includeSubDomains; preload`
- Submit to https://hstspreload.org/?domain=lobste.rs

I would dig into the code more and try to send a PR, but the `bundle` command fails for me and I don't really want to yak-shave the state of Ruby on my system. :-/

**Comment by pushcx** [comment]
This is over in the lobsters-ansible repo as https://github.com/lobsters/lobsters-ansible/issues/1 and https://github.com/lobsters/lobsters-ansible/issues/2.

Yak-shaving an Ansible/Python setup is even less enjoyable than a Bundler/Ruby setup, so no worries. :)
