### ISSUE TITLE
Feature request: submitting user filters

### ISSUE THREAD

**Issue by benwr** [lobsters/lobsters#495]
I hope this isn't taken the wrong way, but there is a small positive number of lobsters whose submissions I would strongly rather not see.

They tend to have provocative titles, be from the users' personal domains, and/or be focused on advice or culture. I don't want to filter out the relevant tags, since I do actually enjoy reading articles about culture and practice. I just feel that these particular users' submissions redirect my attention in a way that I don't like. I can imagine other people finding value in them, and they're not usually flaggable, they just make my personal experience of the site worse.

**Comment by pushcx** [comment]
I posted a user script in #197 for this that you could use to block out those domains.

**Comment by benwr** [comment]
Ah, sorry, I searched for duplicates but didn't see that one for some reason.

Thank you for the user script; I only wish I could use it on mobile :/

**Comment by pushcx** [comment]
Glad that mostly works for you, no worries on the dupe.

**Comment by cactus** [comment]
@pushcx Is there a way to filter/ignore users sending undesired direct Private Messages?

**Comment by pushcx** [comment]
No. If you've asked someone to stop and they continue, please contact me to look into it.
