### ISSUE TITLE
Can't vote on merged comments

### ISSUE THREAD

**Issue by Thra11** [lobsters/lobsters#500]
If multiple threads get merged into one, I can only upvote comments that aren't annotated with a 'fork' icon. If I attempt to upvote merged comments, it appears to work (triangle goes red, score increments), but when the page is reloaded, the upvote has disappeared.

**Comment by Thra11** [comment]
Not sure if related to #429

**Comment by pushcx** [comment]
It's closely related to #424, if not a dupe. We'll keep both to make sure they're both addressed.
