### ISSUE TITLE
Turn on belongs_to_required_by_default (rails 5.0 default).

### ISSUE THREAD

**Issue by thomasdziedzic-pd** [lobsters/lobsters#508]
As mentioned in https://github.com/lobsters/lobsters/pull/498/files#diff-b1fe55db50c712fef0673345e5b9c0d9R30

**Comment by pushcx** [comment]
Reviewing issues... how did this not break/start throwing warnings when I merged the `config.load_defaults 5.2`?

**Comment by thomasdziedzic** [comment]
I turn it off right after loading the 5.2 defaults: https://github.com/lobsters/lobsters/blob/master/config/application.rb#L29
