### ISSUE TITLE
Turn on rails 5.2 defaults after upgrade

### ISSUE THREAD

**Issue by thomasdziedzic-pd** [lobsters/lobsters#509]
Restart after each item:

- [x] Rails.application.config.active_record.cache_versioning = true
- [x] Rails.application.config.action_dispatch.use_authenticated_cookie_encryption = true
- [x] Rails.application.config.active_support.use_authenticated_message_encryption = true
- [x] Rails.application.config.action_controller.default_protect_from_forgery = true
- [x] Rails.application.config.active_record.sqlite3.represent_boolean_as_integer = true
- [x] Rails.application.config.active_support.use_sha1_digests = true

**Comment by pushcx** [comment]
Also:
 - [ ] [set `config.load_defaults`](https://github.com/lobsters/lobsters/pull/498#discussion_r195209699)

And as an implementation note, if someone wants to tackles this, you certainly don't have to do all of them. I'd be very happy to merge PRs for these one-by-one.

**Comment by pushcx** [comment]
I thanked Thomas in #528, but I want to note for any future readers of this issue that Thomas drove this migration and checked everything off the list in his many PRs.
