### ISSUE TITLE
unused data

### ISSUE THREAD

**Issue by hyperloop-rails** [lobsters/lobsters#518]
https://github.com/lobsters/lobsters/blob/8db5de92652365bcd2763eaf2b7bf76e727c2d08/app/controllers/users_controller.rb#L6

the used field of User is `is_active`, `username`, `is_banned`, `is_admin`, `is_modeartor`,  `created_at`, `invited_by_user`, `banned_at`, `banned_by_user`,  `banned_reason`, `hats`, `deleted_at`,  `karma`, `average_karma`. and unused fields are : `email`, `email_messages`, `pushover_messages`, and so on.

**Comment by pushcx** [comment]
This would be an non-idiomatic, high-maintenance change that would result in brittle code for a negligible performance gain.

If these are coming from a static analysis tool, please just post a `meta` thread about using it, or put in the human judgment to offer them only where the performance gain is worth the costs.
