### ISSUE TITLE
First tag joined to URL in Twitter posts

### ISSUE THREAD

**Issue by igorclark** [lobsters/lobsters#520]
As per screenshot below, the space between the Lobsters URL and the first tag is missing from Twitter article posts, and hence getting appended to the URL as though it were an anchor. For example the URL in this submission became https://lobste.rs/s/bndn3t#pdf:

![image](https://user-images.githubusercontent.com/164714/42050133-05743dde-7b00-11e8-9536-faccddd467ca.png)

I'm not a Rails person, so setting up a dev version and trying to work out how to test it would take me longer than seems reasonable for such a tiny issue. 😉

But looking through the code, I'm guessing it's caused by [this change]( https://github.com/lobsters/lobsters/commit/7dfbbea3b542e431161d662ee889131c3a64d5fc#diff-94dbd6164513f8a7a0bba4c48f80bd0eR15) to `script/post_to_twitter` in commit https://github.com/lobsters/lobsters/commit/7dfbbea3b542e431161d662ee889131c3a64d5fc:

https://github.com/lobsters/lobsters/blob/7dfbbea3b542e431161d662ee889131c3a64d5fc/script/post_to_twitter#L15

Hopefully it's a small enough fix to get snuck in (or bundled with something else) when there's time.

Cheers!

**Comment by pushcx** [comment]
A clear bug report is worth its weight in gold. Thanks for pointing this out, and you're correct about the introduction of this bug. I'm deploying the fix now.
