### ISSUE TITLE
tags missing during preview

### ISSUE THREAD

**Issue by nickpsecurity** [lobsters/lobsters#522]
Although I might be misremembering, I think the site used to show the tags in the preview of a new submission. The tags aren't there anymore. Was that intentional or a bug?
![no tags during preview](https://user-images.githubusercontent.com/17504074/42725347-baaddbda-8747-11e8-9b71-1180069929b3.png)

**Comment by pushcx** [comment]
It's a bug.

**Comment by btreim** [comment]
I'd love to take a crack at this.

**Comment by pushcx** [comment]
@btreim Help yourself! I typically review PRs and issues on Wednesday and Thursday mornings, so if you puzzle it out in the next day or two your fix will be seen quickly. Thanks for offering.

**Comment by btreim** [comment]
Just an update, my development laptop crashed shortly after taking this on. If someone else wants to jump on this issue in the meantime, by all means!
