### ISSUE TITLE
per-story comments link too small on iPhone Safari

### ISSUE THREAD

**Issue by alanpost** [lobsters/lobsters#524]
A user on IRC has reported that the comment link for stories is small and close to the scroll bar, making it difficult to click.  This has been confirmed by @hmadison, who says we need a larger touch target: we can use the 20px in between suggest and the icon for it.

**Comment by pushcx** [comment]
I don't have an iOS device available - can someone take a screenshot of this, please?

**Comment by pushcx** [comment]
Screenshot thanks to @hmadison: 
![img_0815](https://user-images.githubusercontent.com/6262/43837490-49b7d336-9ade-11e8-9248-6fb9817388ab.png)

To my eye this looks the same as on Android mobile. Probably the right fix is to make not just the number of comments a link, but the entire dialog balloon around it.
