### ISSUE TITLE
Multi Tag based Feeds

### ISSUE THREAD

**Issue by Church-** [lobsters/lobsters#525]
As per user suggestion, a feature I thought i'd recommend would be multi tag feeding, useful both to members and non member users of the site. Allowing you to search tags like so: lobste.rs/t/assembly+javascript+culture.

This feature would work both via web view, and via RSS as well.

**Comment by pushcx** [comment]
We had a chat about this on IRC and I accepted the feature request.

**Comment by sohaibbhatti** [comment]
Just thinking, would it make sense to show the intersection of tags? or the union?
I.e. for assembly+javascript+culture, would we displaying all feeds tagged as either assembly OR javascript OR assembly, or display feeds containing assembly AND javascript AND assembly?

I'd love to have a stab at this

**Comment by pushcx** [comment]
In chat I understood it to be union, so assembly OR javascript OR culture.

**Comment by sohaibbhatti** [comment]
Awesome thanks!

**Comment by noahhex** [comment]
@sohaibbhatti Yeah it's union, although adding intersection for more fine grained control would be interesting I think.

**Comment by pushcx** [comment]
In chat, rdivyanshu pointed out that we have the tag `c++` that will not work happily with a `.split('+')`. Because tags are only added by the administrator, the name field (`tag`) never got any validation limiting it. We'll have to find another joining character; I really don't want to rename that tag to `cplusplus` or something.

**Comment by crertel** [comment]
`|` perhaps?

**Comment by pushcx** [comment]
`|` is not a valid character in URLs, but `;` is, the markdown engine's `autolink` option recognizes it, and it has the meaning of separating things. Seems a reasonable color to paint this bikeshed.

**Comment by briankung** [comment]
Tempted to work on this next after a short break. Would it be okay if we allowed escaped plus signs (`%2B`) and kept the `+` delimiter? A la: https://stackoverflow.com/a/7146153/1042144

**Comment by pushcx** [comment]
Yeah, that sounds fine. I don't have anywhere near a strong enough opinion to force it on whomever is volunteering to implement this. :)
