### ISSUE TITLE
show deleted stories/comments to mods

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#556]
Few stories get deleted, but it's helpful for mods to see them. For example, [this outright spammer](
https://lobste.rs/u/pradm)'s profile shows 1 story submitted, but it was deleted. It should show to mods on [his /newest page](https://lobste.rs/newest/pradm). Similarly, via a [sockpuppet](https://lobste.rs/u/ceopsm) he posted a comment and it'd be helpful if it appeared on [that account's /comments page](https://lobste.rs/threads/ceopsm).

Also it'd be nice if the profile showed the correct stories count based on `@user.is_moderator?` - right now story count includes deleted for both and comment count does not include deleted for either. It'd be twice as nice if it showed both counts to mods, like "0 (+1 deleted)".

**Comment by jmks** [comment]
I'll try this one out!

**Comment by pushcx** [comment]
Cool, drop me a line however's convenient if you need a hand.

(But mostly I'm commenting so I can say that's an A+ cat photo)

**Comment by pushcx** [comment]
This was finished in 18167b36a5b01644932c826d5833ea0b7cd1daeb
