### ISSUE TITLE
Flick scrolling performance stutters

### ISSUE THREAD

**Issue by wting** [lobsters/lobsters#559]
When attempting to scroll through the comments page it stutters quite a bit ([mp4](https://gfycat.com/FloweryHappygoluckyAiredale)):

![floweryhappygoluckyairedale-size_restricted](https://user-images.githubusercontent.com/622170/46262504-27c3c200-c4b7-11e8-9973-cd6630feef75.gif)

I'm using an iPhone 8 and Chrome

**Comment by pushcx** [comment]
Huh, that's weird. Thanks for the clear demo.

Could you log out and see if it persists? The site only serves js to logged-out users. There's not much, but that might narrow down the possible causes.

**Comment by wting** [comment]
I can't reproduce in Incognito ([mp4](https://gfycat.com/gifs/detail/HarshTatteredGrayfox)):

![loggedout](https://user-images.githubusercontent.com/622170/46263323-88a4c780-c4c2-11e8-8fa1-3f6660ce54a9.gif)

**Comment by pushcx** [comment]
Well, we've only got [~600 lines of js](https://github.com/lobsters/lobsters/blob/master/app/assets/javascripts/application.js.erb), so that narrows things down considerably. Any chance there's someone know knows performance bugs in mobile Safari well reading this?

What's puzzling is that I don't think we have any events connected to scrolling or visibility; it's a dozen click handlers and a couple form editing niceties.

```
$ ag '\.on' app/assets/javascripts/application.js.erb 
423:  $(document).on("click", "a.comment_replier", function() {
464:  $(document).on("click", "button.comment-cancel", function() {
485:  $(document).on("click", "a.comment_editor", function() {
493:  $(document).on("click", "a.comment_deletor", function() {
502:  $(document).on("click", "a.comment_undeletor", function() {
512:  $(document).on("click", "a.comment_disownor", function() {
522:  $(document).on("click", "a.comment_moderator", function() {
536:  $(document).on("click", "div.markdown_help_toggler .markdown_help_label",
542:  $(document).on("click", ".comment-post", function(event) {
547:  $(document).on("click", "button.comment-preview", function() {
551:  $(document).on("click", "button.story-preview", function() {
555:  $(document).on("blur", "#story_url", function() {
578:  $(document).on("blur change", "#story_title", Lobsters.checkStoryTitle);
581:  $(document).on("click", "#story_guidelines_toggler", function() {
```

**Comment by knixeur** [comment]
select2 seems to be firing on scroll at assets/javascripts/select2.js line 320:
```
    /**
     * blurs any Select2 container that has focus when an element outside them was clicked or received focus
     */
    $(document).ready(function () {
        $(document).delegate("*", "mousedown focusin touchend", function (e) {
            console.log('asd');
            var target = $(e.target).closest("div.select2-container").get(0);
            $(document).find("div.select2-container-active").each(function () {
                if (this !== target) $(this).data("select2").blur();
            });
        });
    });
```
This only happens when the hats select is shown (as in the example video) maybe that's what's causing the problem.

**Comment by knixeur** [comment]
Reviewing the video I think the culprit is autosize + the nav/search bar that hide/shows when you start/end scrolling.
Autosize is keeping track of the current scroll and changing it if necessary
```
app/assets/javascripts/autosize.js 
58:				// made available by removing the scrollbar. The following forces the necessary text reflow.
80:			var bodyTop = document.body.scrollTop;
85:			var endHeight = ta.scrollHeight + heightOffset;
87:			if (ta.scrollHeight === 0) {
88:				// If the scrollHeight is 0, then the element probably has display:none or is detached from the DOM.
95:			// prevents scroll-position jumping
96:			document.documentElement.scrollTop = htmlTop;
97:			document.body.scrollTop = bodyTop;
```

And it's only enabled when you're logged in:
```
 -> ~/projects/lobsters $ rg autosize app/views/
app/views/stories/show.html.erb
43:      <% if @user %><script>autosize($("#comment")[0]);</script><% end %>

```

**Comment by pushcx** [comment]
Huh. Thanks for digging in on this. The appearance/hiding of the navbar is browser chrome we don't have control over (and don't want to exercise if we did).

We're running autosize.js 3.0.8 dated 2015-07-08, so first easy thing is to update and see if that fixes it. `resize()` has had substantial changes, so maybe that's it. I'm deploying now. 

Ominously, the [homepage](http://www.jacklmoore.com/autosize/) notes: 

> Autosize will automatically adjust the textarea height on keyboard and window resize events. There is no efficient way for Autosize to monitor for when another script has changed the textarea value or for changes in layout that impact the textarea element.

This reads to me like a known limitation the author is a bit tired of explaining. If it's not fixed, I'll look through their issue tracker and git history for more context. Maybe we can turn off the resizing logic on mobile, where resizes are very rare.

**Comment by knixeur** [comment]
Great, if that doesn't work I can implement a simple autogrow using something like https://stackoverflow.com/questions/43201862/strange-behaviour-with-textarea-autogrow-and-css-box-sizing

**Comment by knixeur** [comment]
Actually, it's probably best to try new autosize version first. It handles more browser specific quirks. If it doesn't work I'll go ahead and try to do something smaller/specific for this use case

**Comment by wting** [comment]
I can't reproduce the lag anymore! :tada:

**Comment by pushcx** [comment]
Wonderful. @wting thanks for such a clear report and a quick confirmation; @knixeur thanks for figuring out where we went wrong. I'll add an issue for the idea of removing the library for a small, custom solution.
