### ISSUE TITLE
Remove autosize.js?

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#575]
In #559 we updated autosize.js to fix a performance issue in mobile scrolling that was prompted by the screen resizing as the mobile browser hides its navigation bar while scrolling down and revealing it while scrolling up. @knixeur noticed that there are some snippets out on the web for resizing textareas, so I wanted to open an issue to explore the possibility of replacing autosize.js with a custom snippet. From the other direction, we could edit autosize to drop support for old browsers, window resizing, and unhooking. It's 1.3k after minification + gzip so this is not a huge win, but maybe someone would like a little puzzle.

If you are reading this in 2020 and no one has decided to play code golf, please post a comment to remind me to close this issue.

**Comment by blakef** [comment]
Bundle size comparisons:
```
140K	public/assets/application-after.js
 48K	public/assets/application-after.js.gz
144K	public/assets/application-before.js
 48K	public/assets/application-before.js.gz
```
No savings in the compressed bundle, so not worth dropping.

**Comment by pushcx** [comment]
After @blakef's PR #635 I agree that the savings is not worth the lost compat. Thanks for investigating!
