### ISSUE TITLE
Internationalize lobsters

### ISSUE THREAD

**Issue by finkiki** [lobsters/lobsters#584]
The lobsters interface should be translated into different language.

**Comment by pushcx** [comment]
[It was](https://github.com/lobsters/lobsters/commits/master/config/locales). There was little demand and no one volunteering to maintain translations, so it was a maintenance burden with no benefits.

**Comment by pushcx** [comment]
[Le Journal du Hacker](https://www.journalduhacker.net/) is a french translation of the site; I don't know if their codebase is available.

**Comment by finkiki** [comment]
I know this french translation, this code is available here : https://gitlab.com/journalduhacker/journalduhacker
But it's an old fork not really up-to-date. Ideally, what I would like is a way to stay up to date with lobste.rs while using a french translation on my own site, but I don't know if this is doable.

**Comment by pushcx** [comment]
I'd say just keep the lobsters repo as a remote and merge it in occasionally; this is what I do for [barnacles](https://github.com/pushcx/barnacl.es). If you enable `rerere` in your `~/.gitconfig` at least you shouldn't see merge conflicts more than once.

Lobsters is english-only, so I don't choose to volunteer to spend tens of hours adding i18n support and commit to the ongoing increased in maintenance time that comes from splitting strings out of our templates into a locale file, nor do I want to impose that burden on contributors to the code.
