### ISSUE TITLE
Make 'rails test' run our test suite

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#585]
For a while Rails has defaulted to the command `rails test` for running the test suite. On our codebase, that runs zero tests and exits; you have to run `rspec` to run the suite. There must be some little piece of missing plumbing that would let us match the default.

**Comment by andrezacm** [comment]
I believe `rspec-rails` adds the `rails spec` command to run all tests. 
If you run `rails -T` you're going to see it on the list.
`rails test` is going to run all tests inside `/test` directory, same thing for `rails spec`, not sure if it should be override...

**Comment by pushcx** [comment]
Yeah. `rails spec` works fine, but a number of times I've seen people pull the codebase, run `rails test` out of habit and say, "Oh, the app has no tests?"

**Comment by pushcx** [comment]
Added a placeholder so at least folks get an error message. Whoever looks into this, please delete the `test` directory in your PR.

**Comment by pushcx** [comment]
@evexoio When I ran `rails test` as described in the bug report, your fix didn't work. It still gave the same `0 tests` output. I've fixed it in 60ad809 but in the future, please include how you've tested that your fixes work. We could've caught that you were running a different command (presumably `rails test test/test_as_spec.rb`) than was reported before merge.
