### ISSUE TITLE
Ironic invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#590]
[app/models/story.rb](https://github.com/lobsters/lobsters/blob/master/app/models/story.rb) has a function for cleaning up unicode:

```ruby
  def title=(t)
    # change unicode whitespace characters into real spaces
    self[:title] = t.strip.gsub(/[\.,;:!]*$/, '')
  end
```

In prod, this function just threw:

```
invalid byte sequence in UTF-8
  app/models/story.rb:733:in `gsub'
```

when I attempted to submit this url : http://marctenbosch.com/quaternions/

This was via the bookmarklet, which open's a new tab with the current page's url and title tag as queryparams, which is reflected in the exception notifier:

```
  * Parameters : {"url"=>"http://marctenbosch.com/quaternions/", "title"=>"Let’s remove Quaternions from
every 3D Engine (An Interactive Introduction to Rotors from Geometric Algebra)", "controller"=>"stories",
"action"=>"new"}
```

Hoooooowever, due to some system along the way not wanting to pass on invalid utf-8, copying and pasting this title doesn't include the invalid utf-8 sequence, you'll have to pull from the `<title>` tag on the page.

Last bit, and why I'm submitting instead of just smashing this bug: I know this can be fixed with a call to `encode` here, but it's the wrong layer. Either something went wrong in the controller/strong params/the field that this invalid utf-8 didn't get caught or (feels more likely) every Rails string coming in has this problem. A quick search turned up some really old posts rather than a "oh yeah, set `config.actually.sanitize.parameters = :nobody_wants_invalid_utf8_strings_why_is_this_not_the_default` in your `config/application.rb`" so I'd appreciate a hand.

**Comment by pushcx** [comment]
(I am aware you do want invalid strings in uploads or when using non-utf encodings, please do not read too much into my puzzled griping, which is why I mention 'the field' to point at ActiveRecord.)

**Comment by evexoio** [comment]
Hey @pushcx, I want to take on this issue.

Have you arrived to any other conclusion for what's causing this issue?

**Comment by pushcx** [comment]
No, I haven't thought about it at all since posting. I was a bit overwhelmed interviewing for and starting a new job.

**Comment by evexoio** [comment]
Ok it seems like Sponge's response body is of encoding `ASCII-8BIT`, converting it to utf using `.force_encoding('ISO-8859-1').encode('UTF-8')` works just fine.

But you said it should be on another layer and you don't want to use encode to solve this. 

I traced it back to `Sponge.fetch`, where `res` is returned with its body's encoding as `ASCII-8BIT`.
So another angle we can fix this from is by looking into the `Sponge` class

**Comment by pushcx** [comment]
This looks reasonable at first glance, thanks for digging in to the bug. I'll give it a full review tomorrow, probably.

**Comment by pushcx** [comment]
Ah, so it's https://bugs.ruby-lang.org/issues/2567 we're running into. `Net::HTTP` is basically returning raw bytes and letting the user figure out if the `Content-Type` header is correct, or if the response is HTML and an included charset can be trusted. So `force_encoding('ISO-8859-1')` for this page is correct, but won't be correct for other pages. Rather than trying to get smarter and figure out the encoding of the page, let's get dumber: can we instead call `.encode!(invalid: :replace, undef: :replace, replace: '')` to make sure we get utf-8 and don't raise exceptions, whatever the encoding (and correctness thereof) of the client? It's OK if we drop the occasional smartquote.

**Comment by evexoio** [comment]
@pushcx getting dumber here is a good way to go 👍 

I've done the changes and pushed(too many force pushing – excuse my git skills 😭)

**Comment by pushcx** [comment]
I don't mind the force pushes, especially from someone volunteering to contribute to solve so many bugs and features. Thank you.

But it's easy because they're really not a big deal for redoing a personal branch in a small project like this. I see activity on other issues/PRs that looks like you're working on your `master` branch and rebasing it occasionally - I guess that's a lesson in why it's worthwhile to work on contributions in individual branches, it's a lot easier when pulling upstream changes doesn't suggest you should rewrite your commits.

I've really appreciated your enthusiasm. I don't know if you use IRC, but it'd  be great to have you (or anyone reading this interested in the codebase!) visit [the chat room](https://lobste.rs/chat) to talk about what you're up to, approaches to problems, or just chat during the day about stories posted to the site.

So, anyways, I'm glad you located the source of this bug and we were able to solve it. Merging now.
