### ISSUE TITLE
write a custom cop to prohibit &.

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#596]
The "safe navigation" operator `&.` makes it easier to work with and propagate `nil` values. Lobsters predates it so it was never previously used, but also I don't *want* it to be easy to add and pass around more `nil`s than we already have to. Unfortunately, its use is becoming common, so it's been a distraction in several recent PRs.

Rubocop has [clear instructions for creating a cop](https://github.com/rubocop-hq/rubocop/blob/master/manual/development.md) and its existing [SafeNaviation cop](https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/style/safe_navigation.rb) is probably a great starting point. I believe the [require](https://docs.rubocop.org/en/latest/extensions/) config can load a cop (I really prefer not to maintain a fork of the rubocop repo) but haven't tested.

Bonus points and high praise if you can get `Enforce: not-used` or something added to the official SafeNavigation cop so we're not maintaining anything, but I have no idea what that process is like.

**Comment by tansengming** [comment]
this sounds fun I'll pick it up. I'll try to keep this thread updated as I get it through Rubocop.

**Comment by alanpost** [comment]
Thank you @tansengming.  @hmadison did a mock-up you might find helpful to start with:

```
module RuboCop
  module Cop
    module Style
      # Disallow the safe navigation operator
      #
      # @example
      #   # bad
      #   foo&.bar
      #
      class DisallowSafeNavigation < Cop
        MSG = 'Do not use &.'.freeze

        def on_csend(node)
          add_offense(node)
        end
      end
    end
  end
end
```

If you cared to clarify, improve, or better guide the user in the error message as well as test and put this outline in to a PR that would be phenomenal.

**Comment by tansengming** [comment]
I've got an initial version of this ready at https://github.com/tansengming/rubocop-disallow-safe-navigation/pull/1

I'll be starting a PR on lobsters to get it integrated and we shall see how that goes.

**Comment by tansengming** [comment]
The new custom cop should work with travis with the new configuration at https://github.com/lobsters/lobsters/pull/598 . Note that I had to fix a couple of Rubocop issues to get that PR to pass.

**Comment by pushcx** [comment]
On the bonus part, I meant getting the rubocop project itself to expand the SafeNavigation cop they ship now with a config setting to prohibit use of the SafeNavigation operator.
