### ISSUE TITLE
"Flag" dropdown displays incorrectly when submission is hidden

### ISSUE THREAD

**Issue by sean-public** [lobsters/lobsters#601]
If you are on a submission's comments page and click `hide` and then `flag` on the submission, the resulting dropdown list of flag reasons is cut off by the comment textarea. Screenshot showing only the first line of the "selector widget" is visible:

![image](https://user-images.githubusercontent.com/21961562/49035049-4671cc80-f179-11e8-89ec-90bd8256ceef.png)

Additionally, if you are on a page listing submissions and click `hide` followed by `flag`, the resulting dropdown selector is also transparent and thus very difficult to see/read/use. I observed these on Chrome 70.

![image](https://user-images.githubusercontent.com/21961562/49035135-889b0e00-f179-11e8-9a7a-801c7336fe62.png)

**Comment by pushcx** [comment]
Probably the same basic issue as #432

**Comment by evexoio** [comment]
@pushcx @sean-public I tried to reproduce this bug, but I couldn't find the flag button on my development server.

<img width="593" alt="screen shot 2018-11-27 at 4 09 30 pm" src="https://user-images.githubusercontent.com/12014839/49087155-e7868300-f25e-11e8-85c4-6d8915cbdcf7.png">

How can I reach the flag button?

Thanks :)

**Comment by sean-public** [comment]
@evexoio please see the conditions at https://github.com/lobsters/lobsters/blob/master/app/models/user.rb#L252-L267

**Comment by evexoio** [comment]
How does this look to you guys? I don't have that much of a designer's eye 😂
<img width="772" alt="screen shot 2018-11-27 at 4 59 34 pm" src="https://user-images.githubusercontent.com/12014839/49090203-ee64c400-f265-11e8-947e-556028ed281b.png">

**Comment by sean-public** [comment]
Please reference this issue # in a PR if you want a review and hopefully merge. Thanks!

**Comment by evexoio** [comment]
@sean-public I did not create a PR, I was checking with you if it looks good first :).

Seems like you like it. PR soon.
