### ISSUE TITLE
Use semver as Semantic Versioning Specification

### ISSUE THREAD

**Issue by guillaumebriday** [lobsters/lobsters#618]
Lobsters has reached 2000 stars on Github which is awesome ! 🎉 

Lots of people use lobsters in production and I think it's now necessary to use a versioning specification to prevent bugs in production or breaking changes.

Moreover, versioning specification could be use as Docker image tag and we could add a build in Docker image very easily 👍 

What do you think about it ?

Thank you

cf: https://github.com/lobsters/lobsters/pull/617 and https://github.com/lobsters/lobsters/pull/607

**Comment by alanpost** [comment]
I didn't know we had 2k stars on GitHub.  Neat.

I don't understand how a version specification prevents bugs or breaking changes in production.  Are you suggesting we reorder our commits?  Branch them up and merge them all at once?  Something else?

As it stands I don't see any value modifying our release process to accommodate semantic versioning.   When we deploy a complex change to production we ask for and get feedback from users in #lobsters on Freenode.  That is necessary regardless of the ordering, sequencing, staging, or tagging of a commit.  I do think the recent contributions to testing and style enforcement are and will continue to be an improvement, even if the release process for them caused problems.  I would definitely like to see more contributions like that: It would not surprise me to see more significant feature development and our testing infrastructure will need to keep pace.

I'll close this ticket as unnecessary.  If I've misunderstood something, please write back.  Thank you for the suggestion.
