### ISSUE TITLE
Merged stories don’t display upvotes

### ISSUE THREAD

**Issue by ron-wolf** [lobsters/lobsters#621]
An explication of #424 (#609 is also related). If a comment (from the user or from someone else) is made on a story that ends up getting merged, and a user votes on that comment, the score counter changes regardless of whether the user has already voted that way on the comment. Upon reloading, the voting indicators returns to blank, and the score displays properly according to the most recent action, whether it be performing or undoing a vote. This still allows for the buttons to be pressed and for a vote to be made, if not registered. The issue shows up for me in [this thread](https://lobste.rs/s/addjas/while_we_blink_we_lose_web#c_dbtdoc).

**Comment by evexoio** [comment]
@ron-wolf hey, I can reproduce this issue. I'll push a fix soon.

**Comment by evexoio** [comment]
I just tried to reproduce this locally and couldn't on the latest master.

@pushcx is the lobste.rs running at the latest master?(cc47b785)

can we make sure if this [line](https://github.com/lobsters/lobsters/blob/master/app/controllers/stories_controller.rb#L419) is the same on production?

**Comment by alanpost** [comment]
Good catch Abdullah,

Production is running b23f1064.  I'm sorry about that Ron, we'll get the patch for your issue here deployed as soon as we're able.

**Comment by alanpost** [comment]
@ron-wolf, @pushcx deployed 17bdf34 to production a few minutes ago.  Your issue here should be resolved and I'll close this ticket.  Please write back if you need further help or the latest release hasn't fixed your issue.
