### ISSUE TITLE
'Edit' button seems broken

### ISSUE THREAD

**Issue by colindean** [lobsters/lobsters#624]
When I click `edit` on a comment, I'm presented with the comment's textarea but the comment is not in the textarea.

I'm seeing this on Chrome Version 71.0.3578.98 on macOS 10.14.1 as well as Chrome on Android 9 (latest of both, presumably).

**Comment by alanpost** [comment]
@evexoio, this seems superficially similar to #622.  Would you like to make a patch for it modeled after 93440ce?

**Comment by evexoio** [comment]
@alanpost yes sure, ill look at it now

**Comment by pushcx** [comment]
I 3cc6ff7 reverting the changes to commentbox (probably the most complex form on the site) and things are OK for the moment. After work I can compare the changes to the output side-by-side to figure out what exactly caused this breakage, if @evexoio hasn't solved it already.
