### ISSUE TITLE
Top navigation is too wide to fit

### ISSUE THREAD

**Issue by Carpetsmoker** [lobsters/lobsters#632]
Currently the top navbar looks like this to me, since I reached a triple-digit karma:

![2019-01-03-125125_1685x106_scrot](https://user-images.githubusercontent.com/1032692/50618233-5a69d480-0f56-11e9-9ff4-b8c679cf4086.png)

Which is rather sub-optimal. The right part of the navbar gets pushed down as it's too wide.

---

I'm not sure what the best way to fix this is, but one way would be to shorten "Submit story" to "Submit", and "Your Threads to "Threads", possibly with a tooltip to read the full text?

![2019-01-03-125150_1674x73_scrot](https://user-images.githubusercontent.com/1032692/50618234-5b026b00-0f56-11e9-9993-45998eedea28.png)

This should give plenty of space, even for people with longer usernames.

**Comment by alanpost** [comment]
What device and browser are you using?  I'm asking both because it makes confirming platform issues easier but also to ask "can you make the window wider?"

I get the same behavior (a break in the top navigation regardless of window width) on the [newest stories](https://lobste.rs/newest) page.

**Comment by Carpetsmoker** [comment]
I'm using Firefox on Linux (Arch).

It doesn't really depend on the window width, as the container has a maximum width. Here's a full-screen screenshot:

![2019-01-03-130441_1920x1080_scrot](https://user-images.githubusercontent.com/1032692/50618521-3d360580-0f58-11e9-9a7f-18c6cf0b9e88.png)

---

The reason you get it on "Newest stories" is because it has the longer "Newest Stories" instead of "Lobsters" on the top-left. Shortening that to "Newest" combined with my previous proposals would fix that.

I actually *don't* get the break with most pages, as those have the shorter "Home" instead of "Lobsters" in the top-left, which shortens the entire thing just enough to fit. However, if I add just one character to my username in the web inspector it doesn't fit again.

**Comment by alanpost** [comment]
Perfect, thank you.

I'd rather not shorten or otherwise abbreviate the labels preferring instead to increase or adjust the container size.  I'd like top navigation to fit on a single line, however.

**Comment by hmadison** [comment]
#580 Describes the same issue too.

**Comment by pushcx** [comment]
Closing in favor of #580, yeah.
