### ISSUE TITLE
Impossible to delete account

### ISSUE THREAD

**Issue by srid** [lobsters/lobsters#636]
## Repro 

1. Go to 'Delete Account' in https://lobste.rs/settings
1. Enter your password and check "I am sure" box.
1. Click "Yes, Delete My Account"

## Bug

You will see `You did not check the "I am sure" checkbox` error message box with red background, viz.:

![image](https://user-images.githubusercontent.com/3998/52052799-8c824c80-257d-11e9-930b-c39e11157203.png)

## Environment

ChromeOS

**Comment by pushcx** [comment]
I'm back from some travel and deployed a fix for this.
