### ISSUE TITLE
Unused selector, maybe more?

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#640]
In [this issue comment](https://github.com/lobsters/lobsters/issues/639#issuecomment-463620051) I noticed that the `table.thread` selector is dead; it's unlikely to ever have been used. Anyone have a minute to remote it and related selectors? Extra credit if you take a look through the main + mobile stylesheets for other dead rules, but a PR just for these would be appreciated.

**Comment by pushcx** [comment]
Well, that PR removes `.thread`, can anyone find more dead style code, or confirm that was it?

**Comment by bovarysme** [comment]
Hi,

I went ahead and tried to find all unused CSS selectors. My methodology was as follows:
- Using Chrome's CSS code coverage tool, I exported one JSON report per page browsed.
- I wrote a small [Python script](https://gist.github.com/bovarysme/6a6b339bd81c8f0713794c1d4b695596#file-coverage-py) to merge the exported data and output a CSS file containing unseen rules.
- Using GitHub's search, I removed from the file valid rules not encountered while browsing the site (e.g. related to the mod views).

This yielded the following CSS file, containing rules that have a high chance of being unused: [output.css](https://gist.github.com/bovarysme/6a6b339bd81c8f0713794c1d4b695596#file-output-css). Would you mind going through them to double check this is the case? I'd be happy to open a PR afterwards.

**Comment by pushcx** [comment]
Wow! That's a thorough approach, please do open a PR. I don't recognize these rules and the ones I spot-checked (`field_with_errors`, `#header h1`, `img#party_hat`) all look to be dead. Great to have this.
