### ISSUE TITLE
Direct links to comments in a collapsed thread do not automatically unfurl that thread.

### ISSUE THREAD

**Issue by ChadSki** [lobsters/lobsters#643]
For example, this direct link to [my comment](https://lobste.rs/s/dkqmvi/there_s_no_good_reason_trust_blockchain#c_ollekl). If I manually unfurl the thread and scroll down, my comment is correctly highlighted.

**Comment by pushcx** [comment]
Getting to collapsed comments and their replies is deliberately inconvenient.
