### ISSUE TITLE
Homepage field?

### ISSUE THREAD

**Issue by Carpetsmoker** [lobsters/lobsters#669]
What are the thoughts on adding a homepage field for users?

Right now you can already put a link in your profile description, but the advantage of a separate field would be that we can add [rel="me"](http://microformats.org/wiki/rel-me), which can be an alternative to e.g. Keybase. It was mentioned by some people in the Keybase discussion; I had never heard of it before, but turns out many services actually add rel="me" (e.g. Twitter, GitHub, etc.) to home page links.

Should be easy to do, and I'll gladly make a PR. Just wanted to check in first to see if there are any objections.

Thanks!

**Comment by pushcx** [comment]
Sounds good. Please stick it in the User model's `typed_store :settings`.
