### ISSUE TITLE
Merged story visible while not logged in

### ISSUE THREAD

**Issue by girst** [lobsters/lobsters#678]
Looking at the current top story (the Firefox bug) when logged out, I can see both the bugzilla and the update link on the front page. When logged in, the secondary link (the update in this case) is hidden.

I've attached a screen shot to demonstrate this.
![lobsters-merged-stories-bug](https://user-images.githubusercontent.com/11820748/57184050-fbd14a80-6ea4-11e9-8c85-d761f57d1cb6.png)

**Comment by pushcx** [comment]
Oof, tough bug. Though it runs the other direction - we should always be showing a single link on any page listing multiple stories, regardless of whether someone is logged in or not.

**Comment by girst** [comment]
Oh, I actually liked this (multi-link) behaviour. It's hard to tell when 
stories get merged otherwise.

**Comment by pushcx** [comment]
It's supposed to be. Merging exists because we don't want dupes and hot takes to get special prominence.
