### ISSUE TITLE
strange keybase information in public profile view for self

### ISSUE THREAD

**Issue by NattyNarwhal** [lobsters/lobsters#691]
When I view my own profile (`/u/calvin`), I get a strange message about Keybase (I don't have it) like this:

![weird lobsters](https://user-images.githubusercontent.com/3161292/59481969-1819bd00-8e3d-11e9-8bce-05e36166497c.PNG)

For others' public profiles, I get a whitespace line where this would be - not odd at first glance, but noticeable.

**Comment by pushcx** [comment]
Yeah, this is the Keybase integration we [recently added](https://github.com/lobsters/lobsters/pull/661). I'll move it to the /settings page with the other integrations, hopefully at lunch today. I didn't totally get the flow for it during the PR or I'd have asked for it to be done then.

**Comment by pushcx** [comment]
Fixed.
