### ISSUE TITLE
Predictable comment URLs?

### ISSUE THREAD

**Issue by grxnola** [lobsters/lobsters#708]
It could be a useful feature to have predictable URLs for a story's comment section. That way, an author who knows they're going to submit a story to lobsters would be able to preemptively provide a link to the comments on that post.

I'm no Rubyist so I don't feel confident making a modification to such a well-tested and spec'd codebase, but from what I can gather the change would involve making this call to `:assign_short_id_and_upvote` do something else, maybe `:hash_URL_and_upvote`?
https://github.com/lobsters/lobsters/blob/f0549673b447bba97553c346efdaf71f5194c4e0/app/models/story.rb#L145

**Comment by pushcx** [comment]
I'll take the "well-tested" compliment, even if I'm not so sure we've earned it. :)

What's the value here? We'd have to do work to replace hash generation, authors would have to know we have this proprietary scheme and implement a version themselves, and the time saved of editing a link into a post after submitting is not very high. (There's also some corner cases like that URLs can be submitted multiple times.)

How about a GET route like `lobste.rs/stories/latest_submission?url=(blog post url here)` that 302s to the latest time that URL has been submitted? That might solve the problem without much work on either side. Though how would we make sure authors knew about the functionality?

**Comment by pushcx** [comment]
Been a month and nobody's too interested, so I'm closing to reduce clutter. We can reopen if someone wants to champion this.
