### ISSUE TITLE
CSS problem: "has been merged into this story" banner is hard to read

### ISSUE THREAD

**Issue by winks** [lobsters/lobsters#712]
I just visited https://lobste.rs/s/2kfdhh/netbsd_9_0_release_process_has_started and (only on the first visit?) I got a green banner saying `"netbsd-9 branch has been created (Welcome to NetBSD 9.99.1)" has been merged into this story."`

Sadly I forgot to take a screenshot, but it was black on not-so-light green with a text-shadow and it was very hard to read.

Yes, this is not a PR, I know. Maybe someone who works on the code base could have a quick look and maybe lighten the green a little, or get rid of the text-shadow to improve the contrast a bit and make it more readable. 
(In my personal opinion the banner doesn't really match the rest of the site design, but this is highly subjective, so feel free to ignore this addendum.)

**Comment by arp242** [comment]
Similar: https://github.com/lobsters/lobsters/pull/668

**Comment by alanpost** [comment]
I was the one that merged these this morning.  I wonder if you fetched it right as I was doing that, or if the problem you're revorted persists in some manner afterward.

**Comment by winks** [comment]
Ah, didn't see this, thanks @arp242 - but I got the green one just earlier, 5min before I posted.

**Comment by pmueller** [comment]
Here's a screenshot for reference:
<img width="975" alt="lobsters-merge-flash" src="https://user-images.githubusercontent.com/780509/62296321-d2d93b00-b43c-11e9-9256-6d00e85b2b34.png">

I agree it's hard to read and should get a lighter green background

**Comment by pmueller** [comment]
I took a stab at making it easier to read, here's the after screenshot:
<img width="936" alt="lobsters-merge-flash2" src="https://user-images.githubusercontent.com/780509/62300326-94477e80-b444-11e9-90c9-efe394af9f71.png">

**Comment by pushcx** [comment]
For anyone reading: visit https://lobste.rs/s/6wcisb to see this message.

**Comment by pushcx** [comment]
This was fixed in #713
