### ISSUE TITLE
how do i change the logo?

### ISSUE THREAD

**Issue by chovy** [lobsters/lobsters#719]
It looks like the lobster logo is an inline image data url. How do I modify it?

**Comment by alanpost** [comment]
@chovy,

You have already been told in #718 that this ticket system is for the site running on https://lobste.rs/ and is not forum for help configuring your own Lobsters instance.  Just like the previous ticket you filed, your question here pertains to running your own Lobsters instance and is off-topic.  You have already been told how to get help.

Cease using the ticket system as you have been here (#719) and in #718.
