### ISSUE TITLE
bug if some wag tries to reset the password of inactive-user

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#721]
If someone enters the username/email of `inactive-user` into the form for resetting a forgotten password, it throws a 500 because the username is reserved. This doesn't need to give a useful error message, it could claim to succeed without doing anything, but it's a bug if it throws 500s.

```
  Validation failed: Username is not permitted
  app/models/user.rb:430:in `initiate_password_reset_for_ip'
```

**Comment by pmueller** [comment]
It should be noted that [the same validation](https://github.com/lobsters/lobsters/blob/845bd7db73b637ef65cca6b79a6678a427f8cdbd/app/models/user.rb#L92) will cause 500 errors on many actions that operate on a user, if that user has a username that's reserved (like `inactive-user`). Actions like enabling/disabling invitations for a user, granting moderatorship, or anything else that calls `save!` on the user.

The validation is also currently preventing the `inactive-user` user account from being created by `rake db:seed`: https://github.com/lobsters/lobsters/blob/845bd7db73b637ef65cca6b79a6678a427f8cdbd/db/seeds.rb#L2

**Comment by pushcx** [comment]
Ouch, I didn't realize `seeds` was broken for 14 months, that's no good. That definitely needs to get fixed as well, even if it's as simple as `validate: false`.

The other things... I'm OK with them being broken because they'll only happen if the admin does them (and would be very odd to do), but they imply that this isn't the right strategy to protect the `inactive-user` name. Maybe someone sees a much better strategy?
