### ISSUE TITLE
Rails 6 Post Upgrade

### ISSUE THREAD

**Issue by thomasdziedzic** [lobsters/lobsters#724]
Enable the following in `config/initializers/new_framework_defaults_6_0.rb`:

- [x]  # Rails.application.config.action_view.default_enforce_utf8 = false
- [ ]  # Rails.application.config.action_dispatch.use_cookies_with_metadata = true
- [ ]  # Rails.application.config.action_dispatch.return_only_media_type_on_content_type = false
- [x]  # Rails.application.config.active_job.return_false_on_aborted_enqueue = true
- [x]  # Rails.application.config.active_storage.queues.analysis = :active_storage_analysis
- [x]  # Rails.application.config.active_storage.queues.purge    = :active_storage_purge
- [x]  # Rails.application.config.active_storage.replace_on_assign_to_many = true
- [ ]  # Rails.application.config.action_mailer.delivery_job = "ActionMailer::MailDeliveryJob"
- [ ]  # Rails.application.config.active_record.collection_cache_versioning = true

# After upgrades

- [ ] Update https://github.com/lobsters/lobsters/blob/441786e4c1b37ae7e78f6dbd9d6256678b950acb/config/application.rb#L27 to 6.0 and remove upgrade file.

**Comment by jcs** [comment]
Is this still relevant now that the project is on Rails 7?

**Comment by pushcx** [comment]
No, these defaults were all adopted. Thanks for noticing the stale issue.
