### ISSUE TITLE
Extract 'domain' model from Story

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#734]
The `Story` model has a `domain` method extracts the domain from a url. We're increasingly wanting a `Domain` model that `Story` can have a foreign key to for quicker searching, analytics, and feedback at story submit time.

So we'll need a migration to add the table (with a single not-null string column `name`) and add the FK for all existing stories. `Story#url=` can `find_or_create_by!` the association for new stories. As in `Story.find_similar_by_url`, it should normalize case and remove a leading `www.` Then tests for submitting a story with a never-seen before domain, a seen-before domain, and editing a story to change the URL.

**Comment by emrox** [comment]
Should the domain be split into subdomain and domain or just the whole hostname?

f.e. for medium there could be
```
{ subdomain: 'mypage', name: 'medium.com' }
```

or it could be just

```
{ hostname: 'mypage.medium.com' }
```

**Comment by pushcx** [comment]
I'd rather have a single field, it'll make the basic features a lot easier to build on top of. I know it won't capture aggregators like Medium.com and Dev.to well, but they're already pretty iffy on quality.

**Comment by emrox** [comment]
When it's just one field maybe just add a `domain` row to the `Story` model?

**Comment by pushcx** [comment]
I don't remember a compelling reason to have a separate `Domain` model if we use Rails 5's attributes API to extract an object for it to centralize that code a bit. Joins to look at flags by domain are going to wind up touching `stories` anyways. Not sure what I was thinking here.

**Comment by pushcx** [comment]
This was completed a little while ago.
