### ISSUE TITLE
CSP error on comments

### ISSUE THREAD

**Issue by comzeradd** [lobsters/lobsters#736]
Not able to post comment anymore, probably due to 57cf63d3728b15459128ebf04409ef32a4cc7be0.

From two different browsers:

`Content Security Policy: The page’s settings blocked the loading of a resource at https://lobste.rs/comments (“default-src”).`

`Refused to connect to https://lobste.rs/comments because it appears in neither the connect-src directive nor the default-src directive of the Content Security Policy.`

**Comment by thomasdziedzic** [comment]
Sorry about that, @pushcx reverted the csp change at https://github.com/lobsters/lobsters/pull/737 so commenting should be good again. I'll keep this pr open to diagnose the issue.
