### ISSUE TITLE
It's possible to vote on/hide merged stories

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#739]
Users submit stories Alpha and Beta. Alice loads Beta. Mary the Moderator merges Beta into Alpha because it's a dupe. Alice reads her tabs and upvotes Beta because she likes it. Alice has now voted on a merged story, which she shouldn't be able to do. StoriesController needs to prevent users from voting/hiding/saving(/anything else?) stories that are merged into another story.

**Comment by eloydegen** [comment]
I do understand that Alice shouldn't be able to upvote both Beta and Alpha when they are merged, but shouldn't Alice be able to upvote only Beta? If she never opens Alpha, her vote won't have effect on that subject. 

And if so, should there be any visual to show the upvote doesn't count, or should it just be discarded on the back-end?

**Comment by pushcx** [comment]
I merged 4io's fix to just silently drop Alice's upvote of Beta. Maybe in the future we want to refactor Story to extract a Link/Text from it, a lot of these issues seem to be caused by the self-referential join.
