### ISSUE TITLE
database_consistency

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#745]
I ran the [database_consistency](https://github.com/djezzzl/database_consistency) gem to look for issues. I'm not committing it to the `development` group in the `Gemfile` because took a little fiddling to get running, but the output looks correct.

If anyone would like to write migrations/validations to deal with one or more of these, they'd be some nice little improvements in reliability.

 - [x] fail Comment short_id column has limit in the database but do not have length validator
 - [x] fail Comment comment column is required in the database but do not have presence validator
 - [ ] fail Comment comment column has limit in the database but do not have length validator
 - [x] fail Comment markeddown_comment column has limit in the database but do not have length validator
 - [x] fail Hat hat column is required in the database but do not have presence validator
 - [x] fail Hat hat column has limit in the database but do not have length validator
 - [x] fail Hat link column has limit in the database but do not have length validator
 - [x] fail HatRequest hat column has limit in the database but do not have length validator
 - [x] fail HatRequest link column has limit in the database but do not have length validator
 - [x] fail HatRequest comment column has limit in the database but do not have length validator
 - [x] fail Invitation email column has limit in the database but do not have length validator
 - [x] fail Invitation code column has limit in the database but do not have length validator
 - [x] fail Invitation memo column has limit in the database but do not have length validator
 - [x] fail InvitationRequest code column has limit in the database but do not have length validator
 - [x] fail InvitationRequest email column has limit in the database but do not have length validator
 - [x] fail InvitationRequest name column has limit in the database but do not have length validator
 - [x] fail InvitationRequest memo column has limit in the database but do not have length validator
 - [x] fail InvitationRequest ip_address column has limit in the database but do not have length validator
 - [ ] fail Keystore key column has limit in the database but do not have length validator
 - [ ] fail Message short_id column has limit in the database but do not have length validator
 - [ ] fail ModNote note column has limit in the database but do not have length validator
 - [ ] fail ModNote markeddown_note column is required in the database but do not have presence validator
 - [ ] fail ModNote markeddown_note column has limit in the database but do not have length validator
 - [ ] fail Moderation action column has limit in the database but do not have length validator
 - [ ] fail Moderation reason column has limit in the database but do not have length validator
 - [ ] fail ReplyingComment user_id column is required in the database but do not have presence validator
 - [ ] fail ReplyingComment story_id column is required in the database but do not have presence validator
 - [ ] fail ReplyingComment comment_created_at column is required in the database but do not have presence validator
 - [ ] fail ReplyingComment comment_author_id column is required in the database but do not have presence validator
 - [ ] fail ReplyingComment story_author_id column is required in the database but do not have presence validator
 - [ ] fail ReplyingComment current_vote_reason column has limit in the database but do not have length validator
 - [ ] fail Story short_id column has limit in the database but do not have length validator
 - [ ] fail Story markeddown_description column has limit in the database but do not have length validator
 - [ ] fail Story story_cache column has limit in the database but do not have length validator
 - [ ] fail Story twitter_id column has limit in the database but do not have length validator
 - [ ] fail SuggestedTitle title column has limit in the database but do not have length validator
 - [ ] fail User username column has limit in the database but do not have length validator
 - [ ] fail User email column has limit in the database but do not have length validator
 - [ ] fail User password_digest column has limit in the database but do not have length validator
 - [ ] fail User password_reset_token column has limit in the database but do not have length validator
 - [ ] fail User session_token column has limit in the database but do not have length validator
 - [ ] fail User about column has limit in the database but do not have length validator
 - [ ] fail User rss_token column has limit in the database but do not have length validator
 - [ ] fail User mailing_list_token column has limit in the database but do not have length validator
 - [ ] fail User banned_reason column has limit in the database but do not have length validator
 - [ ] fail User disabled_invite_reason column has limit in the database but do not have length validator
 - [ ] fail User settings column has limit in the database but do not have length validator
 - [ ] fail Vote vote column is required in the database but do not have presence validator
 - [ ] fail Vote reason column has limit in the database but do not have length validator
 - [x] fail HatRequest hat column should be required in the database
 - [x] fail HatRequest link column should be required in the database
 - [x] fail HatRequest comment column should be required in the database
 - [x] fail InvitationRequest name column should be required in the database
 - [x] fail InvitationRequest email column should be required in the database
 - [ ] fail Message author model should have proper foreign key in the database
 - [ ] fail ReplyingComment comment model should have proper foreign key in the database
 - [x] fail User lower(email) model should have proper unique index in the database
 - [x] fail User lower(username) model should have proper unique index in the database
 - [ ] fail User sent_messages associated model should have proper index in the database
 - [ ] fail User moderations associated model should have proper index in the database

**Comment by magikid** [comment]
Wow. That is a lot of issues. I'm going to try tackling these this week:

- fail Comment short_id column has limit in the database but do not have length validator
- fail Comment comment column is required in the database but do not have presence validator
- fail Comment comment column has limit in the database but do not have length validator
- fail Comment markeddown_comment column has limit in the database but do not have length validator
- fail Hat hat column is required in the database but do not have presence validator
- fail Hat hat column has limit in the database but do not have length validator
- fail Hat link column has limit in the database but do not have length validator
- fail HatRequest hat column has limit in the database but do not have length validator
- fail HatRequest link column has limit in the database but do not have length validator
- fail HatRequest comment column has limit in the database but do not have length validator

**Comment by pushcx** [comment]
Just realized this probably dupes some/all of #722.

**Comment by magikid** [comment]
I don't think so. It looks like all of the issues in this ticket are constraints in the database that aren't in the models where #722 is validations in the models that aren't in the database.

**Comment by pushcx** [comment]
Updated the checkmarks for the work @magikid did in #749.

**Comment by AminArria** [comment]
Hi, I'm gonna do:
- fail Invitation email column has limit in the database but do not have length validator
- fail Invitation code column has limit in the database but do not have length validator
- fail Invitation memo column has limit in the database but do not have length validator
- fail InvitationRequest code column has limit in the database but do not have length validator
- fail InvitationRequest email column has limit in the database but do not have length validator
- fail InvitationRequest name column has limit in the database but do not have length validator
- fail InvitationRequest memo column has limit in the database but do not have length validator
- fail InvitationRequest ip_address column has limit in the database but do not have length validator

**Comment by mauricew** [comment]
I can do these:

* fail Story short_id column has limit in the database but do not have length validator
* fail Story markeddown_description column has limit in the database but do not have length validator
* fail Story story_cache column has limit in the database but do not have length validator
* fail Story twitter_id column has limit in the database but do not have length validator

* fail User username column has limit in the database but do not have length validator
* fail User email column has limit in the database but do not have length validator
* fail User password_reset_token column has limit in the database but do not have length validator
* fail User session_token column has limit in the database but do not have length validator
* fail User about column has limit in the database but do not have length validator
* fail User rss_token column has limit in the database but do not have length validator
* fail User mailing_list_token column has limit in the database but do not have length validator
* fail User banned_reason column has limit in the database but do not have length validator
* fail User disabled_invite_reason column has limit in the database but do not have length validator
* fail User settings column has limit in the database but do not have length validator

* fail Vote vote column is required in the database but do not have presence validator
* fail Vote reason column has limit in the database but do not have length validator

**Comment by svintbel** [comment]
- [ ]  fail User lower(email) model should have proper unique index in the database
- [ ]  fail User lower(username) model should have proper unique index in the database


Seems MySQL indexes are already case-insensitive for these columns as we using `collation: "utf8mb4_general_ci"` in our db schema, if not, resolving these issues require using SQL statements to add functional indexes like
```ruby
execute "CREATE INDEX ind_usernames_on_lowercase_username ON users USING (lower(username);"
```
which are not supporting by [ruby-style AR schema](https://guides.rubyonrails.org/active_record_migrations.html#types-of-schema-dumps) and should to set :sql format for db schema. 
So, resolving these issues will be unuseful.

**Comment by svintbel** [comment]
I'll try to do:

- [ ]  fail Keystore key column has limit in the database but do not have length validator
- [ ]  fail Message short_id column has limit in the database but do not have length validator
- [ ]  fail ModNote note column has limit in the database but do not have length validator
- [ ]  fail ModNote markeddown_note column is required in the database but do not have presence validator
- [ ]  fail ModNote markeddown_note column has limit in the database but do not have length validator
- [ ]  fail Moderation action column has limit in the database but do not have length validator
- [ ]  fail Moderation reason column has limit in the database but do not have length validator

===================================================


- [ ]  fail Message author model should have proper foreign key in the database
- [ ]  fail ReplyingComment comment model should have proper foreign key in the database
- [ ]  fail User sent_messages associated model should have proper index in the database
- [ ]  fail User moderations associated model should have proper index in the database

**Comment by AminArria** [comment]
Doing:
- fail ReplyingComment user_id column is required in the database but do not have presence validator
- fail ReplyingComment story_id column is required in the database but do not have presence validator
- fail ReplyingComment comment_created_at column is required in the database but do not have presence validator
- fail ReplyingComment comment_author_id column is required in the database but do not have presence validator
- fail ReplyingComment story_author_id column is required in the database but do not have presence validator
- fail ReplyingComment current_vote_reason column has limit in the database but do not have length validator

**Comment by AminArria** [comment]
@pushcx from what I gather `ReplyingComment` is a view so it wouldn't need any validator or foreign key in the DB.

So we can mark those as solved right?

**Comment by AminArria** [comment]
On #775 I tackled:
- fail HatRequest hat column should be required in the database
- fail HatRequest link column should be required in the database
- fail HatRequest comment column should be required in the database
- fail InvitationRequest name column should be required in the database
- fail InvitationRequest email column should be required in the database

This overlaps almost completely with #722

**Comment by yaaase** [comment]
Are any of these remaining? I am happy to address the rest.
