### ISSUE TITLE
Hacktoberfest!

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#747]
Hello, hacktoberfesters!

We'd love to have your contributions, please check out: https://lobste.rs/s/hvgmsx/hacktoberfest_lobsters_edition

**Comment by nickhammond** [comment]
@pushcx I noticed the `hacktoberfest` topic isn't on this repository but it does come up in a few directories, is this repository still participating? 

<img width="1084" alt="image" src="https://github.com/lobsters/lobsters/assets/17698/ad4e15a0-d3e8-4f01-808f-1a5831a3e887">

**Comment by pushcx** [comment]
Sure, worth a try. I've added the `hacktoberfest` tag to the project.

I'm going to close out this issue, though - no reason for it to be hanging out open after years. :)
