### ISSUE TITLE
More of a question than an issue but does the site have an API?

### ISSUE THREAD

**Issue by Uzay-G** [lobsters/lobsters#757]
Just wondering because it could be useful for a project I am working on. 
edit:
I noticed this issue but there aren't any docs or anything to understand: https://github.com/lobsters/lobsters/issues/42

Edit: 
Oh ok I'm figuring it out.
I can do a documentation for the API if the repo owners would like. Where would you like me to put it?
Thanks

**Comment by pushcx** [comment]
Some of the site is accessible through RSS or JSON, but there's no formal API because it'd be a bunch of extra work to maintain. I appreciate you offering to document the API, but I'd prefer not to imply features or stability for people who code against it.
