### ISSUE TITLE
Sharing on Twitter and certain tags (i.e. c++)

### ISSUE THREAD

**Issue by tomekw** [lobsters/lobsters#788]
Hi,

I've noticed that certain tags, i.e. `c++`, are shared on Twitter as `#c++` which erases to just `#c`. I would be willing to fix that by adding a tag rewriter so such tag would be translated to `#cpp` before sharing. What do you think? 🤔

**Comment by pushcx** [comment]
Oh, what an odd bug. Yes, if we can't get Twitter to stop deleting the plusses (maybe this is just a url encoding bug?) then we should find another way to represent them. Could you elaborate on what you mean by a rewriter?

**Comment by tomekw** [comment]
That's how the tag looks on Twitter:

<img width="337" alt="Zrzut ekranu 2019-12-2 o 09 21 23" src="https://user-images.githubusercontent.com/198371/69942900-3192ec00-14e5-11ea-8dd4-9e8b8fd1b700.png">

The super quick code to demonstrate the solution would be:

```ruby
tag_rewrite_rules = {
  "c++" => "cpp"
}

tags.map { |tag| tag_rewrite_rules.fetch(tag) { tag }.prepend("#") }
```

Something like that ;) WDYT?

**Comment by tomekw** [comment]
Also, rust should become #rustlang and go #golang :)

**Comment by pushcx** [comment]
We declined to pay Twitter to give them interesting links and discussion, so this bug has been dead for ~6 months.
