### ISSUE TITLE
has_many relation ship should have destroy dependent

### ISSUE THREAD

**Issue by jwjwyoung** [lobsters/lobsters#789]
We found it's possible to create some invalid data due to the non-tight has_many relationship. 

In https://github.com/lobsters/lobsters/blob/3f1d498a7c5110ca53c9fd7fc3cd73240c5c5240/app/models/story.rb#L30, the has_many relationship has no dependent at all, which means deleting story will not deleted its associated votes. 

But in votes.rb, there is `belongs_to :story, optional: false`
https://github.com/lobsters/lobsters/blob/3f1d498a7c5110ca53c9fd7fc3cd73240c5c5240/app/models/vote.rb#L3
which means that for each vote, they should be associated with a story. 

So when a story is deleted, its votes all become invalid data in the applications. 

The solution would be has_many :votes, dependent: :destroy.

**Comment by pushcx** [comment]
We don't delete stories from the database. if you use the usual interface they're marked with the `is_expired` flag.
