### ISSUE TITLE
Story submissions strip 'friends link' code from medium stories

### ISSUE THREAD

**Issue by enkiv2** [lobsters/lobsters#791]
When submitting a medium URL with a 'friends link' code, lobste.rs strips that code (seemingly because it has been miscategorized as a tracking code). Since this code is a method provided to authors to allow bypassing the paywall, this means that the posts get erroneously paywalled due to overzealous URL cleaning.

The code looks like `?sk=249f4cb0c3964e85f1424d25f1c168a9`, and is appended to the URL.

**Comment by pushcx** [comment]
Do you have any documentation for this? I couldn't find any when I was trying to identify these parameters.

Also: that's a _lot_ of entropy for something that could be controlled entirely server-side, a bit on the article table saying the it shouldn't be paywalled. Can there be many codes per post so authors can use them to separate out distribution channels? Does Medium use them to track something? Why is it a url parameter at all?

**Comment by enkiv2** [comment]
It's distinct from "undistributed" articles (which aren't paywalled at all,
& this is done by some internal flag). The friends link is unique per story
& allows bypassing paywall on otherwise paywalled articles (much like the
token that allows arbitrary people to see private documents on google docs).

I'll try to dig up docs, but it's not an api per-se so there might not be
technical docs.

There's tracking only in a very loose sense: the stats page shows a count
for clicks to the friends link for a story alongside clicks for logged-in
users & all views. It can't be much more granular since it's unique per
story. It may be internally correlated with referer, but that data is not
presented to authors.

Whitelisting the 'sk' attribute on domain medium.com will fix the issue
most of the time, & whitelisting the 'sk' attribute in general will solve
it across the board at the risk of letting some tracking codes through on
non-medium sites that have decided to specifically target tracking lobste.rs
users (which seems like an awfully strange threat model).

**Comment by enkiv2** [comment]
This seems to be the extent of official documentation on this feature:
https://help.medium.com/hc/en-us/articles/360006543813-Friend-Links -- no
technical details, & it doesn't even specify the attribute name.

**Comment by pushcx** [comment]
Closing - this is undocumented, has way too much entropy for what it claims to do, expires (anecdotes say a week or two), and [is reported to no longer work at all](https://medium.com/the-partnered-pen/sharing-the-friend-link-no-longer-allows-friends-to-read-for-free-9a04e150850f).
