### ISSUE TITLE
Domain query seems broken

### ISSUE THREAD

**Issue by phikal** [lobsters/lobsters#798]
It seems the _filter by domain_ feature is broken. When clicking on the greyed-out domain name next to an article, such as `nullprogramm.com`, I was given [this page](https://lobste.rs/search?order=newest&q=domain:nullprogram.com), that as of now, looks like this:

![Screenshot_2019-12-29 Lobsters](https://user-images.githubusercontent.com/6370419/71556905-12c93c00-2a36-11ea-992c-d48bd2efe18c.png)

**Comment by gustafe** [comment]
Apparently spam mitigation:

https://twitter.com/lobsters/status/1210399640618704896

**Comment by pushcx** [comment]
Yep, it was broken. I've reverted it now that things have quieted down.
