### ISSUE TITLE
Lobste.rs website takes several minutes to load

### ISSUE THREAD

**Issue by cnst** [lobsters/lobsters#799]
It takes several minutes to load lobste.rs on some connections.  This would be 100% reproducible on certain networks in conditions where Happy Eyeballs practice is not in place, and IPv4 is preferred over IPv6, because IPv4 connection attempts are silently dropped by lobste.rs without any indication of the drop taking place.

This has been partially discussed over at https://twitter.com/pushcx/status/1212089737969684485 and Issue #797.  If #797 is given as the reason for the necessity of the block, it would seem that doing `block drop` instead of `block return` (where an RST packet is returned immediately, making the client retry over IPv6 right away, without having to wait for any timeout timers to expire) is a measure that may be overly aggressive for the circumstances at hand.

It would seem that doing `block drop` on a public website like that is also not a very nice thing to do in general, as it causes legitimate users to experience unnecessary frustration with their connection being slow.

The immediate solution would be to return `RST` packets when incoming connections are blocked (this is called `block return` in OpenBSD PF).  I couldn't find the nginx config file for the website in this repo, but I would also suggest to implement this rate-limiting on the proxy layer, where a cached version of the site could always be returned even for those clients and networks that are rate-limited, a successful authentication could be used to bypass the limiting, and an appropriate error message could be displayed (or even just `return 444`) in cases where the connection has to be dropped.  I'd be happy to help with such nginx configuration if there's any interest.

**Comment by alanpost** [comment]
> some connections.

> certain networks.

Which IPv4 address/network are you personally experiencing slow page loads?

**Comment by cnst** [comment]
> > some connections.
> 
> > certain networks.
> 
> Which IPv4 address/network are you personally experiencing slow page loads?

Which IP addresses/networks do you block drop?

**Comment by alanpost** [comment]
If you would like help, please answer the question.  Feel free to PM me the answer if you'd like.  Otherwise I'll close this ticket.  I do appreciate you pointing out we missed the IPv6 address.  I'll add those to the block list as I'm able.

**Comment by cnst** [comment]
> I do appreciate you pointing out we missed the IPv6 addresses. I'll add those to the block list as I'm able.

Wait, so, you're `block-drop`'ing just for the sake of it, preemptively?  Without the underlying addresses or subnets being problematic in any way?  Else, why are you suggesting you'll be blocking IPv6 if seemingly they're causing no issues for the server?  (Or, if they do, yet the server is still seemingly fine, why `block drop`?)

You do realise you're basically shadowbanning random people here; bypassing the moderation log; in direct violation of the primary reason for why @jcs made Lobsters.

I think list of the blocked subnets and/or addresses should be made public, especially as it seems like a whole bunch of unrelated subnet were blocked, not just a few individual addresses or user-agents or whatnot.
