### ISSUE TITLE
lobste.rs/rss broken?

### ISSUE THREAD

**Issue by haroldcarr** [lobsters/lobsters#806]
Is the RSS working?

My feed reader (BazQux) quit seeing updates about a week or two ago.

So I deleted it from my reader and then added https://lobste.rs/rss back to my reader, but then it times out trying to subscribe.

**Comment by magikid** [comment]
I'm unable to reproduce this issue.  I signed up with BazQux and was able to successfully subscribe.  The latest article from lobsters is also showing at the top of the feed for me.

I recommend emailing their support here: https://bazqux.uservoice.com/

**Comment by haroldcarr** [comment]
the feed started working again (I didn't do anything) yesterday (or maybe the day before).

**Comment by pushcx** [comment]
We haven't had any 500s in a while, so I lean towards this being an issue with BazQux. If you see it again, please ask them for more debugging info - the timestamp of a request and an error message would be useful.
