### ISSUE TITLE
After merging a non-submitter authored story in to a submitter authored story, both stories are "authored by."

### ISSUE THREAD

**Issue by alanpost** [lobsters/lobsters#809]
I merged story bysh8c in to story dwugf8.   Story dwugf8 was authored by the story submitted, and has the "user_is_author" field set to true, whereas story bysh8c has the "user_is_author" field set to false:

    MariaDB [lobsters]> select user_is_author, short_id from stories where short_id in ("bysh8c", "dwugf8");
    +----------------+----------+
    | user_is_author | short_id |
    +----------------+----------+
    |              0 | bysh8c   |
    |              1 | dwugf8   |
    +----------------+----------+

In the display of the merged stories, both are "authored by":

authored by Yogthos (story bysh8c)
authored by paroneayea (story dwugf8)

Story bysh8c in the merged dwugf8 should say "via" rather than "authored by," matching the display as if the stories were not merged, or when stories without the user_is_author field set are merged (e.g., qqlkk0).

**Comment by emmahyde** [comment]
I spent a few hours getting familiar with the repo and wrote a couple of unit tests in `story_spec.rb`. As of right now, I'm unable to reproduce this error. Steps taken: 
1. I booted the app and populated it with the fake data from the README. 
2. I created the test/test user (`test`).
3. I had that user `test` write a post with `user_is_author` turned on (bypassing `is_new?` checks for the sake of the end-to-end test by setting created_at manually).
4. I had another user (`inactive-user`) write a different post with `user_is_author` turned off.
5. Using the UI, I performed a merge using the first post's shortcode.
Here is a screenshot of the local db after my initial testing:

<img width="606" alt="Screen Shot 2021-03-15 at 5 55 24 AM" src="https://user-images.githubusercontent.com/8183738/111135482-18377700-8553-11eb-9af8-89a34623bf34.png">

And here is a screenshot of the post after completion of steps:

![Screen Shot 2021-03-15 at 5 51 53 AM](https://user-images.githubusercontent.com/8183738/111135537-28e7ed00-8553-11eb-9140-af81e4ab56f4.png)

Obviously I'd be happy to push these tests up for extra protection against this type of thing going forward, but was anyone else able to reproduce this?

**Comment by emmahyde** [comment]
The relevant tests written are on fork+branch `emmahyde/lobsters/809/via-authored-by`. No PR is open because its unclear if we want to take this any further!

Hard link: 
https://github.com/emmahyde/lobsters/blob/809/via-authored-by/spec/requests/stories_spec.rb#L135-L173
