### ISSUE TITLE
Ruby SVG library?

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#818]
Research question for contributors: is there a good library to spit out SVG charts? Specifically, I'd like to output scatterplot and line charts. (Though also I read [Tufte](https://en.wikipedia.org/wiki/Edward_Tufte) at an impressionable age and would love to have more power.) We don't serve js to logged-out users and I'd rather not start, so sending data to a client-side library is a nonstarter.

Purposes:
 * vanity stats like number of users/stories/comments/votes over time
 * practical stats like domain quality
 * showing [heavily flagged](https://github.com/lobsters/lobsters/commit/3f69c0eb60fd11856abd0eb89801693e44ba2044) users visually what outliers they are because they really are

**Comment by hmadison** [comment]
The only one I'm aware of is [SVG::Graph](https://github.com/lumean/svg-graph2).

**Comment by pushcx** [comment]
Thanks for finding this. I've [landed our first use](https://lobste.rs/stats) of the gem.
