### ISSUE TITLE
moderator deleted stories appear on domain pages with suggest and cached links

### ISSUE THREAD

**Issue by NattyNarwhal** [lobsters/lobsters#828]
I don't know if this is intentional, but you can see the deleted by moderator tombstones on domain pages (perhaps this is, to make it easy to eyeball for mods) along with options to suggest (showing the title and tags; I have not tried actually submitting it) along with cached (which gives you access to its original URL), which may be less intentional.

Reproduction:

![image](https://user-images.githubusercontent.com/3161292/75039295-b9f2ae80-548e-11ea-93ba-79b3ccacc3f2.png)

https://lobste.rs/domain/danluu.com

**Comment by pushcx** [comment]
Not intentional, that's a bug.

**Comment by sknebel** [comment]
this might be fixed? Example above does not reproduce anymore, and I feel like I've not seen it recently, but could not quickly identify a matching commit.

**Comment by pushcx** [comment]
Looks like I fixed it in 10bab4a7dabb84f5257d4b9488bc745b042332d9 and a92e9988bd67bdc8a85e0f238377c4fd90840c42, and missed closing this bug. Thanks for catching the stale issue, @sknebel.
