### ISSUE TITLE
Rename "troll" to "unhelpful"

### ISSUE THREAD

**Issue by grxnola** [lobsters/lobsters#829]
The word "troll" is ill-defined; is someone only a troll if they're trolling? Can someone who's trolling not be a troll? Where is the line between trolling and being obtuse? These are the questions that a rename to "unhelpful" can be useful. It covers a set of comments which contains all comments that could be considered trolling (without being unkind)  and it's less inflammatory than the word "troll". I'm sure others can come up with more, better reasons for why "unhelpful" is more helpful as it was discussed in IRC the other day with some interesting  feedback.

**Comment by pushcx** [comment]
"Troll" is a statement about [results](https://lobste.rs/s/wei3a9/downvote_category_for_inappropriate#c_ycorze), not motivations.
