### ISSUE TITLE
Feature: A search by `url:` option

### ISSUE THREAD

**Issue by rwanyoike** [lobsters/lobsters#850]
There's a search by `domain:` option, but nothing more granular. This proposal is for a search by `url:` option that can cover the "I want search for submissions that point to this url" use case.

**Comment by emdemir** [comment]
I'll see what I can do.

**Comment by pushcx** [comment]
Note: this should use `Utils.normalize_url`

**Comment by petrenkorf** [comment]
Any updates on this @pushcx?

**Comment by pushcx** [comment]
It doesn't require a `url:` prefix but I added this feature in 5647897a7. If you're scripting, 117a8fe3 added an API.
