### ISSUE TITLE
hide email addresses on the hats page when not logged in

### ISSUE THREAD

**Issue by zg** [lobsters/lobsters#854]
I'm one of the few users with a hat, and I received a spam email because someone scrapped the page.

One way to mitigate this is to require being logged in to view the sensitive contents of how users are validated.

**Comment by arandomandy** [comment]
I'm sorry to hear that, @zg.

This sounds good to me. What do you say, @pushcx ? I suppose my question is whether you think it is useful to display the @domain.ltd? To be honest, I do not but perhaps I misunderstand its purpose. In my mind, if the hat's there, it means someone approved it; that should be enough to prove the veracity of it for others. However, there might be other reasons to include it that I am not aware of.

**Comment by pushcx** [comment]
It's convenient to give a method of contact, as hats are for speaking officially on behalf of a project, so I'd like to keep that display for logged-in users. But yeah, let's not display them publicly.

**Comment by cnst** [comment]
Another option is to use web-pages in place of email addresses.  I believe when the feature was originally implemented by `jcs@`, he was asking for email addresses, because OpenBSD, doesn't have webpages with a catalogue of developers, but in NetBSD we do, and I've added access by ID a decade ago, so, that's a potential improvement to consider (however, it seems like not all developers have bothered to update the official webpage with their name and login).

**Comment by zg** [comment]
> Another option is to use web-pages in place of email addresses. I believe when the feature was originally implemented by `jcs@`, he was asking for email addresses, because OpenBSD, doesn't have webpages with a catalogue of developers, but in NetBSD we do, and I've added access by ID a decade ago, so, that's a potential improvement to consider (however, it seems like not all developers have bothered to update the official webpage with their name and login).

How would that work in the context of someone who has a hat designating that they're an employee for a large corporation, e.g. Apple?

**Comment by jcs** [comment]
This was implemented in #868 and should be closed.

**Comment by pushcx** [comment]
Thanks for catching the stale issue, closing.
