### ISSUE TITLE
Unnecessary JOIN make query slow(search.rb#L138)

### ISSUE THREAD

**Issue by wtune** [lobsters/lobsters#856]
From Database Log we find some queries with unnecessary JOIN produced by [search.rb#L138](https://github.com/lobsters/lobsters/blob/master/app/models/search.rb#L138-L138). One of them is as follows:
```
SELECT 
  COUNT(DISTINCT stories.id) 
FROM 
  `stories` 
  INNER JOIN `domains` ON `domains`.`id` = `stories`.`domain_id` 
  LEFT OUTER JOIN `taggings` ON `taggings`.`story_id` = `stories`.`id` 
  LEFT OUTER JOIN `tags` ON `tags`.`id` = `taggings`.`tag_id` 
  LEFT OUTER JOIN `users` ON `users`.`id` = `stories`.`user_id` 
WHERE 
  `stories`.`merged_story_id` IS NULL 
  AND `stories`.`is_expired` = FALSE 
  AND (domains.domain = 'lobste.rs') 
  AND (
    (
      MATCH(stories.title) AGAINST('term1' IN BOOLEAN MODE) 
      OR MATCH(stories.description) AGAINST('term1' IN BOOLEAN MODE) 
      OR MATCH(stories.story_cache) AGAINST('term1' IN BOOLEAN MODE)
    )
  )
```
It retrieved nothing from taggings  tags and users, so we can remove them from query. And then JOIN dimains will not create duplicate records stories.domain_id is a foreign key, which means we can remove DISTINCT.Finally we can rewrite this query as shown below:
```
SELECT 
  COUNT(stories.id) 
FROM 
  `stories` 
  INNER JOIN `domains` ON `domains`.`id` = `stories`.`domain_id` 
WHERE 
  `stories`.`merged_story_id` IS NULL 
  AND `stories`.`is_expired` = FALSE 
  AND (domains.domain = 'lobste.rs') 
  AND (
    (
      MATCH(stories.title) AGAINST('term1' IN BOOLEAN MODE) 
      OR MATCH(stories.description) AGAINST('term1' IN BOOLEAN MODE) 
      OR MATCH(stories.story_cache) AGAINST('term1' IN BOOLEAN MODE)
    )
  )
```
According to our test it can improve query efficiency by 18%.

**Comment by pushcx** [comment]
Whose test?

**Comment by pushcx** [comment]
User apparently has a tool that clones rails projects, runs their tests, and spams them with worthless micro-optimization bug reports like this one. They've littered dozens of these across GitHub; blocking.
