### ISSUE TITLE
Unnecessary JOIN make query slow(search.rb#L170)

### ISSUE THREAD

**Issue by wtune** [lobsters/lobsters#857]
From Database Log we find some slow queries with unnecessary JOIN produced by [search.rb#L170](https://github.com/lobsters/lobsters/blob/master/app/models/search.rb#L170-L170). One of them is as follows:
```
SELECT 
  COUNT(DISTINCT comments.id) 
FROM 
  `comments` 
  LEFT OUTER JOIN `users` ON `users`.`id` = `comments`.`user_id` 
  LEFT OUTER JOIN `stories` ON `stories`.`id` = `comments`.`story_id` 
WHERE 
  `comments`.`is_deleted` = FALSE 
  AND `comments`.`is_moderated` = FALSE 
  AND `comments`.`story_id` IN (67, 68, 69, 71) 
  AND (
    MATCH(comment) AGAINST(
      'comment2 comment3' IN BOOLEAN MODE
    )
  )
``` 
It retreieved nothing from users and stories so we can remove these table  and DISTINCT from query as shown below:
```
SELECT 
  COUNT(comments.id) 
FROM 
  `comments` 
WHERE 
  `comments`.`is_deleted` = FALSE 
  AND `comments`.`is_moderated` = FALSE 
  AND `comments`.`story_id` IN (67, 68, 69, 71) 
  AND (
    MATCH(comment) AGAINST(
      'comment2 comment3' IN BOOLEAN MODE
    )
  )
```
According to our test it can improve query efficiency by 28%.

**Comment by pushcx** [comment]
Whose test?

**Comment by pushcx** [comment]
User apparently has a tool that clones rails projects, runs their tests, and spams them with worthless micro-optimization bug reports like this one. They've littered dozens of these across GitHub; blocking.
