### ISSUE TITLE
Bug: asset pipeline isn't linking our image in production

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#859]
We only have one image, `app/assets/images/select2.png`. The story edit/submission page displays it in the tag input field to indicate a tag can be removed.

![Screenshot from 2020-05-23 16-42-42](https://user-images.githubusercontent.com/6262/82741099-6702ee80-9d3e-11ea-848d-967f87beaf95.png)

With last week's Rails upgrade, our css is no longer linking to it properly in production; it works fine in development mode. Something breaks with the asset pipeline every minor release, so the task here is to figure out what hoop to jump through to get it linked again properly.

An alternate approach would be to delete the image and edit the css to print an `x` there (perhaps U+2A2F?). The `x` is only one image on a sprite sheet, so it may be a bit of a slog to update.

**Comment by threeplanetssoftware** [comment]
Seems to be working correctly now on production, suggest closing.

![image](https://user-images.githubusercontent.com/10688754/90811809-458cb100-e2f3-11ea-9e4d-2ae761d72c25.png)

**Comment by pushcx** [comment]
...yup. I didn't do anything for this, maybe it was the Rails 6 upgrade. I will whistle past the graveyard on this one.
