### ISSUE TITLE
My first submission (foo.github.io/bar), gives this error: "Url is an unseen domain from a new user"

### ISSUE THREAD

**Issue by xpe** [lobsters/lobsters#860]
Of course, I didn't really literally submit `https://foo.github.io/bar`. If you want me to share the actual URL, I can. 

I'm surprised that `github.io` is an unseen domain.

Is there an FAQ about this geared towards new users?

The error is raised here in the code:
https://github.com/lobsters/lobsters/blob/master/app/models/story.rb#L189

**Comment by pushcx** [comment]
It came from https://lobste.rs/s/utbyws/mitigating_content_marketing

There's an open issue (#834) for me to document it, I'm sorry for the confusion.
