### ISSUE TITLE
Refactoring: rename Comment scope `for_user` to `accessible_to_user`

### ISSUE THREAD

**Issue by roryokane** [lobsters/lobsters#864]
As discussed briefly on [pushcx’s stream today](https://www.twitch.tv/videos/645356413) from 1:14:00 to 1:15:25, this `for_user` scope in the `Comment` model:

https://github.com/lobsters/lobsters/blob/ee42f2f308fcc29b3c9f1250a0de58014ccb3567/app/models/comment.rb#L36

would be better if named `accessible_to_user`, given the separation of the in-development `Comment.not_on_story_hidden_by` scope.

All the callers will need to be renamed too. I see only 7 search results for `.for_user` in the codebase.

**Comment by gabrielbaldao** [comment]
can I get this one?

**Comment by roryokane** [comment]
I’m not working on this, so feel free.

**Comment by gabrielbaldao** [comment]
I cannot watch your video, can you look at this PR? I also did a refact in the scope condition, I wanna know if I am forgetting to change something

**Comment by pushcx** [comment]
Completed by @gabrielbaldao's PR. Thanks again!
