### ISSUE TITLE
[Q] My VPS can no longer connect to the site

### ISSUE THREAD

**Issue by NightMachinary** [lobsters/lobsters#866]
I crawl the RSS feed at https://lobste.rs/top/rss every 15 minutes. This hadn’t been working lately, and when I checked, my VPS couldn’t connect to the site at all. I thought perhaps my hosts.txt is at fault (I use that as an adblocker), but trying with the IP address didn’t work either:

```
❯ curl 71.19.148.33                 
curl: (28) Failed to connect to 71.19.148.33 port 80: Connection timed out
```

The only hypothesis I have is that my IP (82.102.11.148) somehow got blocked?

**Comment by alanpost** [comment]
I did block that IPv4 address, correct.

It was making profoundly more requests than once every 15 minutes--more requests by a large margin than any other IP address.

If you can explain what happened and what you did to fix it I'm happy to lift the block--thank you for reaching out.

**Comment by NightMachinary** [comment]
@alanpost I looked through my log file. It seems rsstail was encountering a parse error, and thus exiting. I have that in a while true loop for fault tolerance (usually the errors are transient network problems), and I think that might have caused a spike. I have now added a sleep timeout of 24 hours between restarts for lobsters, so the problem should hopefully be solved.

BTW, I’d appreciate an invite to the site. :)

**Comment by alanpost** [comment]
I've lifted the IPv4 block that was preventing you from accessing lobste.rs.

If you'd like an invite please visit #lobsters on freenode--join, wait a moment to make sure you're not interrupting, and introduce yourself. You'll be asked for a portfolio, personal website, or other social proof and you may have to visit more than once--the channel is not always active and not always in the mood for invitations but if you can demonstrate that you're a practitioner and with sufficient patience you've a reasonable chance of finding someone to invite you.

Thank you for fixing your script. I'll resolve this ticket. Please write back if you need anything else.
