### ISSUE TITLE
logo traffic pinned at 100% since bugfix

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#873]
https://github.com/lobsters/lobsters/commit/ee42f2f308fcc29b3c9f1250a0de58014ccb3567

Users report that the logo has been pinned at 100% traffic for the several days since I've deployed this commit, so there's almost certainly a bug here. Given that we're pinned at 100% rather than 0%, probably it's failing to count how much activity there's been in the last 90 days.

**Comment by pushcx** [comment]
The above commit didn't fix it. There's more than just timezone going wrong, apparently.

**Comment by emdemir** [comment]
Currently the logo tooltip shows up as 3%. Is there something I'm missing?

**Comment by pushcx** [comment]
Commit 263daed changed the behavior of this bug.

**Comment by threeplanetssoftware** [comment]
The logo seems realistic to me, is this still a bug? It was ~0% most of the night time (U.S./Europe), is sitting at 9% now, had been up at ~23% at the start of the workday when U.S. and Europe would be overlapping their mornings.

**Comment by pushcx** [comment]
This was fixed a long while back, belated close.
