### ISSUE TITLE
Firefox: Content Security Policy blocks JS, Can't vote or comment 

### ISSUE THREAD

**Issue by mdesjardins** [lobsters/lobsters#875]
Hello, I apologize if this has been reported already. I searched the issues but could only find previously closed/addressed problems.

I have been unable to upvote stories or comments, or reply to comments, for several months now while using Firefox. I seem to be able to do these things on Chrome. When I look at the console, I see the following: 

    Loading failed for the <script> with source “https://lobste.rs/assets/application-6bbb1c4d088552cecdd160b2723886ac6ddf78894b49d5c35f755ef142c71f22.js”. lobste.rs:16:1
    Content Security Policy: The page’s settings blocked the loading of a resource at https://lobste.rs/assets/application-6bbb1c4d088552cecdd160b2723886ac6ddf78894b49d5c35f755ef142c71f22.js (“script-src”).
    Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).

The violated policy is:
     Request URL:https://lobste.rs/assets/application-6bbb1c4d088552cecdd160b2723886ac6ddf78894b49d5c35f755ef142c71f22.js
     Request Method:GET
     Referrer Policy:unsafe-url

Not really sure what's happening here? I don't have many add-ons installed and have disabled my ad-blocker (even though this seems unrelated to that). Thanks!

**Comment by mdesjardins** [comment]
nm. I was being an idiot. I *did* have an extension installed that was blocking it. It works fine now, sorry for wasting your time!

**Comment by pushcx** [comment]
No worries. What was the extension, so I know to ask for it if we get a similar report again?

**Comment by mdesjardins** [comment]
I'm *extremely* embarrassed to say that it was a "disable javascript" extension I installed a long time ago and forgotten about, I must have enabled it on lobsters at some point. 😖
