### ISSUE TITLE
Dark mode background color is bright

### ISSUE THREAD

**Issue by kconner** [lobsters/lobsters#884]
When my iOS 14 phone is set to dark mode, the site has a different set of colors applied, but certain regions which look like they would get a black background instead still have a white background. 

Light mode:
![image](https://user-images.githubusercontent.com/602569/87377964-d1742600-c55a-11ea-99d5-46c241d6942b.png)

Dark mode:
![image](https://user-images.githubusercontent.com/602569/87377978-d6d17080-c55a-11ea-940f-46fa4f1235b7.png)

Here the links that are visited (the top two) show more color contrast, not less as in light mode, so it looks like the intent was to have a black background color alongside the other changes.

Article bodies do have a gray background. 

![image](https://user-images.githubusercontent.com/602569/87378284-7ee73980-c55b-11ea-816c-6a4d54d99503.png)

**Comment by pushcx** [comment]
Reverted in 65b0b34 - browser support isn't there yet.
