### ISSUE TITLE
Raise max search result pages to 50

### ISSUE THREAD

**Issue by mohaazeem** [lobsters/lobsters#889]
No matter how many results are returned in the search results, I can’t seem to go beyond page 5. Is that a feature? I tried looking into the code but couldn’t understand if there’s a limitation.

**Comment by pushcx** [comment]
Yes. From the commit message, it looks like it was to work around an issue with Sphinx, which we no longer use for search. So it could be removed.

**Comment by mohaazeem** [comment]
@pushcx thanks for elaborating. May I ask which commit introduced that workaround?

**Comment by pushcx** [comment]
4b768e2f420ecf70949595af4652f955e9b5f4a8

**Comment by pdthomson** [comment]
Is this issue still open? Could I take this on?
