### ISSUE TITLE
Bug: User model considers expired stories when computing most_common_tag, leading to users with 0 stories and a most common tag

### ISSUE THREAD

**Issue by threeplanetssoftware** [lobsters/lobsters#893]
For users with no submitted stories, when viewing their own profile, it claims there is a most commonly used tag. I believe this should not be appearing, since the most common tag of nothing is nothing.

![image](https://user-images.githubusercontent.com/10688754/89106179-b24c1400-d3f5-11ea-8459-460cb0f8ccff.png)

When viewing other user profiles who have no submitted stories, there is no listed tag.

![image](https://user-images.githubusercontent.com/10688754/89106195-cabc2e80-d3f5-11ea-8821-be0a9ecb9e3e.png)

Because the user helper checks to see if a tag exists before inserting that wording, it looks like this error is generated in this method https://github.com/lobsters/lobsters/blob/083dbb1e67d337b1d0481c294b3f362d0c68c2b5/app/models/user.rb#L494

_Edit: My apologies, when inserting the screenshot on a new ticket, the ticket opened itself before it was complete._

**Comment by threeplanetssoftware** [comment]
After testing, realized this was not caused by viewing my own profile but because I had submitted a story a while back and forgotten that I immediately deleted it after realizing it was already posted but search hadn't found it. Can be reproduced in testing/development environment by:

1. Seeding with fake data.
1. Logging in as test user (has no stories)
2. Viewing profile will show 0 submitted stories and no common tag
2. Submitting a story with any tag
3. Immediately deleting the story
4. Viewing profile will show 0 submitted stories with that tag as the most common.

I am not sure if this is intended or unintended behavior, but for users with no posts it looks like a bug without an explanation. I can understand if this is not accepted based on the desire to see all tags even after moderation and will accept the closure of this issue as a feature without implementation if that is the desire.

**Comment by alanpost** [comment]
> I am not sure if this is intended or unintended behavior, but for users with no posts it looks like a bug without an explanation.

It's a bug. Similar to issue #790.
