### ISSUE TITLE
Got "Url is an unseen domain from a new user" when submit URL at Github Pages

### ISSUE THREAD

**Issue by erthink** [lobsters/lobsters#896]
I got the "Url is an unseen domain from a new user" error when submitting the https://erthink.github.io/libmdbx/ (i.e. without custom domain) to the https://lobste.rs/stories.

What could be the reason?

**Comment by pushcx** [comment]
The reason is that you are a new user and it is an unseen domain. Usually that means someone showed up to market themself. I see in the log you also tried to use bitly to conceal your activity. Don't do that.

**Comment by erthink** [comment]
Thank for clarification.
