### ISSUE TITLE
Story model: recognize links with or without .htm(l) as related

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#897]
http://brooker.co.za/blog/2020/06/23/code (https://lobste.rs/s/efrg4x[](story)) and http://brooker.co.za/blog/2020/06/23/code.html ([https://lobste.rs/s/u2tkhs](story)) weren't recognized as similar URLs but seem reasonable to detect.

Tests for this should look something like `example.com/foo` matching `example.com/foo.html` and `example.com/foo.htm` and vice-versa.

**Comment by Thunderbottom** [comment]
Also found another issue with a [recent post](https://lobste.rs/s/k5n7ot/generics_for_go), which was also [posted](https://lobste.rs/s/ac83w9/generics_for_go) around a month ago.

Although the problem in here is that the article posted a month ago has the link:

```
https://lwn.net/SubscriberLink/824716/ee9bbbfad58cef3d/
```

Whereas the one posted today links to:

```
https://lwn.net/Articles/824716/
```

Intrinsically though, on loading, the first article resolves to the second URL. Wanted to ask if lobste.rs should try to resolve the link before allowing it to be posted? That kind of solves this issue. Also, as a side effect, it would also check whether the link is accessible.

**Comment by 00-matt** [comment]
@Thunderbottom When the LWN article was first posted, it didn't have a redirect. Only a couple of weeks later when it became publicly available for non-subscribers did it become a redirect.

**Comment by Thunderbottom** [comment]
Fair, I did not know that. But I feel it would still make sense to try and resolve URLs before allowing the user to post, no? It would (to some extent) prevent duplicate or even dud links from being posted.

**Comment by pushcx** [comment]
Yeah, worth doing. The submission form tries to use canonical URLs; it's worth expanding that into recognizing redirects (see `canonical_target` in `app/models/story.rb`).

As a benefit, it could also prevent the use of unknown link shorteners.

**Comment by pushcx** [comment]
This code was entirely redesigned in 42d3ad4c which solved this issue.
