### ISSUE TITLE
Web-based category editing

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#917]
We have basic CRUD forms for admins to create and edit tags with updates to the modlog. We could use the exact same functionality for categories. Same logging, same permissions, very similar forms. This should be pretty straightforward to implement given that it basically involves porting over `TagsController` (except `index`) with its views and tests.

(Maybe I can sucker @threeplanetssoftware into this given his familiarity with tag editing code from #898 and categories from #914?)

**Comment by threeplanetssoftware** [comment]
Sure, I'll take a peek.

**Comment by alanpost** [comment]
Thank you for your interest @threeplanetssoftware.
