### ISSUE TITLE
Doffed hats are offered when composing or replying to private messages

### ISSUE THREAD

**Issue by jcs** [lobsters/lobsters#927]
Though sending with a doffed hat returns an error as expected.

![hat](https://user-images.githubusercontent.com/9888/92140046-783faa80-edc5-11ea-845e-1e8f6e4b3e0d.png)

**Comment by threeplanetssoftware** [comment]
I ran through the other places "hats" came up in the code base and believe this is the last place that all hats should have been changed to wearable hats.

**Comment by pushcx** [comment]
Thanks for the bug report and the fix. For anyone curious, there have only been 8 hats doffed.
