### ISSUE TITLE
"Mysql2::Error: Got error 'missing ) at offset 686' ...

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#931]
Someone pasted a URL and a little extra into a the story url: `https://wiki.freebsd.org/VCSWhy (`. This passed through `check_url_dupe` to `most_recent_similar` which failed to escape the character and threw an error. I've pasted the traceback below, but I think it's truncated - surely it must continue execution through `similar_stories` and `Story.find_similar_by_url`.

```
  app/models/story.rb:280:in `most_recent_similar'
  app/models/story.rb:180:in `already_posted_recently?'
  app/controllers/stories_controller.rb:359:in `check_url_dupe'
  config/initializers/production.rb:42:in `call'
```

For this bug, please add the given URL as a test and then make it pass. This is probably a fix to `find_similar_by_url`. I recently touched this in 03be4f8 - I don't think that change caused this bug, but they probably have a common cause of improper escaping. I could be convinced that we should pull in a library for this work, that method's actual meaning of "what we consider a similar url" is getting bogged down in the mechanics of checking for them.

(I had a moment of paranoia this might point to SQL injection, but @hmadison pointed out we're getting an error constructing a valid regular expression, we're correctly using ActiveRecord's `where` parameters. And as a bonus he pointed out that we could speed this up significantly by joining to `Domain` because that always matches and cuts the number of rows down from all stories to, median case, like four.)

**Comment by hmadison** [comment]
If anyone is looking at tackling this, the `Story.find_similar_by_url` method itself can be dried up significantly using the [`Regexp.ecapse`](https://ruby-doc.org/core-2.6.5/Regexp.html#method-c-escape) method present in Ruby 2.6.

**Comment by jmks** [comment]
So this is behaving weird for me. I can easily replicate the error in the UI.

But when I try to write a test, it never crashes. Stepping through the code, I can see where the SQL is executed, but if I take the `to_sql` output and try it in mysql, it gives the error. Yet the Ruby code gives me a value.

Even for the previous change in 03be4f8, if I comment out the added escape code, the test still passes.

In any case, when you escape the regex part of the query, the `check_url_dupe` endpoint no longer crashes with either `https://wiki.freebsd.org/VCSWhy (` nor `http://aaonline.fr/search.php?search&criteria[title-contains]=debian`).

**Comment by pushcx** [comment]
This bug is a really finicky bit of quoting. Even not seeing it, I'd guess your test has one too many or one too few `\`s, or it's the difference between `.to_s` and `.inspect` when you're getting a value to debug.
