### ISSUE TITLE
Users JSON isn't actually JSON

### ISSUE THREAD

**Issue by twodayslate** [lobsters/lobsters#935]
https://lobste.rs/u.json is not actually JSON and the returned content type is text/html instead of application/json

Seems to just be returning https://github.com/lobsters/lobsters/blob/142edb664e9a89cb8156f2c6124a6ca03b16c6cd/app/views/users/tree.html.erb without the layout

**Comment by magikid** [comment]
It doesn't look like that endpoint supports JSON currently.  https://github.com/lobsters/lobsters/blob/df5b1e0487094405af196b6322dc09192f27ee5b/app/controllers/users_controller.rb#L53

In #116, the routes were updated to be explicit about which routes supported which formats and I don't see the user route annotated that it supports JSON.  In the corresponding ticket (#115) though, I see that @jcs [mentioned](https://github.com/lobsters/lobsters/issues/115#issuecomment-33144051) adding a proper JSON view of the user pages but I don't see any other tickets related to that work or any other work done in that regard.

**Comment by pushcx** [comment]
The frontend js doesn't need to consume json of that, so the site doesn't emit it. The bug is that it's responding at all, which is details in #746 and #1114, so I'm closing this in favor of those.
