### ISSUE TITLE
Repeated text in message

### ISSUE THREAD

**Issue by elpres** [lobsters/lobsters#937]
The passage "your account your account" looks like a typo to me:

https://github.com/lobsters/lobsters/blob/21524de9ed70d15384a3c1371f68e500b0e7cede/app/controllers/settings_controller.rb#L29

**Comment by pushcx** [comment]
Yep, thanks for pointing it out. Funny how many people read right over this before it went live. Fixed bd15ccba9e25f579a4d24c8bd348d03775c349dd.
