### ISSUE TITLE
All subdomains of a domain should be treated as being the same domain

### ISSUE THREAD

**Issue by Hexstream** [lobsters/lobsters#943]
I tried posting a meta thread about this, but new users can't do that.
Frankly, I think the new user experience is pretty wonky.

I understand that it's a good idea to treat different subdomains as different domains generally, but in the context of "previously unseen domain detection" and domain search, I think it's pretty obviously preferable to treat all subdomains of a domain as being the same domain, except in the case of subdomains of popular hosts like github.io.

I got bitten by this. As a new user, I had to rely on someone else to post [this](https://lobste.rs/s/xw0ebc/hexstreamsoft_public_domain_common_lisp), even though  [something from hexstreamsoft.com had already been posted by someone else](https://lobste.rs/s/lrbb7i/common_lispers_list). Note that hexstreamsoft.com has 6 subdomains (if we don’t count the tarballs subdomain). `www.hexstreamsoft.com` and `common-lispers.hexstreamsoft.com` ought to be treated as the same domain (`hexstreamsoft.com`) for the purpose of previously unseen domain detection.

Same thing for site search. [A query for `domain:hexstreamsoft.com`](https://lobste.rs/search?q=domain%3Ahexstreamsoft.com&what=stories&order=relevance) (or `domain:*.hexstreamsoft.com`?) obviously ought to return the stories from both `www.hexstreamsoft.com` and `common-lispers.hexstreamsoft.com`.

**Comment by pushcx** [comment]
The prohibition on unseeen domains from new users exists as a speedbump for people who show up to promote themselves, exactly like what you tried to do. It's working as intended.

**Comment by Hexstream** [comment]
Congratulations on immediately censoring the important context that I had posted in the thread.

I should have known better than trusting this apparently ethical site instead of independently saving all my stuff as I so often do.

[Note that self-promotion of relevant content is highly appreciated on the site.](https://lobste.rs/s/tnpfea/meta_could_we_consider_banning_self)

[Congratulations on deliberately breaking the Internet Archive.](https://web.archive.org/web/20200919164228/https://lobste.rs/s/tnpfea/meta_could_we_consider_banning_self)

**Comment by pushcx** [comment]
Ah yes, quality content showing off your marketing chops:

> If you really want a “story”, how about this:
> 
> According to Alexa, HexstreamSoft is now the #1 Common Lisp site as of October 2020, and the site has been trending upwards for 60+ consecutive days as of 4 November 2020, with 2 trivial exceptions.
> 
> The absolutely insane site engagement metrics have been roughly around 14 Daily Pageviews Per Visitor, 25 minutes Daily Time on Site and 25% Bounce Rate for a good while.

You misunderstand that Wayback Machine snapshot. Comparing the timestamp in the URL to the timestamp visible when hovering over the "1 minute ago", the snapshot was taken 98 seconds after that story was posted. It doesn't have comments on it because it was taken before anyone could comment.

**Comment by Hexstream** [comment]
> The prohibition on new users posting meta exists as a speedbump to people who try to change community norms without taking time to understand them, exactly as you are trying to do here. It's working as intended.

There is no need to understand community norms to understand or point out or acknowledge that `foo.bar.com` should obviously be treated as the same domain as `www.bar.com` for the purpose of previously unseen domain detection, unless `bar.com` is a host with user subdomains like `github.io`.

Sorry, I believe your handling of this situation is fully insane, although I certainly don't represent that I think it won't get even more insane.

**Comment by pushcx** [comment]
Please explain what kind of use and abuse of subdomains Lobsters was seeing when the rule was introduced, how that related to how Lobsters has parsed and built features on domains for eight years, and how your preferred usage differs.

**Comment by Hexstream** [comment]
> Ah yes, quality content showing off your marketing chops:

You "forgot" my 2 additional comments in the thread, especially the big one.

**Comment by Hexstream** [comment]
> You misunderstand that Wayback Machine snapshot. Comparing the timestamp in the URL to the timestamp visible when hovering over the "1 minute ago", the snapshot was taken 98 seconds after that story was posted. It doesn't have comments on it because it was taken before anyone could comment.

Right, sorry, I was wrong about that particular point. [The new snapshot works.](https://web.archive.org/web/20201106170830/https://lobste.rs/s/tnpfea/meta_could_we_consider_banning_self) So many people deliberately break the Internet Archive that I was a bit careless.

**Comment by Hexstream** [comment]
> Please explain what kind of use and abuse of subdomains Lobsters was seeing when the rule was introduced, how that related to how Lobsters has parsed and built features on domains for eight years, the limitations we've been debating this fall

This would surely be better summarized by an eminent expert such as yourself rather than a newbie like me. This undue shift of burden is bizarre, but admittedly much less bizarre than reflexively and unilaterally censoring highly relevant content on your site when relevant self promotion is widely and explicitly appreciated by its community, [per the highly upvoted comments on this thread](https://lobste.rs/s/tnpfea/meta_could_we_consider_banning_self).

**You knowingly and deliberately shat on a decade of Common Lisp Open Source, against your community's best interests. That's pathetic.**

**Comment by pushcx** [comment]
To fill you in on community norms as a newbie, characterizing someone's actions as insane or as shitting on a community is not normal or acceptable behavior on Lobsters.

**Comment by Hexstream** [comment]
We are not on Lobsters, and you are distracting from the relevant point exactly as a relentless power abuser would do.
It's pretty hard to believe that this is an isolated incident.

**Comment by pushcx** [comment]
I know you've made a point of not understanding how the site works, but the comments you left on your ad are in fact still visible in many places on the site.

Speaking of not being on Lobsters, you may not have seen this note on the about page:

>   If you dislike the content or moderation policies here, you may prefer  <a href="https://news.ycombinator.com">Y Combinator News</a>,  <a href="https://reddit.com/r/programming">r/programming</a>,  <a href="https://slashdot.org">Slashdot</a>,  <a href="https://tilde.news">Tilde News</a>,  <a href="https://en.wikipedia.org/wiki/Comp.*_hierarchy">comp.*</a>, or  <a href="http://boards.4chan.org/g/">/g/</a>.

Sounds like the last one may the best fit for your communication style. Best of luck out there with your advertising.
