### ISSUE TITLE
Can't delete messages

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#946]
When a story is edited from user suggestions, the submitter gets a `Message` notifying them from the "System" account. In the database this works by setting `author_user_id` to `0`.

It's not possible for the recipient to delete this message. They'll get a 500 because the soft deletion throws `ActiveRecord::RecordInvalid "Validation failed: Author must exist"`.

If someone wants to pick this up, you don't need to test all of the setup, just a model test that a message from "System" can have `deleted_by_recipient` set to `true`, as happens in `MessagesController#destroy`.

**Comment by dracconi** [comment]
I have addressed this in #970.
