### ISSUE TITLE
Recognize arxiv url dupes

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#954]
https://lobste.rs/s/zm1xgo/air_fi_generating_covert_wi_fi_signals

We pretty regularly get people submitting both the arxiv page and the direct link to the pdf, let's recognize them as dupes. This patch will be in `Story.find_similar_by_url`.

**Comment by prabuw** [comment]
Hello - long time fan of the site. 

@pushcx I am happy to pick this issue up and contribute a PR?

**Comment by pushcx** [comment]
You don't need permission, please go right ahead. :)

**Comment by prabuw** [comment]
Cheers - PR raised. 👍🏽

**Comment by pushcx** [comment]
https://lobste.rs/s/kcyg0p/gwp_asan_sampling_based_detection_memory

This story had an alternate arxiv URL merged in. I don't know if it's a new URL structure on their part or a bug on ours that we didn't identify it, but it's the first dupe I'm aware of in the 2.5y since this was merged.

**Comment by fanf2** [comment]
There’s a v2 at the end of the URL that isn’t matched by the arxiv dup detector

**Comment by pushcx** [comment]
Yep, that was it, good eye.
