### ISSUE TITLE
Twitter account @lobsters has stopped posting new stories

### ISSUE THREAD

**Issue by moreati** [lobsters/lobsters#959]
The account https://twitter.com/lobsters normally tweets new stories from https://lobste.rs. On 4th Jan 2021 it stopped.

The last story tweet was [CRUSH: Controlled, Scalable, Decentralized Placement of Replicated Data](https://twitter.com/lobsters/status/1345946898608381953) for https://lobste.rs/s/ax9uso, at 4:15 AM · Jan 4, 2021 (UTC I think).

**Comment by pushcx** [comment]
It's on my to-do list to fix this, though it's behind some critical db performance work.

**Comment by pushcx** [comment]
Fixed, caught up on backlog.

When I regenerated the API keys they were reset to read-only. I needed to change the app to requesting read-write and regenerate again.

**Comment by eddyg** [comment]
Thanks for fixing! 😄
