### ISSUE TITLE
Reduce the scope of twitter permissions requested

### ISSUE THREAD

**Issue by acatton** [lobsters/lobsters#966]
Hi there,

When connecting one's lobste.rs account to twitter, the permissions requested are extremely broad:

![Screenshot from 2021-01-20 22-13-18](https://user-images.githubusercontent.com/3966553/105238096-cc78da80-5b6c-11eb-8d77-17c445123fb8.png)

Could these permissions be reduced to a bare minimum required for lobste.rs? Maybe just "See your Twitter profile information and account settings.".

Thanks!

**Comment by pushcx** [comment]
We had a brief discussion on IRC - this is an error, it only needs the barest permission to confirm you own the account. Something must have reset to a default when I regenerated the API keys.

**Comment by pushcx** [comment]
Twitter shut down their API.
