### ISSUE TITLE
Reduce comment double-posting

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#967]
Our current database setup is occasionally significantly slower than previous. We've seen a rash of double-posted comments because it looks like nothing's happened.

We're working on replacing the slow database, but in any case, we should prevent this. Off the top of my head, this probably looks like updating `CommentsController.create` to look for a comment from the author in the last ten minutes with identical text. If one is found, silently skip creating a comment and render the existing one. There's a `spec/requests/comments_spec.rb` that a test for this behavior can live in.

**Comment by meaagan** [comment]
I believe this is already done on line 38 of comments_controller.rb.

**Comment by pushcx** [comment]
Unfortunately, no. That code's been present a long time and hasn't fired here. I'd guess it's the `params[:preview].blank?` causing it to get skipped. I don't understand why that clause is there but want to think about it and research a bit before I remove it.

And even if that is changed, it's worth having @arp242's nicer UI design to make it clear that something is happening while waiting for a comment to post.
