### ISSUE TITLE
Karma suddenly increased

### ISSUE THREAD

**Issue by benwr** [lobsters/lobsters#980]
Last week, I (user bwr) believe I had something like 350 karma. Today I have 544. I didn't comment or post during that week, and as far as I can tell none of my content rose from the dead to receive hundreds of votes.

Did the karma aggregation formula change? I'm not complaining, but figured it might be some kind of bug.

**Comment by pushcx** [comment]
Not a bug, but I can see why it'd surprise. It was a one-off manual bonus. The mod log message was:

> +152 karma to everyone who flagged or hid this troll post without commenting (number of mistaken upvotes)

The story was /s/evs3px, a troll post about github renaming the `master` branch that linked to a neo-nazi website.
