### ISSUE TITLE
Comments in user's "flagged comments" view are visible even if comment removed by mod action

### ISSUE THREAD

**Issue by gustafe** [lobsters/lobsters#983]
The page https://lobste.rs/u/\<user\>/standing displays the current state of flags on comments (and stories?). It is followed by a list of comments made by the user that have been flagged.

Currently, my page displays the links and text of the following comments, which were made on recently deleted story: 

* https://lobste.rs/s/evs3px/github_f_ck_your_name_change#c_twhqs7
* https://lobste.rs/s/evs3px/github_f_ck_your_name_change#c_0rwq0y
* https://lobste.rs/s/evs3px/github_f_ck_your_name_change#c_ndhbpj

However, as the entire story is deleted, the links lead to an error page.

Suggested behavior:

* do not show the links to non-existent comments on the "standings" page

**Comment by pushcx** [comment]
Since 92f431d1c0a25efe428d4021c51218e8cf4ceaf4, logged-in users see a message explaining removed stories, so this is fixed in a roundabout way.
