### ISSUE TITLE
Dependency on mimemagic 0.3.x no longer valid

### ISSUE THREAD

**Issue by liviux** [lobsters/lobsters#989]
Any solutions for installing the current version of lobsters? I always hit "Dependency on mimemagic 0.3.5 no longer valid" and installations stop. Can't find a workaround yet.
I know it's  a big problem for a loooot of apps, more here - [https://dev.to/cseeman/what-s-up-with-mimemagic-breaking-everything-he1](https://dev.to/cseeman/what-s-up-with-mimemagic-breaking-everything-he1)

**Comment by natestemen** [comment]
I hit this as well, and haven't found a workaround.

**Comment by pushcx** [comment]
It was an upstream issue with Rails. I'll bump our version shortly to handle it.

**Comment by nsteinmetz** [comment]
To test the software:
* In the `Gem.file` you can change the rails version for `gem "rails", "~> 6.0.3.7"` (at least `6.0.3.6` which has the fix
* Add a `bundle update` step which will update the `Gemfile.lock` file accordingly

I'm not a ruby/rails user but it was good enough to be able to test lobsters in docker containers.

**Comment by cameronhotchkies** [comment]
This appears to have been resolved in [commit 431e67ae ](https://github.com/lobsters/lobsters/commit/431e67aec3f5890a09cca0d82e99f483e282f50f)

**Comment by pushcx** [comment]
Closing this out - it was fixed in a bump. Looks like Rails has moved the dep to a gem named mime_magic.
